### ISSUE TITLE
Not releasing USB device when disabling port

### ISSUE THREAD

**Issue by TheBum** [cminyard/ser2net#10]
I have an application where a device connected via USB can get commands from a script, written directly to /dev/ttyUSB0, or from an app connected via TCP port 4030. The script can communicate via the device file after boot until a connection is made on 4030, and then it can never write to it again, even after disabling the port using the ser2net control port (setportenabled 4030 off). IMO, ser2net shouldn't keep the device tied up while the port is disabled.

**Comment by cminyard** [comment]
On Mon, May 06, 2019 at 06:25:12PM -0700, TheBum wrote:
> I have an application where a device connected via USB can get commands from a script, written directly to /dev/ttyUSB0, or from an app connected via TCP port 4030. The script can communicate via the device file after boot until a connection is made on 4030, and then it can never write to it again, even after disabling the port using the ser2net control port (setportenabled 4030 off). IMO, ser2net shouldn't keep the device tied up while the port is disabled.

Disabling the port will not immediately kick off any connection on it,
it just disables new connections.  There is a separate command to kick
anything off the connection, you will have to use that if you want that
to happen.  So perhaps the port is still connected?

If there is no connection on the port, ser2net does not have the device
open.  If ser2net opens and closes the port and it no longer works, that
could be an issue with the device driver.

-corey

**Comment by cminyard** [comment]
Assuming that my comments resolved the issue.
