### ISSUE TITLE
ser2net[]: Unexpected scalar value on line 0 column 0

### ISSUE THREAD

**Issue by hairem** [cminyard/ser2net#100]
I am trying to set up a ser2net as I have before, but I keep getting this error.

Here is my yaml file:
'''
YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &con0096
    accepter: tcp,2000
    enable: off
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              115200n81,local

connection: &con1096
    accepter: tcp,2001
    enable: off
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyS1,
              9600n81,local

connection: &con0192
    accepter: tcp,5000
    enable: on
    options:
      banner:
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyS0,
             9600n81,local

connection: &con1192
    accepter: tcp,3001
    enable: off
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyS1,
              19200n81,local
'''

I am doing this on a Raspberry Pi Zero, and I have done this setup a few times with no issue but this one is new. I confirmed the serial port works, /dev/ttyS0, using minicom.

Any Ideas?

**Comment by cminyard** [comment]
On Tue, Aug 01, 2023 at 07:17:24AM -0700, Michael wrote:
> I am trying to set up a ser2net as I have before, but I keep getting this error.
> 
> Here is my yaml file:
> '''
> YAML 1.1

You are missing the % before YAML.

-corey

**Comment by hairem** [comment]
That crazy because I never removed the % sign. Thanks

**Comment by hairem** [comment]
The % fixed my issue but now my connection will only stay connected for about 2 sec and disconnect me. Any idea what would cause this? I was able to use minicom for 30 minutes without data loss but then when I connect through the ser2net port it drops me ever 2 to 3 seconds.

**Comment by cminyard** [comment]
On Wed, Aug 02, 2023 at 01:16:07PM -0700, Michael wrote:
> The % fixed my issue but now my connection will only stay connected for about 2 sec and disconnect me. Any idea what would cause this? I was able to use minicom for 30 minutes without data loss but then when I connect through the ser2net port it drops me ever 2 to 3 seconds.

I don't know, that's odd

The banner on &con0192, which is the only port that is enabled, is
blank.  Maybe that's the issue?

-corey

**Comment by hairem** [comment]
I've removed the banner before on other versions of this without issue. I
can connect and get data but again it's only for a sec

**Comment by cminyard** [comment]
On Wed, Aug 02, 2023 at 02:52:33PM -0700, Michael wrote:
> I've removed the banner before on other versions of this without issue. I
> can connect and get data but again it's only for a sec

Try taking off kickolduser.  Well, just try taking off everything except
the connecter, acceptor, and enable.

-corey

>

**Comment by hairem** [comment]
Tried the kick old user it gave me a ton of errors. I'll try the others
later

**Comment by cminyard** [comment]
On Wed, Aug 02, 2023 at 05:42:29PM -0700, Michael wrote:
> Tried the kick old user it gave me a ton of errors. I'll try the others
> later

If you remove kickolduser and get errors, you probably have something
else trying to use the port.  But what are the errors, exactly?

-corey

>

**Comment by hairem** [comment]
I'll do again and send the errors tomorrow. I have no idea what else would
be using the port, I am the only one connecting to it and it's the in board
uart serial port /dev/ttyS0 on a pi zero.

**Comment by hairem** [comment]
I reinstalled ser2net and tried what you suggested, the errors stopped but the connection is still dropping every second. here is the yaml file:
'''
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &con0192
    accepter: tcp,5000
    enable: on
    options:
      banner:
      kickolduser:
      telnet-brk-on-sync:
    connector: serialdev,
              /dev/ttyS0,
             9600n81,local
'''

**Comment by cminyard** [comment]
On Thu, Aug 03, 2023 at 10:06:07AM -0700, Michael wrote:
> I reinstalled ser2net and tried what you suggested, the errors stopped but the connection is still dropping every second. here is the yaml file:

Just remove the entire options section.  Don't blank things out.  I
don't think that's legal YAML code.

-corey

**Comment by hairem** [comment]
That seems to have fixed the problem

**Comment by cminyard** [comment]
On Thu, Aug 03, 2023 at 12:11:58PM -0700, Michael wrote:
> That seems to have fixed the problem

Ok.  I'm not sure why it's not giving you an error when it loads the
config.  I'll have to look at that.

-corey

>

**Comment by hairem** [comment]
Yeah this was an odd journey

**Comment by cminyard** [comment]
I spent some time looking at this, and it turns out that if you leave the value empty in a list in yaml, it gives you and empty string as the value.  In some cases that's legal.  Like an empty banner.  For something like kickolduser: it will interpret an empty as "true" because of the tools it's using to process the code.  So I guess that's legal.  I'm still not sure what was causing all the issues, but everything seems good now.
