### ISSUE TITLE
Weird chars when running to Cisco devices

### ISSUE THREAD

**Issue by rgomez-eng** [cminyard/ser2net#101]
Hi,

Running the packaged 4.3.3 version in Raspberry OS.

Here is the config file:

```
root@raspberrypi:/etc# cat /etc/ser2net.yaml 
%YAML 1.1
---

define: &banner \r\nRemote console server - Port \p device \d [\s]\r\n\r\n

connection: &con0096
    accepter: tcp,8601
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              9600n81,local


connection: &con0097
    accepter: tcp,8602
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB1,
              9600n81,local

connection: &con0098
    accepter: tcp,8603
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB2,
              9600n81,local

connection: &con0099
    accepter: tcp,8604
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB3,
              9600n81,local
```

What happens is the keyboard reactions are very weird.

For example in Cisco device if I want to auto complete any command using TAB it will go like this.

`Cisco#conf^I`

Going directly from the device using screen works fine.

I wonder if I'm missing something in configuration.

**Comment by cminyard** [comment]
On Thu, Aug 03, 2023 at 09:37:25AM -0700, rgomez-eng wrote:
> Hi,
> 
> Running the packaged 4.3.3 version in Raspberry OS.

How are you connecting to ser2net?  If you are using telnet, then you
need to put "telnet" in the accepter.

-corey

**Comment by rgomez-eng** [comment]
> On Thu, Aug 03, 2023 at 09:37:25AM -0700, rgomez-eng wrote: Hi, Running the packaged 4.3.3 version in Raspberry OS.
> How are you connecting to ser2net? If you are using telnet, then you need to put "telnet" in the accepter.
> […](#)
> -corey
> Here is the config file: ``` ***@***.***:/var/lib/dpkg/info# cat /etc/ser2net.yaml %YAML 1.1 --- define: &banner \r\nRemote console server - Port \p device \d [\s]\r\n\r\n connection: &con0096 accepter: tcp,8601 enable: on options: banner: *banner kickolduser: true telnet-brk-on-sync: true connector: serialdev, /dev/ttyUSB0, 9600n81,local connection: &con0097 accepter: tcp,8602 enable: on options: banner: *banner kickolduser: true telnet-brk-on-sync: true connector: serialdev, /dev/ttyUSB1, 9600n81,local connection: &con0098 accepter: tcp,8603 enable: on options: banner: *banner kickolduser: true telnet-brk-on-sync: true connector: serialdev, /dev/ttyUSB2, 9600n81,local connection: &con0099 accepter: tcp,8604 enable: on options: banner: *banner kickolduser: true telnet-brk-on-sync: true connector: serialdev, /dev/ttyUSB3, 9600n81,local ``` What happens is the keyboard reactions are very weird. For example in Cisco device if I want to auto complete any command using TAB it will go like this. `Cisco#conf^I` Going directly from the device using screen works fine. -- Reply to this email directly or view it on GitHub: #101 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

That worked like a charm. Should have read the sample file much better.

Thanks.
