### ISSUE TITLE
Is the a way to get this working over SSH instead of telnet 

### ISSUE THREAD

**Issue by Saman-K** [cminyard/ser2net#102]
I want to use SSH when I connect. the guide is not clear.

Is there a way to do that? if not can you add that in the user guide?

thanks

**Comment by cminyard** [comment]
On Thu, Aug 31, 2023 at 05:19:03AM -0700, Saman.K wrote:
> I want to use SSH when I connect. the guide is not clear.
> 
> Is there a way to do that? if not can you add that in the user guide?

You cannot currently use ssh to connect.  It's more complicated than you
think.  None of the current ssh implementations are modular and the ssh
protocol is wrapped around a lot of things that make it hard to use for
this purpose.

There are tools as part of gensio that will let you make a secure
authenticated connection.  You can search for gtlssh in README.rst and
ser2net.yaml.5 for more information.

If you need more help, please ask.

-corey
