### ISSUE TITLE
can some help me migrating conf to yaml

### ISSUE THREAD

**Issue by sonewtogithub** [cminyard/ser2net#104]
In ser2net.conf I had this string :
2001:raw:600:/dev/ttyUSB0:115200 NONE 1STOPBIT 8DATABITS XONXOFF LOCAL -RTSCTS

I had to reinstall ser2net on my raspberry, but I don't succeed in translating the string to yaml.

How to migrate this string.
If I have to put my question somewhere else please tell me where, with my sincere excuses for asking it here.

**Comment by cminyard** [comment]
On Fri, Oct 06, 2023 at 06:41:23AM -0700, sonewtogithub wrote:
> In ser2net.conf I had this string :
> 2001:raw:600:/dev/ttyUSB0:115200 NONE 1STOPBIT 8DATABITS XONXOFF LOCAL -RTSCTS
> 
> I had to reinstall ser2net on my raspberry, but I don't succeed in translating the string to yaml.

connection: &con1
  accepter: tcp,localhost,2001
  connector: serialdev,/dev/ttyUSB0,115200n81,xonxoff,local

rtscts is off by default.

-corey

**Comment by sonewtogithub** [comment]
Thnx

Op vr 6 okt. 2023 18:24 schreef Corey Minyard ***@***.***>:

**Comment by Conan179** [comment]
Could someone help me too? Unfortunately I don't understand yaml :(
2021:raw:0:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner

**Comment by cminyard** [comment]
On Sun, Oct 29, 2023 at 01:17:18PM -0700, Conan179 wrote:
> Could someone help me too? Unfortunately I don't understand yaml :(
> 2021:raw:0:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner
> 

define: &banner1 banner text
connection: &con1
  accepter: tcp,localhost,2021
  connector: serialdev,/dev/ttyUSB0,115200n81,xonxoff
  options:
    banner: banner1

The example yaml file has a lot of info on this.

-cotey

**Comment by Conan179** [comment]
That's right, there's a lot in the yaml example, too much it overwhelmed me. Thanks for your help.

**Comment by Conan179** [comment]
@cminyard 
Unfortunately, I have to say, it doesn't work.
I can't access the ttyUSB0 from outside.

**Comment by cminyard** [comment]
On Mon, Oct 30, 2023 at 11:51:22AM -0700, Conan179 wrote:
> @cminyard 
> Unfortunately, I have to say, it doesn't work.
> I can't access the ttyUSB0 from outside.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/cminyard/ser2net/issues/104#issuecomment-1785847291
> You are receiving this because you were mentioned.

Can you send your full yaml file?

**Comment by cminyard** [comment]
Oh, sorry, you need to take out localhost:

define: &banner1 banner text
connection: &con1
  accepter: tcp,2021
  connector: serialdev,/dev/ttyUSB0,115200n81,xonxoff
  options:
    banner: banner1

**Comment by Conan179** [comment]
> Oh, sorry, you need to take out localhost:
> 
> ```
> define: &banner1 banner text
> connection: &con1
>   accepter: tcp,2021
>   connector: serialdev,/dev/ttyUSB0,115200n81,xonxoff
>   options:
>     banner: banner1
> ```

Yup, that works.
An optical thing that doesn't affect the function, when you start the connection it says "banner1" at the top left, nothing more.

**Comment by cminyard** [comment]
On Mon, Oct 30, 2023 at 12:59:19PM -0700, Conan179 wrote:
> > Oh, sorry, you need to take out localhost:
> > 
> > ```
> > define: &banner1 banner text
> > connection: &con1
> >   accepter: tcp,2021
> >   connector: serialdev,/dev/ttyUSB0,115200n81,xonxoff
> >   options:
> >     banner: banner1
> > ```
> 
> Yup, that works.
> An optical thing that doesn't affect the function, when you start the connection it says "banner1" at the top left, nothing more.

Oops, that
   banner: banner1
line should be
   banner: *banner1

Without the "*" it just prints the text you put there.
