### ISSUE TITLE
Need help converting old ser2net.conf to .yaml

### ISSUE THREAD

**Issue by Ay1tsMe** [cminyard/ser2net#108]
Hi

I'm looking into connecting a Russound CAA66 to my Linux machine using the following ser2net.conf:
```
BANNER:banner:CONSOLE LAB Terminal Server TCP port p device d serial parms srn
 
TRACEFILE:tr1:/var/log/ser2net/p-Y-M-D-H:i:s.U
6271:telnet:0:/dev/ttyUSB0:19200 8DATABITS NONE 1STOPBIT banner tr=tr1 timestamp
```

The config above was created a few years ago and can be found [here.](https://community.home-assistant.io/t/anyone-using-russound-rnet-component-i-could-use-a-walkthrough/7211/14) As I'm unfamiliar with the project and how the new .yaml config works, It would be great help if this was explained. How would I convert this to the .yaml format that the ser2net requires so I can get this running as intended. 

Thanks for the help!

**Comment by cminyard** [comment]
On Wed, Nov 15, 2023 at 04:10:51AM -0800, Adam Wyatt wrote:
> Hi
> 
> I'm looking into connecting a Russound CAA66 to my Linux machine using the following ser2net.conf:
> ```
> BANNER:banner:CONSOLE LAB Terminal Server TCP port p device d serial parms srn
>  
> TRACEFILE:tr1:/var/log/ser2net/p-Y-M-D-H:i:s.U
> 6271:telnet:0:/dev/ttyUSB0:19200 8DATABITS NONE 1STOPBIT banner tr=tr1 timestamp
> ```

That would be:
```
%YAML 1.1
---

define: &banner CONSOLE LAB Terminal Server TCP port \p device \d serial parms \s\r\n

define: &tr1 /var/log/ser2net/\p-\Y-\M-\D-\H:\i:\B.\U

connection: &con1
  accepter: telnet,tcp,6271
  connector: serialdev,/dev/ttyUSB0,19200n81
  options:
    banner: *banner
    trace-read: *tr1
    trace-read-timestamp: true
```

Which is more wordy, but a lot easier to read.

> 
> The config above was created a few years ago and can be found [here.](https://community.home-assistant.io/t/anyone-using-russound-rnet-component-i-could-use-a-walkthrough/7211/14) As I'm unfamiliar with the project and how the new .yaml config works, It would be great help if this was explained. How would I convert this to the .yaml format that the ser2net requires so I can get this running as intended. 
> 
> Thanks for the help!

You are welcome.  Could you post this to that forum for me?  That way
others can benefit more directly.

-corey

**Comment by Ay1tsMe** [comment]
Thank you for the quick reply!

I will test this out within the coming days. Just waiting to get the hardware in order to connect the device to my system. 

Before I post to the forum, I just wanna make sure that everything still works correctly. I'll let you know if I have any troubles before I close this issue. 

Thanks again!

**Comment by cminyard** [comment]
On Wed, Nov 15, 2023 at 07:57:41AM -0800, Adam Wyatt wrote:
> Thank you for the quick reply!
> 
> I will test this out within the coming days. Just waiting to get the hardware in order to connect the device to my system. 
> 
> Before I post to the forum, I just wanna make sure that everything still works correctly. I'll let you know if I have any troubles before I close this issue. 

Ok, thanks.

The tracefile stuff, BTW, creates a file for each connection that traces
all data read on the connection.  If you don't need that, you can remove
the tracefile things.

-corey

**Comment by Ay1tsMe** [comment]
Wasn't able to get ser2net working for my use case. I believe it's something to do with either user error on my part or the Home Assistant Russound RNET integration. I ended up using [pyserial](https://github.com/pyserial/pyserial/blob/master/examples/tcp_serial_redirect.py) instead and that worked for me.

I think the configuration you provided was correct, but I just kept getting this error everytime it would try to connect to ser2net:
```
2023/11/22 12:05:48 OPEN (ipv6,::ffff:10.1.1.173,42172)
2023/11/22 12:05:48 CLOSE port (dev read error)
2023/11/22 12:05:48 CLOSE netcon (port closing)
```

It's not so much a big deal as I got it working with pyserial, but I would like to know why the integration wasn't able to connect to my Russound controller.

**Comment by cminyard** [comment]
On Tue, Nov 21, 2023 at 08:47:05PM -0800, Adam Wyatt wrote:
> Wasn't able to get ser2net working for my use case. I believe it's something to do with either user error on my part or the Home Assistant Russound RNET integration. I ended up using [pyserial](https://github.com/pyserial/pyserial/blob/master/examples/tcp_serial_redirect.py) instead and that worked for me.
> 
> I think the configuration you provided was correct, but I just kept getting this error everytime it would try to connect to ser2net:
> ```
> 2023/11/22 12:05:48 OPEN (ipv6,::ffff:10.1.1.173,42172)
> 2023/11/22 12:05:48 CLOSE port (dev read error)
> 2023/11/22 12:05:48 CLOSE netcon (port closing)
> ```
> 
> It's not so much a big deal as I got it working with pyserial, but I would like to know why the integration wasn't able to connect to my Russound controller.

I'm not sure.  What you see above generally means that the connector
side is not working.  No logs out of ser2net?  Try running it in the
foreground with the -d option.

-corey

**Comment by Ay1tsMe** [comment]
Okay, I ran ser2net with the -d option and this is the error I get in the terminal when the home assistant tries to establish a connection:

```
ser2net[2565]: dev read error for device on port con1: Remote end closed connection
```
In the home assistant logs, there's a bunch of errors when trying to connect to the host, so either ser2net isn't connecting to the russound properly and thats why the integration isn't able to execute the code, or the integration is designed to work with pyserial but I doubt that considering other users got it working with ser2net.

Here is some of the home assistant logs if that helps:
```
2023-11-22 11:57:51.825 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.bed_1 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/russound/russound.py", line 165, in get_zone_info
    self.send_data(send_msg)
  File "/usr/local/lib/python3.11/site-packages/russound/russound.py", line 245, in send_data
    self.sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/russound_rnet/media_player.py", line 100, in update
    ret = self._russ.get_zone_info(self._controller_id, self._zone_id, 4)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/russound/russound.py", line 184, in get_zone_info
    return return_value
           ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'return_value' where it is not associated with a value
2023-11-22 11:58:01.826 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.bed_1 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/russound/russound.py", line 165, in get_zone_info
    self.send_data(send_msg)
  File "/usr/local/lib/python3.11/site-packages/russound/russound.py", line 245, in send_data
    self.sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/russound_rnet/media_player.py", line 100, in update
    ret = self._russ.get_zone_info(self._controller_id, self._zone_id, 4)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/russound/russound.py", line 184, in get_zone_info
    return return_value
           ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'return_value' where it is not associated with a value
```

**Comment by cminyard** [comment]
On Wed, Nov 22, 2023 at 06:18:24PM -0800, Adam Wyatt wrote:
> Okay, I ran ser2net with the -d option and this is the error I get in the terminal when the home assistant tries to establish a connection:
> 
> ```
> ser2net[2565]: dev read error for device on port con1: Remote end closed connection
> ```

Try adding ",local" after the baud rate, parity, etc.  That ignores the
modem control lines.  I'm not sure why it worked before, though.

Sometime I wonder if that should have been the default.

-corey

**Comment by cminyard** [comment]
I haven't seen anything on this, I assume you are ok.  Closing, please re-open if you still have an issue.
