### ISSUE TITLE
Pre-connect signals

### ISSUE THREAD

**Issue by tuctboh** [cminyard/ser2net#109]
Machine : Raspberry Pi 4 1.5
OS : Debian 12
Ser2Net version : 4.3.11
Port : /dev/ttyUSB0
Serial Adapter : https://www.amazon.com/dp/B0C2853BB1
lsusb : Bus 001 Device 003: ID 067b:23a3 Prolific Technology, Inc. ATEN Serial Bridge
YAML:  
connection: &con0096
    accepter: telnet(rfc2217),tcp,2000
    enable: on
    options:
      banner: *banner
      kickolduser: false
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              9600n81,local
Connections: Vintage Computer - Serial DB25 - Null Modem - Db25<>DB9 - Dongle - Raspberry Pi

So I'm trying to connect my Raspberry Pi to a Vintage piece of equipment that's running effectively a BBS . I'm trying to replace the modem with ser2net. I run into an issue though.

When the RPi is sitting there the BBS is waiting, the status of port 232 on the Vintage Computer (TRS-80 Model I) is 255 while 233 is 111- To decode that is -

PORT E8H (232) 	Master Reset/MODEM Status Register
Any output to this port resets the Controller.
On input: 	Bit 4 -- Ring Indicator
Bit 5 -- Carrier Detect
Bit 6 -- Data Set Ready
Bit 7 -- Clear To Send

PORT E9H (233) 	Config. DIP switches/Baud rate select
On input: 	Bits 0-2 Baud rate from 50 to 1200 (5=300; 7=1200)
Bit 3 -- 0=Parity On; 1=Parity Off
Bit 4 -- 0=1 Stop Bit; 1=2 Stop Bits
Bit 5-6 Word length (00=5, 01=6, 10=7, 11=8)
Bit 7 -- 0=Parity Odd; 1=Parity Even
On output: 	Bits 0-3 Receive Baud Rate (50-19200)
Bits 4-7 Transmit Baud Rate (50-19200) 

When I telnet to port 2000, 232 goes to 31, and 233 stays at 111.

The problem is that 232 being set to 255 is considered an RS-232 error and it won't let me go farther. I honestly don't remember serial settings so I'm not sure what to expect, but I would have at least thought that bit 0-3 would be 0 at all times. Bit 4 would only be on maybe during the beginning of the TCP 3-way handshake in ser2net. Bit 5 off normally, and on once the 3 way handshake completes. Bit 6+7 probably on all the time.

Is this something that ser2net can support or set before the connection?

Thanks, Tuc

**Comment by cminyard** [comment]
On Wed, Nov 15, 2023 at 07:38:19AM -0800, tuctboh wrote:
> Machine : Raspberry Pi 4 1.5
> OS : Debian 12
> Ser2Net version : 4.3.11
> Port : /dev/ttyUSB0
> Serial Adapter : https://www.amazon.com/dp/B0C2853BB1
> lsusb : Bus 001 Device 003: ID 067b:23a3 Prolific Technology, Inc. ATEN Serial Bridge
> YAML:  
> connection: &con0096
>     accepter: telnet(rfc2217),tcp,2000
>     enable: on
>     options:
>       banner: *banner
>       kickolduser: false
>       telnet-brk-on-sync: true
>     connector: serialdev,
>               /dev/ttyUSB0,
>               9600n81,local
> Connections: Vintage Computer - Serial DB25 - Null Modem - Db25<>DB9 - Dongle - Raspberry Pi
> 
> 
> So I'm trying to connect my Raspberry Pi to a Vintage piece of equipment that's running effectively a BBS . I'm trying to replace the modem with ser2net. I run into an issue though.
> 
> When the RPi is sitting there the BBS is waiting, the status of port 232 on the Vintage Computer (TRS-80 Model I) is 255 while 233 is 111- To decode that is -

Wow, that's some old equipment :-).  I remember when those came out.

> 
> PORT E8H (232) 	Master Reset/MODEM Status Register
> Any output to this port resets the Controller.
> On input: 	Bit 4 -- Ring Indicator
> Bit 5 -- Carrier Detect
> Bit 6 -- Data Set Ready
> Bit 7 -- Clear To Send

I don't completely understand all you are saying here, but you may have
an easy solution.  The "serialdev" gensio you are using can change the
DTR (and RTS) lines at connection.  You can can add "dtr=on" to the end
of your connector to enable DTR when you connect.  Assuming your null
modem connector handles these signals properly, that should raise DCD
(Carrier Detect) and DSR (Data Set Ready) on your system.

You may also need to enable RTS/CTS flow control, so that would be
adding "rtscts=true".  I don't think normal hardware has any way to
enable RI (Ring Indicator), you would have to do some fancy hardware to
manage that.  It's probably not needed, though.

So you would end up with:

     connector: serialdev,
               /dev/ttyUSB0,
               9600n81,local,dtr=on,rtscts=true

If you remove the "local" line, if the BBS deasserts it's DTR line it
will close the ser2net connection.  Not sure if that is desirable.

Unfortunately, the documentation for all this is part of the gensio
library, which was split out from ser2net a while ago.  If gensio is
installed on your system, you can do "man 5 gensio" and search for
"serialdev" to see all the available options.

-corey

> 
> PORT E9H (233) 	Config. DIP switches/Baud rate select
> On input: 	Bits 0-2 Baud rate from 50 to 1200 (5=300; 7=1200)
> Bit 3 -- 0=Parity On; 1=Parity Off
> Bit 4 -- 0=1 Stop Bit; 1=2 Stop Bits
> Bit 5-6 Word length (00=5, 01=6, 10=7, 11=8)
> Bit 7 -- 0=Parity Odd; 1=Parity Even
> On output: 	Bits 0-3 Receive Baud Rate (50-19200)
> Bits 4-7 Transmit Baud Rate (50-19200) 
> 
> When I telnet to port 2000, 232 goes to 31, and 233 stays at 111.
> 
> The problem is that 232 being set to 255 is considered an RS-232 error and it won't let me go farther. I honestly don't remember serial settings so I'm not sure what to expect, but I would have at least thought that bit 0-3 would be 0 at all times. Bit 4 would only be on maybe during the beginning of the TCP 3-way handshake in ser2net. Bit 5 off normally, and on once the 3 way handshake completes. Bit 6+7 probably on all the time.
> 
> Is this something that ser2net can support or set before the connection?
> 
> Thanks, Tuc

**Comment by tuctboh** [comment]
Thanks, but no changes. I need to change the signals while ser2net is waiting for a connection. Right now the Model I is seeing all bits as 1 on PORT E8H (232) . It thinks that's an RS-232 error and won't let things go any further.

For giggles, I changed dtr off and rtscts to false and tried again. Still getting 255. It isn't until I telnet to 2000 does it then go to 127. So its almost like its not setting them until the connection is made, not before.

I'll see if I can load gensio (I did want to try to use it so I could do 1 connector to the USB, and 2 acceptors (One telnet and one SSH) but I just got lost. :-/

**Comment by tuctboh** [comment]
Tried everything, and no matter what the "pre-call"  PORT E8H (232) is always showing 255, which ends up causing the system to go into the tight loop constantly checking for it to change.

Is there a way to have it activate the connector options on startup?
Tnx
Tuc

**Comment by tuctboh** [comment]
Sorry if I'm spamming. I just got via Amazon an RS-232 breakout box.

I plugged it on the DB9/Dongle side. At every setting in ser2net.yaml before connection there was only ever DCD and DSR on. No matter what I twiddled, this never changed.

**Comment by cminyard** [comment]
On Wed, Nov 15, 2023 at 09:58:12AM -0800, tuctboh wrote:
>   Sorry if I'm spamming. I just got via Amazon an RS-232 breakout box.
> 
> I plugged it on the DB9/Dongle side. At every setting in ser2net.yaml before connection there was only ever DCD and DSR on. No matter what I twiddled, this never changed.

Try adding "hangup-when-done=true" as another serial option.  Then
connect, disconnect, and reconnect.

**Comment by cminyard** [comment]
On Wed, Nov 15, 2023 at 01:44:30PM -0600, Corey Minyard wrote:
> On Wed, Nov 15, 2023 at 09:58:12AM -0800, tuctboh wrote:
> >   Sorry if I'm spamming. I just got via Amazon an RS-232 breakout box.
> > 
> > I plugged it on the DB9/Dongle side. At every setting in ser2net.yaml before connection there was only ever DCD and DSR on. No matter what I twiddled, this never changed.
> 
> Try adding "hangup-when-done=true" as another serial option.  Then
> connect, disconnect, and reconnect.

Actually, that's not going to work.  Ironically enough, I was working on
a related issue just now.  ser2net would set HUPCL (hangup on close)
in the current termios, but it would restore the termios on close and if
HUPCL wasn't set there it wouldn't work.

What you can do is:
  stty </dev/tttUSB0 hupcl

And then connect, disconnect, and reconnect.

**Comment by tuctboh** [comment]
Didn't seem to do anything.

255/111 before stty
255/111 after stty
31/111 when connected
255/111 when disconnected
31/111 when connected

I realize its bad form, but I stumbled on this - https://github.com/pyserial/pyserial/blob/master/examples/tcp_serial_redirect.py

If I stop ser2net (still 255/111), and run -

python3 tcp_serial_redirect.py --bytesize 8 --parity N --stopbits 1 -P 2000 /dev/ttyUSB0 9600

I have DTR+DSR go high on my breakout box, and the machine sees 31/111, which is fine waiting for a session. 

If I connect, though, the machine still sees 31/111, which may or may not be an issue.

If I start a modem program, I can type from the machine to the Raspberry Pi, but not the other way. :-/ This is sorta an issue I've seen otherwise with some programs I tried.

**Comment by tuctboh** [comment]
Hi,

I thought maybe it was a chip issue, so I moved over to a FTDI based chip and tried again. Same results. :-/ 

Any thoughts on what to try next? I've actually bought an old 56K modem and waiting for it to see what it SHOULD be seeing/looking for.

Tnx, Tuc

**Comment by tuctboh** [comment]
The 56K modem showed up. Interestingly, plugging it in without even being turned on it went from 255->14. When I finally turned it on it went to 63.
Tnx, Tuc

**Comment by tuctboh** [comment]
Closing, no answer.
