### ISSUE TITLE
win7 x64 no libgensio-6.dll

### ISSUE THREAD

**Issue by whoim2** [cminyard/ser2net#111]
> I installed gensio (https://github.com/cminyard/gensio), but it didn't help. The search for this file is also unsuccessful. Ser2net won't start (no libgensio-6.dll)... help?

sorry, i copied all files from /gensio/bin to ser2net folder, dll found now. I have another problem:
_procedure entry point ClosePseudoConsole not found in DLL KERNER32.dll_

**Comment by cminyard** [comment]
On Tue, Dec 05, 2023 at 11:27:46PM -0800, whoim2 wrote:
> I installed gensio (https://github.com/cminyard/gensio), but it didn't help. The search for this file is also unsuccessful. Ser2net won't start (no libgensio-6.dll)... help?

I'm not sure this will work on Windows 7, that's old and unsupported,
I think I used things that were not available there, and I have no way
to test it.

But it may work.  Not sure.  Is the Gensio directory in your PATH?  It
should be added automatically by the Gensio install, but maybe that
doesn't work on Windows 7?  If it's in the path it should be loadable by
Windows.

**Comment by whoim2** [comment]
Im copied all gensio files to ser2net/bin. Im find another way for my task, socat :)
