### ISSUE TITLE
ser2net3.5 Enable client baud rate self negotiation function

### ISSUE THREAD

**Issue by TelDragon** [cminyard/ser2net#112]
Dear author, hello. I have been running ser2net3.5 steadily for several years.

Currently, I am running according to standard configuration files. During this period, my two or three serial devices occupied a lot of my ports, ranging from a baud rate of 300 to 115200.

I remember when compiling ser2net, there was an option to enable the client's automatic baud rate negotiation function to comply with Cisco standards.

But I can't find it, nor can I find the relevant documents. Is it because my memory is confused?

**Comment by cminyard** [comment]
On Mon, Dec 11, 2023 at 08:44:38PM -0800, cloud-dragon wrote:
> Sorry, I misunderstood. Maybe it's two ways,
> One is that RFCC2217 itself has this function.
> The other one is from Sisco iOS

Yes, it works with both automatically now, and detects which is being
used.  So no option is required any more.

-corey

**Comment by TelDragon** [comment]
> On Mon, Dec 11, 2023 at 08:44:38PM -0800, cloud-dragon wrote: Sorry, I misunderstood. Maybe it's two ways, One is that RFCC2217 itself has this function. The other one is from Sisco iOS
> Yes, it works with both automatically now, and detects which is being used. So no option is required any more.
> […](#)
> -corey

Sorry, I don't quite understand the - core parameter?

I didn't find it in the help document either

How is it used?

**Comment by cminyard** [comment]
On Tue, Dec 12, 2023 at 06:54:20AM -0800, cloud-dragon wrote:
> > On Mon, Dec 11, 2023 at 08:44:38PM -0800, cloud-dragon wrote: Sorry, I misunderstood. Maybe it's two ways, One is that RFCC2217 itself has this function. The other one is from Sisco iOS
> > Yes, it works with both automatically now, and detects which is being used. So no option is required any more.
> > […](#)
> > -corey
> 
> Sorry, I don't quite understand the - core parameter?

There's no parameter.  It's possible to determine which is being used
from the protocol data, so the code automatically figures it out.  You
don't have to do anything.

If you add the remctl option to the configuration line, it will enable
RFC2217 and it will use either RFC2217 or Cisco baud rates, depending on
what it gets from the other end.

-corey

**Comment by TelDragon** [comment]
> On Tue, Dec 12, 2023 at 06:54:20AM -0800, cloud-dragon wrote: > On Mon, Dec 11, 2023 at 08:44:38PM -0800, cloud-dragon wrote: Sorry, I misunderstood. Maybe it's two ways, One is that RFCC2217 itself has this function. The other one is from Sisco iOS > Yes, it works with both automatically now, and detects which is being used. So no option is required any more. > […](#) > -corey Sorry, I don't quite understand the - core parameter?
> There's no parameter. It's possible to determine which is being used from the protocol data, so the code automatically figures it out. You don't have to do anything. If you add the remctl option to the configuration line, it will enable RFC2217 and it will use either RFC2217 or Cisco baud rates, depending on what it gets from the other end.
> […](#)
> -corey
> I didn't find it in the help document either How is it used? -- Reply to this email directly or view it on GitHub: [#112 (comment)](https://github.com/cminyard/ser2net/issues/112#issuecomment-1852194377) You are receiving this because you commented. Message ID: ***@***.***>

thank you. You are very clear. I understand

**Comment by TelDragon** [comment]
If so. If the cmd command window that comes with Windows does not have this feature, I found out that someone had previously used the Realtermsoftware for testing.

It can not only input the IP address and port number of the counterpart to connect, but also select the corresponding baud rate.



But I tried and still failed.

**Comment by cminyard** [comment]
I think you are saying that your windows software could select the IP address and port, but not the baud rate.  The client you are using on windows has to support rfc2216, too.  I don't know of any that do.  Well, there's gensiot as part of the gensio library, but it's a console application and is not terribly user friendly.

Looking at realterm, I see no mention of rfc2217.  So it may not do this.

**Comment by cminyard** [comment]
I assume this resolved.
