### ISSUE TITLE
ser2net not working on Windows 11

### ISSUE THREAD

**Issue by RichardRo** [cminyard/ser2net#113]
Hi,
Tried ser2net on Windows 11 PC, but couldn't get it work.
Want to share a Serial port in Windows PC to network, the Serial port is a Serial to USB device.
Used the example yaml configuration:
`%YAML 1.1
---

define: &banner Connected to port \N(\d)\r\n

default:
      name: local
      value: true
      class: serialdev

default:
      name: mdns
      value: true

default:
      name: mdns-sysattrs
      value: true

connection: &my-console
      accepter: telnet(rfc2217),mux,tcp,3001
      connector: serialdev,/dev/ttyUSB0,115200N81
      options:
              banner: *banner`

Tried to "telnet 127.0.0.1 3001", got "err: my-console: Error accepting a gensio: Protocol error" error.
Maybe "connector: serialdev,/dev/ttyUSB0,115200N81" line is incorrect? 
Thanks.

**Comment by cminyard** [comment]
On Dec 28, 2023 21:17, RichardRo ***@***.***> wrote:
Hi,
Tried ser2net on Windows 11 PC, but couldn't get it work.
Want to share a Serial port in Windows PC to network, the Serial port is a Serial to USB device.
Used the example yaml configuration:
`%YAML 1.1
define: &banner Connected to port \N(\d)\r\n
default:
name: local
value: true
class: serialdev
default:
name: mdns
value: true
default:
name: mdns-sysattrs
value: true
connection: &my-console
accepter: telnet(rfc2217),mux,tcp,3001Take out the mux here.  That's a multiplexing protocol layer, telnet won't have that.-corey
connector: serialdev,/dev/ttyUSB0,115200N81
options:
banner: *banner`
Tried to "telnet 127.0.0.1 3001", got "err: my-console: Error accepting a gensio: Protocol error" error.
Maybe "connector: serialdev,/dev/ttyUSB0,115200N81" line is incorrect?
Thanks.

**Comment by RichardRo** [comment]
Thanks for the quick reply!
After removing "mux", I got error:
`Device open failure: OS error, see logs

Connection to host lost.`
Does it mean opening the serial device failed?
The serial port is "USB Serial Port (COM5)" in device manager.
Tried to modify /dev/ttyUSB0 to /dev/ttyUSB4, /dev/ttyUSB5, but got the same error.

**Comment by RichardRo** [comment]
Just figured it out, "/dev/ttyUSB0" should be "\\\\.\\COM5". It works now.
Thanks so much!
Happy new year!

**Comment by cminyard** [comment]
On Dec 29, 2023 1:45 AM, RichardRo ***@***.***> wrote:
Thanks for the quick reply!
After removing "mux", I got error:
`Device open failure: OS error, see logs
Connection to host lost.`
Does it mean opening the serial device failed?
The serial port is "USB Serial Port (COM5)" in device manager.
Tried to modify /dev/ttyUSB0 to /dev/ttyUSB4, /dev/ttyUSB5, but got the same error.Yes, on Windows you use COM1, COM2, etc, not /dev/ttyX.-corey
