### ISSUE TITLE
Docs out of sync with option `-C`'s changed meaning

### ISSUE THREAD

**Issue by chder** [cminyard/ser2net#114]
`config_line` doesn't work with `-C` anymore.

Docs:
https://github.com/cminyard/ser2net/blob/eef09816204897bcafeed4cf8fc9e7706f5328e8/ser2net.c#L234-L238

https://github.com/cminyard/ser2net/blob/eef09816204897bcafeed4cf8fc9e7706f5328e8/ser2net.8#L8

Looks like that was replaced with:
https://github.com/cminyard/ser2net/blame/eef09816204897bcafeed4cf8fc9e7706f5328e8/ser2net.c#L862
And that expects a config directory rather than a config line.

**Comment by cminyard** [comment]
On Sun, Jan 07, 2024 at 10:15:31AM -0800, Chris Derichs wrote:
> `config_line` doesn't work with `-C` anymore.

Thanks, I fixed it.  -Y is the one for yaml config lines now.

-corey
