### ISSUE TITLE
Programmatically create ser2net.yaml files - how to add alias?

### ISSUE THREAD

**Issue by Nippey** [cminyard/ser2net#115]
Hi,
I am using a python server that can dynamically create new ser2net configurations for user-requested endpoint.
Until now, I am manually writing the YAML file line by line.
I would like to just prepare the DICT and hand-over to a package like PyYAML.

But I have a problem with the connection naming `connection: &name`.
This kind of anchor is difficult to create by converting DICT/JSON to YAML.
Could it be possible to alternatively define the name of the connection by a `name` tag?

Best Regards
Nippey

**Comment by Nippey** [comment]
Also, I just found that my YAML parsers are unhappy with multiple `connection:` placed as level 1 node without being a list.
Wouldn't it make more sense to have multiple connections as list to be placed below `connections:` ?

**Comment by cminyard** [comment]
On Wed, Jan 31, 2024 at 04:05:53AM -0800, Nippey wrote:
> Hi,
> I am using a python server that can dynamically create new ser2net configurations for user-requested endpoint.
> Until now, I am manually writing the YAML file line by line.
> I would like to just prepare the DICT and hand-over to a package like PyYAML.
> 
> But I have a problem with the connection naming `connection: &name`.
> This kind of anchor is difficult to create by converting DICT/JSON to YAML.
> Could it be possible to alternatively define the name of the connection by a `name` tag?

Yeah, that was a mistake on my part, but I recently added a new way to
do YAML.  If you move to version 4.6.0, it takes a different YAML
configuration format that is standard (and the old one works, too).
You should be able to generate that from standard YAML parsers.

Look in the ser2net.yaml.5 man page for "version 2" for documentation.
You can also look in the ser2net.yaml example configuration file.

Thanks,

-corey

**Comment by Nippey** [comment]
Thank you for the quick reply!
I am on Debian 12 with 4.3.11, will have a look into it in the next maintenance :)

BR!

**Comment by cminyard** [comment]
On Wed, Jan 31, 2024 at 04:52:21AM -0800, Nippey wrote:
> Thank you for the quick reply!
> I am on Debian 12 with 4.3.11, will have a look into it in the next maintenance :)
> 

You can, of course, just compile it yourself.  Install libyaml-dev and
libgensio-dev and it should just compile and work.
