### ISSUE TITLE
rs485 configuration

### ISSUE THREAD

**Issue by jonasfoyth** [cminyard/ser2net#117]
Hello!

I'm testing the .yaml configuration to use tcp over serial to read an rs485 device, but without success. To do this, I need to use rts_on_send from [gensio](https://man.archlinux.org/man/extra/gensio/gensio.5.en#:~:text=values%20can%20be%3A%20%22-,rts_on_send,-%22%20%2D%20RTS%20set%20when) (using ser2net 4.6.1 and gensio 2.8.3). I try with:

```bash
connection: &con01
    acceptor: tcp,8500
    connector: serialdev,/dev/ttyS4,57600n81,local
    options:
        kickolduser: true
```

```bash
connection: &con01
    acceptor: tcp,8500
    connector: serialdev,/dev/ttyS4,57600n81,local,rts=on,rs485=0:0:rts_on_send
    options:
        kickolduser: true
```

```bash
connection: &con01
    acceptor: tcp,8500
    connector: serialdev,/dev/ttyS4,57600n81,local,rs485=0:0:rts_on_send
    options:
        kickolduser: true
```

```bash
connection: &con01
    acceptor: tcp,8500
    connector: serialdev,/dev/ttyS4,57600n81,local,rs485=1000:1000:rts_on_send
    options:
        kickolduser: true
```

```bash
connection: &con01
    acceptor: tcp,8500
    connector: serialdev,/dev/ttyS4,57600n81,local,rts=off,dtr=off
    options:
        kickolduser: true
```

Direct reading from the device terminal ([mbpool](https://github.com/epsilonrt/mbpoll) with the -F option) is working as expected. To test the command, i'm sending the frame that the device is waiting with netcat.

**Comment by cminyard** [comment]
On Fri, Feb 09, 2024 at 02:55:02AM -0800, jonasfoyth wrote:
> Hello!
> 
> I'm testing the Yaml configuration to use tcp over serial to read an rs485 device, but without success. To do this, I need to use rts_on_send from [gensio](https://man.archlinux.org/man/extra/gensio/gensio.5.en#:~:text=values%20can%20be%3A%20%22-,rts_on_send,-%22%20%2D%20RTS%20set%20when) (using ser2net 4.6.1 and gensio 2.8.3). I try with:
> 
> 
> ```bash
> connection: &con01
>     acceptor: tcp,8500
>     connector: serialdev,/dev/ttyS4,57600n81,local
>     options:
>         kickolduser: true
> ```
> 
> ```bash
> connection: &con01
>     acceptor: tcp,8500
>     connector: serialdev,/dev/ttyS4,57600n81,local,rts=on,rs485=0:0:rts_on_send
>     options:
>         kickolduser: true
> ```
> 
> ```bash
> connection: &con01
>     acceptor: tcp,8500
>     connector: serialdev,/dev/ttyS4,57600n81,local,rs485=0:0:rts_on_send
>     options:
>         kickolduser: true
> ```

This would be the most correct one, I think.  I looked at mbpoll and
libmodbus, because I don't know very much about rs485; other people have
helped me with this.

The default parity for mbpoll is even, not none.  That could be one
thing.  The other thing is that you need to get the delays (the 0:0
thing) correct, and I don't know what the values should be.  libmodbus
appears to take whatever the default is in the kernel.  From looking at
the kernel, it looks like 1:1 would be the most common value, and
100:100 is the maximum value.

libmodbus does appear to set "local", so I think that's correct.

What are the values you pass to mbpoll?  The default speed is 9600, for
instance.

-corey

**Comment by jonasfoyth** [comment]
Thanks for the answer,

The mbpoll command working: ` mbpoll -m rtu -b 57600 -F -a 1 -c 2 -P none -t 4:hex /dev/ttyS4 -1 -r 293 -v `

But perhaps the problem are in how the control is implemented by the kernel i am using.

I will carry out some more tests and get back to you.

**Comment by cminyard** [comment]
On Mon, Feb 12, 2024 at 03:28:24AM -0800, jonasfoyth wrote:
> Thanks for the answer,
> 
> The mbpoll command working: ` mbpoll -m rtu -b 57600 -F -a 1 -c 2 -P none -t 4:hex /dev/ttyS4 -1 -r 293 -v `
> 
> But perhaps the problem are in how the control is implemented by the kernel i am using.
> 
> I will carry out some more tests and get back to you.

Reading a little more, mbpoll appears to be implementing the modbus
protocol on top of rs485, which I know nothing about.  There's not a
modbus protocol layer in gensio.  rs485 is only the physical link for
transporting packets, mbpoll is sending messages to something else on
the bus and getting responses.

**Comment by cminyard** [comment]
I assume we have closure on this, though it's probably not what you wanted :-(.
