### ISSUE TITLE
read error for port X: Operation timed out

### ISSUE THREAD

**Issue by shmuelhazan** [cminyard/ser2net#118]
Hi, 

First of all, thank you very much for your work on ser2net. It helps us a lot every day. 

We noticed that in some cases, when the network is under load, we will stop receiving information from ser2net until we'll perform `systemctl restart ser2net`.

From the code (https://github.com/cminyard/ser2net/blob/6e8439ad1aa422529c5ca1ca95c7495eb399715f/dataxfer.c#L527), it looks like ser2net would disable network ports if it notices any error (correct me if I am wrong). 

What is the reason for this behavior? Maybe it would be better to just ignore (and log) IO errors?

**Comment by cminyard** [comment]
On Wed, Feb 14, 2024 at 02:58:52AM -0800, Shmuel Hazan wrote:
> Hi, 
> 
> First of all, thank you very much for your work on ser2net. It helps us a lot every day. 

Thank you.

> 
> We noticed that in some cases, when the network is under load, we will stop receiving information from ser2net until we'll perform `systemctl restart ser2net`.
> 
> From the code (https://github.com/cminyard/ser2net/blob/6e8439ad1aa422529c5ca1ca95c7495eb399715f/dataxfer.c#L527), it looks like ser2net would disable network ports if it notices any error (correct me if I am wrong). 

It will shut down the connection.  It will not disable the port, a new
connection should work.

> 
> What is the reason for this behavior? Maybe it would be better to just ignore (and log) IO errors?

In general, once you get an error from the serial port, it will stop
working and just generate errors.  So if you just ignore the error, you
would basically go into an infinite loop handling errors.

What is the error?  What version of ser2net and gensio are you running?

**Comment by shmuelhazan** [comment]
@cminyard Thanks for the fast response. I checked again, and looks like the error I mentioned ("read error for port") is unrelated to the actual issue (serial get stuck until `systemctl restart ser2net`). And the actual issue happens with no error in the log. I will try to reproduce it again and then backtrace using gdb to see why ser2net is getting stuck. 

For now, I will close the issue. 

For reference, my version is:
* ser2net: 4.3.3
* gensio: 2.2.4

**Comment by cminyard** [comment]
On Wed, Feb 14, 2024 at 04:54:24AM -0800, Shmuel Hazan wrote:
> @cminyard Thanks for the fast response. I checked again, and looks like the error I mentioned ("read error for port") is unrelated to the actual issue (serial get stuck until `systemctl restart ser2net`). And the actual issue happens with no error in the log. I will try to reproduce it again and then backtrace using gdb to see why ser2net is getting stuck. 
> 
> For now, I will close the issue. 
> 
> For reference, my version is:
> * ser2net: 4.3.3
> * gensio: 2.2.4

There have been issues fixed in both gensio and ser2net dealing with
lockups in some situations.  I'd bet that upgrading will solve your
issues.  Those versions are pretty old.
