### ISSUE TITLE
autostart ser2net

### ISSUE THREAD

**Issue by denissyslo** [cminyard/ser2net#119]
Hello, my friend!
i need ser2net for ttyS1 -> TCP 3002 on orange pi zero.
I install ser2net:  `sudo apt-get install ser2net`
then:
`sudo useradd -r -M -d /usr/share/ser2net -G dialout ser2net
sudo mkdir /usr/share/ser2net
sudo chown ser2net.ser2net /usr/share/ser2net`
I check work of program:
`ser2net -C "3002:raw:0:/dev/ttyS1:115200 NONE 1STOPBIT 8DATABITS -XONXOFF -LOCAL -RTSCTS"`
After this string my device vork great! all working (php to ttys1)
I need startup `ser2net -C "3002:raw:0:/dev/ttyS1:115200 NONE 1STOPBIT 8DATABITS -XONXOFF -LOCAL -RTSCTS"` every starting orange pi.
For this i write to rc.local:
`stty -F /dev/ttyS1 cs8 115200 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts -hupcl
ser2net -C "3002:raw:0:/dev/ttyS1:115200 NONE 1STOPBIT 8DATABITS -XONXOFF -LOCAL -RTSCTS"
exit 0`

after restart my device (orangepi +arduino) not operate. If i put: `root@orangepizero:~# ser2net -C "3002:raw:0:/dev/ttyS1:115200 NONE 1STOPBIT 8DATABITS -XONXOFF -LOCAL -RTSCTS"` - all begin operate.

my config file in etc/ser2net.yaml:

%YAML 1.1
---

define: &banner \r\n ser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &con1192
    accepter: tcp,3002
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyS1,
              115200n81,local

How i can use ser2net in (-C mode) for auto start or how i can tune ser2net for correct work?

**Comment by denissyslo** [comment]
I tune ser2net.yaml and ser2net work correctly, but also not work from startup.
service ser2net start automatically , but not working and have problem in config.
if i manualy restart service ser2net begin work correct.
![Безымянный](https://github.com/cminyard/ser2net/assets/161838963/a1a002f8-3cb1-4345-a5a7-a820ac873ee0)

**Comment by cminyard** [comment]
This is a much discussed issue in this forum, look at https://github.com/cminyard/ser2net/issues/96 and https://github.com/cminyard/ser2net/issues/60 for instance.

If you switch to a newer version of ser2net it retries and completely avoids this issue, but you have to build and install a new version.

**Comment by denissyslo** [comment]
Hello, my friend!
Thank you for answer.
I setup (first time) new version  4.3.4 to blank system.
I solve problem by add 5 sec delay and restart ser2net to rc/local:

#!/bin/sh -e
sleep 5
ser2net -c "/etc/ser2net.yaml"
exit 0

i don't why, but this working.

P.S. go to read 96 and 60 issue.
