### ISSUE TITLE
`ser2net` cli commands now return 1

### ISSUE THREAD

**Issue by gsalvatella** [cminyard/ser2net#121]
Issuing CLI commands such as `ser2net -v` in the latest v4.6.1 returns code 1, which breaks applications that rely on them to return successfully (0), for instance inside python `subprocess` calls.

```bash
$ ser2net -v
ser2net version 4.6.1
$ echo $?
1
```

This seems to have been introduced by https://github.com/cminyard/ser2net/commit/edf8bf45a413693cc6f2260e702427df6691995f. Looks like a critical bug.

**Comment by cminyard** [comment]
Oops.  I just pushed up a fix for this.  Sorry about that.
