### ISSUE TITLE
Suitable EditorConfig configuration

### ISSUE THREAD

**Issue by yegorich** [cminyard/ser2net#123]
[EditorConfig](https://editorconfig.org/) project helps to provide a cross-editor configuration for the following settings like line and file endings, indentation, etc.

What would be the suitable configuration for the ser2net project?

**Comment by cminyard** [comment]
On Wed, Apr 10, 2024 at 01:00:46AM -0700, Yegor Yefremov wrote:
> [EditorConfig](https://editorconfig.org/) project helps to provide a cross-editor configuration for the following settings like line and file endings, indentation, etc.
> 
> What would be the suitable configuration for the ser2net project?

That's interesting.  I don't have a strong opinion, if you want to
invent something I'd be happy to work with it.  I've been using 2
character indent, that's really about it.  It looks like you could use
[ser2net/*.yaml] for the naming.

**Comment by yegorich** [comment]
Solved via e5c3dfa43f7d4711651fdfa14088a23b71b6c4bf.
