### ISSUE TITLE
Help Converting .conf to . yaml

### ISSUE THREAD

**Issue by Quicksilver2002** [cminyard/ser2net#126]
Hi, I'm working on a project that was originally setup by someone else using the .conf. file   I'm trying to convert to .Yaml, but I'm not sure how to do some of the conversions.  Specifically, the raw:600 portion and the XONXOFF.  The conf settings, and my new yaml are listed below.  Can someone explain how I would add these in the Yaml file?  Thanks!

Original .conf. 
`BANNER:banner:\r\nSer2net \p device \d [\s] \r\nConnection will stay open for 10 min \r\n\r\n

1041:raw:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT XONXOFF banner
32010:raw:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT banner
32011:raw:600:/dev/ttyUSB0:57600 8DATABITS NONE 1STOPBIT banner
32012:raw:600:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner
`

This is how I have the .yaml

`%YAML 1.1
---
define: &banner \r\nSer2net \p device \d [\s] \r\n /r/n/r/n

connection: &con1
    accepter: tcp,1041
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              9600n81,local

connection: &con2
    accepter: tcp,9100
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              9600n81,local

connection: &con3
    accepter: tcp,32011
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              57600n81,local

connection: &con4
    accepter: tcp,32012
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              115200n81,local

`

**Comment by cminyard** [comment]
On Thu, May 16, 2024 at 11:46 AM Quicksilver2002 ***@***.***>
wrote:

> Hi, I'm working on a project that was originally setup by someone else
> using the .conf. file I'm trying to convert to .Yaml, but I'm not sure how
> to do some of the conversions. Specifically, the raw:600 portion and the
> XONXOFF. The conf settings, and my new yaml are listed below. Can someone
> explain how I would add these in the Yaml file? Thanks!
>
raw is the default if you just use "tcp".


> Original .conf.
> `BANNER:banner:\r\nSer2net \p device \d [\s] \r\nConnection will stay open
> for 10 min \r\n\r\n
>
> 1041:raw:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT XONXOFF banner
> 32010:raw:600:/dev/ttyUSB0:9600 8DATABITS NONE 1STOPBIT banner
> 32011:raw:600:/dev/ttyUSB0:57600 8DATABITS NONE 1STOPBIT banner
> 32012:raw:600:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner
> `
>
> This is how I have the .yaml
> `%YAML 1.1
>
> define: &banner \r\nSer2net \p device \d [\s] \r\n /r/n/r/n
>
> connection: &con1
>
Add:
timeout: 600
to all the connections.

> accepter: tcp,1041
> enable: on
> options:
> banner: *banner
> kickolduser: true
> telnet-brk-on-sync: true
> connector: serialdev,
> /dev/ttyUSB0,
> 9600n81,local
>
append ,xonxoff to the above line.

**Comment by Quicksilver2002** [comment]
wow! Thanks for the quick response! I appreciated the info. I will get these changes made. 

I've been reading ser2net(5) and ser2net(8), and I'm having a hard time understanding the banner and how it works. Its working how it is now, but I'm trying to understand the reasoning behind it.  I understand \r\n does a new line, but is this for the data I'm sending to it?  I was thinking it was "formatting" the data I was sending but doesn't appear to have the correct amount of carriage returns for that so maybe it's not for the data I'm sending. I'm sending 5 fields of data. The data I'm sending looks like this

<HP123-12
Test Description
076-007
2207260105
25000>

Also, the .conf has a [\s] in the banner and I'm not sure why that's in square brackets. It also says, "Connection will stay open for 10 min", I removed that line in my .yaml and it didn't see to affect anything. 

In the .conf file its 
BANNER:banner:\r\nSer2net \p device \d [\s] \r\nConnection will stay open for 10 min \r\n\r\n

Yaml file
define: &banner \r\nSer2net \p device \d [\s] \r\n \r\n\r\n

Was just curious if maybe you could help clarify this a little for me. Thanks!

**Comment by Quicksilver2002** [comment]
I really appreciate your help Thanks!

**Comment by cminyard** [comment]
This appears to be done, please re-open if you have other questions or issues.
