### ISSUE TITLE
Getting gensio_control_set undeclared error when compiling ser2net

### ISSUE THREAD

**Issue by zacchild** [cminyard/ser2net#127]
pi@pi: ser2net-4.3.11 $ make
Making all in tests
make[1]: Entering directory '/home/pi/ser2net-4.3.11/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/ser2net-4.3.11/tests'
make[1]: Entering directory '/home/pi/ser2net-4.3.11'
  CC       auth.o
auth.c: In function ‘handle_auth_begin’:
auth.c:174:32: error: ‘GENSIO_CONTROL_SET’ undeclared (first use in this function); did you mean ‘GENSIO_CONTROL_CERT’?
  174 |   err = gensio_control(net, 0, GENSIO_CONTROL_SET,
      |                                ^~~~~~~~~~~~~~~~~~
      |                                GENSIO_CONTROL_CERT
auth.c:174:32: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:553: auth.o] Error 1
make[1]: Leaving directory '/home/pi/ser2net-4.3.11'
make: *** [Makefile:675: all-recursive] Error 1
pi@pi: ser2net-4.3.11 $

**Comment by cminyard** [comment]
On Fri, May 31, 2024 at 05:28:31AM -0700, Zac Child wrote:
> ***@***.***:~/ser2net-4.3.11 $ make

You are using a really old version of ser2net with an even older version
of gensio.  I'm guessing the gensio version is before 2.3.0, which
added:

#define GENSIO_CONTROL_GET     true
#define GENSIO_CONTROL_SET     false

Can you switch to newer versions?  If not, you will need to define the
above in your code.

-corey

**Comment by zacchild** [comment]
> On Fri, May 31, 2024 at 05:28:31AM -0700, Zac Child wrote: ***@***.***:~/ser2net-4.3.11 $ make
> You are using a really old version of ser2net with an even older version of gensio. I'm guessing the gensio version is before 2.3.0, which added: #define GENSIO_CONTROL_GET true #define GENSIO_CONTROL_SET false Can you switch to newer versions? If not, you will need to define the above in your code.
> […](#)
> -corey
> Making all in tests make[1]: Entering directory '/home/pi/ser2net-4.3.11/tests' make[1]: Nothing to be done for 'all'. make[1]: Leaving directory '/home/pi/ser2net-4.3.11/tests' make[1]: Entering directory '/home/pi/ser2net-4.3.11' CC auth.o auth.c: In function ‘handle_auth_begin’: auth.c:174:32: error: ‘GENSIO_CONTROL_SET’ undeclared (first use in this function); did you mean ‘GENSIO_CONTROL_CERT’? 174 | err = gensio_control(net, 0, GENSIO_CONTROL_SET, | ^~~~~~~~~~~~~~~~~~ | GENSIO_CONTROL_CERT auth.c:174:32: note: each undeclared identifier is reported only once for each function it appears in make[1]: *** [Makefile:553: auth.o] Error 1 make[1]: Leaving directory '/home/pi/ser2net-4.3.11' make: *** [Makefile:675: all-recursive] Error 1 ***@***.***:~/ser2net-4.3.11 $ -- Reply to this email directly or view it on GitHub: #127 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

Thank you, that worked!
