### ISSUE TITLE
RTS is set to high by ser2net and not clearing after flush

### ISSUE THREAD

**Issue by naseef** [cminyard/ser2net#128]
Hi I am using ser2net to connect serial to tcp with the below configuration

```
connection: &default
  accepter: tcp,8080
  enable: on
  options:
    mdns: false
    kickolduser: true
    dev-to-net-bufsize: 1200
    net-to-dev-bufsize: 1200
    trace-both: /tmp/ser2net.log
    trace-hexdump: true
    trace-timestamp: true
  connector: serialdev,/dev/rs485,9600n81,rs485=0:0:rts_on_send
```
  
  
The serial UART port is connected to an RS485 Transceiver like this ( in half duplex mode)

![image](https://github.com/user-attachments/assets/4c7e7228-680e-436f-a083-4e48f3427ac9)

The problem is that, once a tcp connection is established, the RTS is set by ser2net  ( or may be by driver , i don't know) and not getting reset after flush and as a result any response from the serial device is not received by ser2net ( since RTS is HIGH, means DE ( Driver enable) is always on and RE ( receive enable) is off)

How can i troublehsoot this? I tried setting rts=off , enable rtscts flowcontrol etc , but no effect

For testing purpose my serial device is sending data every second to the system, the data before the tcp connection is getting received by ser2net ( see first line in the log), but after tcp is open, it is not getting any serial data

```
2024/07/29 14:07:24 OPEN (ipv6,::ffff:XXXXXXXXXXX,52172)
2024/07/29 14:07:25 term 7e 61 73 64 61 73 64 7e  |~asdasd~|
2024/07/29 14:07:25 tcp  7e a0 08 02 cf 03 93 3c  |~......<|
2024/07/29 14:07:25 tcp  d8 7e                    |.~|
2024/07/29 14:07:35 tcp  7e a0 08 02 cf 03 93 3c  |~......<|
2024/07/29 14:07:35 tcp  d8 7e                    |.~|
2024/07/29 14:07:45 tcp  7e a0 08 02 cf 03 93 3c  |~......<|
2024/07/29 14:07:45 tcp  d8 7e                    |.~|
2024/07/29 14:07:55 tcp  7e a0 08 02 cf 03 53 30  |~.....S0|
2024/07/29 14:07:55 tcp  1e 7e                    |.~|
2024/07/29 14:08:05 tcp  7e a0 08 02 cf 03 53 30  |~.....S0|
2024/07/29 14:08:05 tcp  1e 7e                    |.~|
2024/07/29 14:08:15 tcp  7e a0 08 02 cf 03 53 30  |~.....S0|
2024/07/29 14:08:15 tcp  1e 7e                    |.~|
2024/07/29 14:08:25 CLOSE netcon (network read close)
2024/07/29 14:08:25 CLOSE port (All users disconnected)
```

RTS is correctly set by the driver since i can confirm the same with minicom

**Comment by cminyard** [comment]
I am not sure I completely understand your hardware configuration.  So you have an RS485-capable device on your system hooked to an RS485 transceiver?  If so the device on your system should manage RTS based in the rs485= settings, the other RTS settings shouldn't do anything.  However, I am not sure that you can set the delay values to 0.  Can you try setting them to 1?  That's the normal default.  I'm not sure, but setting them to 0 may disable RTS.

If you are trying to hook a normal RS232 port to an RS485 transceiver, I'm not sure how that will work.

**Comment by cminyard** [comment]
Try adding ",rtscts,local" to the ser2net connector.  I'm betting it's local, as you don't have dtr/dsr wired up.

**Comment by cminyard** [comment]
The `write` function (`writev`, really) is called from gensio_unix_write().

The only other possibility is direct RTS setting with modem control, but that is ignored by the kernel on rs485.

What version of ser2net and gensio are you using?

**Comment by cminyard** [comment]
Those versions are certainly current enough.

I am a bit at a loss here.  Lets just try something basic.  Can you set the connector line to:
```
serialdev,/dev/rs485,9600n81,rts=on
```
That should drive the rts line low.  (I believe low is enabled and high is disabled for RTS.)  Don't enable rs485.

minicom by default will enable the RTS line.  If you start it up and then set rs485, it will have been enabled first.  But Linux will ignore setting the RTS line after you enable rs485.  Anyway, it will at least tell us that RTS can be driven.  You could also try your original connector line and add `rts=on` and see if that matters, but I'm guessing not.

**Comment by cminyard** [comment]
Non-blocking shouldn't matter.  I know lots of others are using RS485 on this, so it is working, but there is something unique about your setup.

I need to modify gensio to clear rs485 if it isn't set.

The following program should clear RS485, it's just a small modification of the previous program.

```
#include <stdio.h>
#include <linux/serial.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

int
main(int argc, char *argv[])
{
    struct serial_rs485 c;
    int fd = open(argv[1], O_RDWR);

    if (fd < 0) {
	perror("open");
	return 1;
    }

    if (ioctl (fd, TIOCGRS485, &c) < 0) {
	perror("ioctl");
	return 1;
    }

    printf("flags: %8.8x\n", c.flags);
    printf("delay_rts_before: %u\n", c.delay_rts_before_send);
    printf("delay_rts_after: %u\n", c.delay_rts_after_send);

    printf("Clearing RS485\n");
    c.flags = 0;
    if (ioctl (fd, TIOCSRS485, &c) < 0) {
	perror("ioctl");
	return 1;
    }
    
    return 0;
}
```

**Comment by cminyard** [comment]
I pushed up a patch to clear rs485 if it isn't set, and to save/restore the rs485 config at startup/shutdown.
