### ISSUE TITLE
ssh over serial without network connection

### ISSUE THREAD

**Issue by linzha0** [cminyard/ser2net#131]
Hi, thanks for sharing this amazing software. 
In my case, I will have two computers (pi and laptop), which are only communicated through serial. I am trying to create an ssh over the serial communication. So I can type shell commands to check the pi's conditions. 
I am wondering if ser2net  could be used for this case.  Thanks for your time.

**Comment by cminyard** [comment]
On Wed, Aug 28, 2024 at 11:42 AM linzha0 ***@***.***> wrote:

> Hi, thanks for sharing this amazing software.
> In my case, I will have two computers (pi and laptop), which are only
> communicated through serial. I am trying to create an ssh over the serial
> communication. So I can type shell commands to check the pi's conditions.
> I am wondering if ser2net could be used for this case. Thanks for your
> time.
>

I'm not sure exactly what you are trying to accomplish, but it sounds like
you want a secure login from the laptop to the pi over a serial port.

You could perhaps use ser2net to do this, but there's a better way, I
think.  ser2net is based on the gensio library, and the gensio library has
a secure shell sort of thing that's based on TLS.  You can see an example
at https://github.com/cminyard/gensio, search for "conacc" in the
README.rst.

You have to generate all the keys to do this.  The gtlssh, gtlsshd, and
gtlssh-keygen manual pages will be useful for that.  It may be tricky, feel
free to ask for help on setting this up.

-corey

**Comment by linzha0** [comment]
thanks for your quick reply. Since I just want to use the shell console of the remote computer, I found another way to use getty for the serial console. I will close the issue for now.
