### ISSUE TITLE
Corrupted response to RFC2217 break condition

### ISSUE THREAD

**Issue by ben-powell-ctct** [cminyard/ser2net#134]
Hi,

Should ser2net support sending a break condition to an RFC2217 serial port? When I try this on my setup, ser2net responds with some corrupted packets which are rejected by the client. The corrupted packets are packets 40, 42 and 44 in the attached zipped PCAP file [ser2net-telnet-break-bad-response.zip](https://github.com/user-attachments/files/17806845/ser2net-telnet-break-bad-response.zip). The behaviour is reproducible on my setup using the most recent versions of gensio (git hash ff1715f5ee3680725778782bec49f1a5a1e482ae) and ser2net (git hash 90e35f79bf811bf9b361b555f3decaea42456786) at the time of writing. I have also tested a few older versions of both gensio and ser2net, but wasn't able to find a version which didn't have this issue. 

The test code I used to reproduce the behaviour is:

```
import serial


with serial.serial_for_url("rfc2217://host:port", baudrate=38400, timeout=1) as port:
    port.send_break(0.5)
```

Thanks,

Ben

**Comment by cminyard** [comment]
On Mon, Nov 18, 2024 at 4:19 PM ben-powell-ctct
***@***.***> wrote:
>
> Hi,
>
> Should ser2net support sending a break condition to an RFC2217 serial port? When I try this on my setup, ser2net responds with some corrupted packets which are rejected by the client. The corrupted packets are packets 40, 42 and 44 in the attached zipped PCAP file ser2net-telnet-break-bad-response.zip. The behaviour is reproducible on my setup using the most recent versions of gensio (git hash ff1715f5ee3680725778782bec49f1a5a1e482ae) and ser2net (git hash 90e35f7) at the time of writing. I have also tested a few older versions of both gensio and ser2net, but wasn't able to find a version which didn't have this issue.
>
> The test code I used to reproduce the behaviour is:
>
> import serial
>
>
> with serial.serial_for_url("rfc2217://host:port", baudrate=38400, timeout=1) as port:
>     port.send_break(0.5)
>
> Thanks,
>
> Ben

Yes, ser2net supports this, and I suspect ser2net is working as it is
supposed to.  I'm guessing you are connecting to a Unix system and you
are sending a break at the login prompt.  When you do that, Unix
systems will re-send the login message at a different speed, cycling
through a set of baud rates as you send breaks.  If I'm right, the
"corrupted packets" are data sent at the wrong speed.

You can verify this with the "trace" gensio.  You can stick it in
various places in a gensio stack (like between telnet and serialdev
for this problem, or on top of telnet, or on top of tcp) to see the
data flowing in one or both directions.

-corey

**Comment by ben-powell-ctct** [comment]
Hi Corey,

Thanks for the quick response. Sorry, my description of the issue wasn't that great. The corrupted messages are ser2net's responses to the break request command, not the serial device's response to the break condition itself. I have included a screenshot of one of the corrupted packets from the PCAP file I attached above. The client has IP address 192.168.1.78, and the server has the IP address 192.168.1.25.

![image](https://github.com/user-attachments/assets/360233c2-6f3a-43e8-af55-67966490b7e6)

I'll try the trace gensio now, to see if I can get a bit more information about the problem.

Thanks,

Ben

**Comment by ben-powell-ctct** [comment]
Hi Corey,

As you suspected, the corrupted data in the original capture was coming from the device attached to the port, which was responding to the break at 9600bps rather than 38400bps. However, I still see the same exception raised by pyserial even when the device is not attached to the serial port (but the serial port is still attached to the server). I have included another Wireshark capture which shows the issue: [ser2net-responds-to-break-off-with-break-on-no-device-connected.zip](https://github.com/user-attachments/files/18104813/ser2net-responds-to-break-off-with-break-on-no-device-connected.zip). In this file, 10.3.17.78 is the server, 10.3.17.215 is the client, and the RFC2217 messages are on port 2000. The last four packets in the file show pyserial sending first a "break on" request and then a "break off" request to ser2net. ser2net responds to the "break on" request with a "break on" response, but responds to the "break off" request with another "break on" response.

![image](https://github.com/user-attachments/assets/be2ad90c-34dd-4d76-ad76-6b06b9099c8c)
![image](https://github.com/user-attachments/assets/fb38115d-8a44-4aa9-91a4-c9e64644889b)

Is this behaviour correct? I couldn't see anything obvious in https://www.rfc-editor.org/rfc/rfc2217 which explains what the behaviour should be, but it seems logical that the server should respond to a "break off" request with a "break off" response.

I tried the trace gensio by adding `trace(file=/tmp/foo)` to the beginning of the `connector` entries in the ser2net configuration file, but it doesn't seem to record port control commands.

I can work around this behaviour by ignoring the exception, as it appears the break condition is correctly generated by the serial port and ser2net is sending back the expected data from the connected device. If this behaviour is in fact incorrect I am happy to try fixing it, given a place to start looking.

Thanks,

Ben

**Comment by cminyard** [comment]
On Wed, Dec 11, 2024 at 06:47:45PM -0800, ben-powell-ctct wrote:
> Hi Corey,
> 
> As you suspected, the corrupted data in the original capture was coming from the device attached to the port, which was responding to the break at 9600bps rather than 38400bps.

Well, I'm sort of glad it was what I expected, because I was at a loss
to explain it otherwise.

>However, I still see the same exception raised by pyserial even when the device is not attached to the serial port (but the serial port is still attached to the server). I have included another Wireshark capture which shows the issue: [ser2net-responds-to-break-off-with-break-on-no-device-connected.zip](https://github.com/user-attachments/files/18104813/ser2net-responds-to-break-off-with-break-on-no-device-connected.zip). In this file, 10.3.17.78 is the server, 10.3.17.215 is the client, and the RFC2217 messages are on port 2000. The last four packets in the file show pyserial sending first a "break on" request and then a "break off" request to ser2net. ser2net responds to the "break on" request with a "break on" response, but responds to the "break off" request with another "break on" response.
> 
> ![image](https://github.com/user-attachments/assets/be2ad90c-34dd-4d76-ad76-6b06b9099c8c)
> ![image](https://github.com/user-attachments/assets/fb38115d-8a44-4aa9-91a4-c9e64644889b)
> 
> Is this behaviour correct? I couldn't see anything obvious in https://www.rfc-editor.org/rfc/rfc2217 which explains what the behaviour should be, but it seems logical that the server should respond to a "break off" request with a "break off" response.

No, obviously it's not.

> 
> I tried the trace gensio by adding `trace(file=/tmp/foo)` to the beginning of the `connector` entries in the ser2net configuration file, but it doesn't seem to record port control commands.

You would have to put it between telnet and tcp to catch the port
control commands.

> 
> I can work around this behaviour by ignoring the exception, as it appears the break condition is correctly generated by the serial port and ser2net is sending back the expected data from the connected device. If this behaviour is in fact incorrect I am happy to try fixing it, given a place to start looking.

Well, you do a release, and then someone finds a bug.  It seems to
always happen :-).

I've pushed up a fix to the gensio library git tree.  Basically, the
tty ioctls do not allow you to fetch the current break state for some
strange reason (why didn't they do TIOCGBRK?).  So the gensio library
stores the current value of break down in the bowls of the serial port
handling.  Unfortunately, it was storing the wrong value, so once you
did a break setting, it would report "on" forever.  The good news is
that break is set correctly, it's just the report that's wrong.

I can do a new release if you like.

The diff is:

diff --git a/lib/gensio_osops.c b/lib/gensio_osops.c
index 8d4053ff..370a2e11 100644
--- a/lib/gensio_osops.c
+++ b/lib/gensio_osops.c
@@ -3064,7 +3064,7 @@ gensio_unix_termios_control(struct gensio_os_funcs *o, int op, bool get,
                if (errno != ENOTTY) /* Happens with PTYs. */
                    return gensio_os_err_to_err(o, errno);
            }
-           t->break_set = nval;
+           t->break_set = val;
        }
        break;


Thanks for reporting this.

-corey

**Comment by ben-powell-ctct** [comment]
Hi Corey,

Thanks for sorting this out. Don't worry about doing a new release just for this unless other people need it, as I am building gensio and ser2net from source in my application so I can fetch the commit hash of the gensio source which contains the fix.

Thanks,

Ben

**Comment by cminyard** [comment]
Again, thanks for reporting this.

-corey
