### ISSUE TITLE
Segmentation fault by closing Telnet to Admin

### ISSUE THREAD

**Issue by mpflaga** [cminyard/ser2net#16]
I have just discovered you fork to Ser2net and very much like the improvements. 

Where I have found that I can Seg Fault the latest version. Simply by disconnecting the Telnet Session to the Admin Acceptor. It works correctly if the user types "exit" or "quit" at the Admin prompt. But when closed by the Telnet client while at the Admin prompt the below happens.

`root@raspberrypi(buster):~# /usr/sbin/ser2net -c /etc/ser2net.conf -n -d &`
`[1] 4757`
`root@raspberrypi(buster):~# telnet localhost 1999`
`Trying ::1...`
`Connected to localhost.`
`Escape character is '^]'.`
`-> version`
`ser2net version 4.1`
`-> exit` **Using the Exit Command with expected result**
`Connection closed by foreign host.`
`root@raspberrypi(buster):~# `
`root@raspberrypi(buster):~# telnet localhost 1999`
`Trying ::1...`
`Connected to localhost.`
`Escape character is '^]'.`
`-> version`
`ser2net version 4.1`
`-> `  **I typed Ctl+]**
`telnet> q` **Not using the exit command**
`Connection closed.`
`[1]+  Segmentation fault      /usr/sbin/ser2net -c /etc/ser2net.conf -n -d` **Opps Something bad Happened.**
`root@raspberrypi(buster):~# telnet localhost 1999`
`Trying ::1...`
`Trying 127.0.0.1...`
`telnet: Unable to connect to remote host: Connection refused`
`root@raspberrypi(buster):~# `

Here is the config file
`root@raspberrypi(buster):~# cat /etc/ser2net.conf`
`%YAML 1.1`
`---`
`admin:`
`__accepter: telnet,tcp,1999`
`define: &banner1 Ser2net \N,\p,\d,\I \r\n`
`connection: &CON0`
`__accepter: telnet,tcp,2011`
`__timeout: 600`
`__enable: on`
`__connector: serialdev,/dev/ttyUSB0,115200n81,LOCAL`
`__options:`
`____banner: *banner1`
`____kickolduser: true`
`root@LNN-TerminalServer-QA:~#`

The problem occurs on Jessie also. And from different telnet clients. I have not tried earlier versions of this fork. Where I know the standard release package at 2.9.1 does not have this issue.

**Comment by cminyard** [comment]
Yeah, that was a dumb mistake.  Fixes are pushed to git and will be in the next release.  Thanks for reporting.
