### ISSUE TITLE
ser2net 3.5 in Debian 10 hangs when data length to send is 0

### ISSUE THREAD

**Issue by hthiery** [cminyard/ser2net#17]
I used ser2net 2.9.1 from Debian 9 without problems. Since updating to ser2net 3.5 with Debian 10 I faced an issue that my application does not longer work. After doing a git bisect I figured out that with commit be3cffd595dcb79116e080383076f40dae8a58d6 the problem was introduced.

This seems to be the problem:
```
+    to_send = buf->cursize - *pos;
+    if (to_send <= 0)
+       /* Don't send empty packets, that can confuse UDP clients. */
+       return;
+
+    reterr = sendto(netcon->fd, buf->buf + *pos, to_send,
```

I see that with that the code ends up in a loop that point where `to_send` is negative,

**Comment by hthiery** [comment]
I did some tests and with the following "hack" the problem does no longer occure. But I don't know if this is the right point to fix.

```
--- a/dataxfer.c
+++ b/dataxfer.c
@@ -1,4 +1,4 @@
-/*
+/:set*
  *  ser2net - A program for allowing telnet connection to serial ports
  *  Copyright (C) 2001  Corey Minyard <minyard@acm.org>
  *
@@ -1226,9 +1226,11 @@ net_fd_write(port_info_t *port, net_info_t *netcon,
     }

     to_send = buf->cursize - *pos;
-    if (to_send <= 0)
+    if (to_send <= 0) {
        /* Don't send empty packets, that can confuse UDP clients. */
+       *pos = buf->cursize;
        return;
+    }

     reterr = net_write(netcon->fd, buf->buf + *pos, to_send,
                       0, netcon->udpraddr, netcon->udpraddrlen);
```

**Comment by cminyard** [comment]
On Mon, Jan 20, 2020 at 02:30:57AM -0800, Heiko Thiery wrote:
> I did some tests and with the following "hack" the problem does no longer occure. But I don't know if this is the right point to fix.
> 
> ```
> --- a/dataxfer.c
> +++ b/dataxfer.c
> @@ -1,4 +1,4 @@
> -/*
> +/:set*
>   *  ser2net - A program for allowing telnet connection to serial ports
>   *  Copyright (C) 2001  Corey Minyard <minyard@acm.org>
>   *
> @@ -1226,9 +1226,11 @@ net_fd_write(port_info_t *port, net_info_t *netcon,
>      }
> 
>      to_send = buf->cursize - *pos;
> -    if (to_send <= 0)
> +    if (to_send <= 0) {
>         /* Don't send empty packets, that can confuse UDP clients. */
> +       *pos = buf->cursize;
>         return;
> +    }

That's good information.

This implies that *pos > buf->cursize, which shouldn't be possible.
Are you doing multiple connections to the same device?

-corey

**Comment by hthiery** [comment]
> On Mon, Jan 20, 2020 at 02:30:57AM -0800, Heiko Thiery wrote: I did some tests and with the following "hack" the problem does no longer occure. But I don't know if this is the right point to fix. ``` --- a/dataxfer.c +++ b/dataxfer.c @@ -1,4 +1,4 @@ -/* +/:set* * ser2net - A program for allowing telnet connection to serial ports * Copyright (C) 2001 Corey Minyard ***@***.***> * @@ -1226,9 +1226,11 @@ net_fd_write(port_info_t *port, net_info_t *netcon, } to_send = buf->cursize - *pos; - if (to_send <= 0) + if (to_send <= 0) { /* Don't send empty packets, that can confuse UDP clients. */ + *pos = buf->cursize; return; + }
> That's good information. This implies that *pos > buf->cursize, which shouldn't be possible. Are you doing multiple connections to the same device?

No. I only have one connection.

> […](#)
> -corey
> reterr = net_write(netcon->fd, buf->buf + *pos, to_send, 0, netcon->udpraddr, netcon->udpraddrlen); ``` -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#17 (comment)](https://github.com/cminyard/ser2net/issues/17#issuecomment-576210134)

**Comment by cminyard** [comment]
On Mon, Jan 20, 2020 at 11:08:37AM -0800, Heiko Thiery wrote:
> > On Mon, Jan 20, 2020 at 02:30:57AM -0800, Heiko Thiery wrote: I did some tests and with the following "hack" the problem does no longer occure. But I don't know if this is the right point to fix. ``` --- a/dataxfer.c +++ b/dataxfer.c @@ -1,4 +1,4 @@ -/* +/:set* * ser2net - A program for allowing telnet connection to serial ports * Copyright (C) 2001 Corey Minyard ***@***.***> * @@ -1226,9 +1226,11 @@ net_fd_write(port_info_t *port, net_info_t *netcon, } to_send = buf->cursize - *pos; - if (to_send <= 0) + if (to_send <= 0) { /* Don't send empty packets, that can confuse UDP clients. */ + *pos = buf->cursize; return; + }
> > That's good information. This implies that *pos > buf->cursize, which shouldn't be possible. Are you doing multiple connections to the same device?
> 
> No. I only have one connection.
> 

Ok.  Do you have a procedure to reproduce?

-corey

**Comment by hthiery** [comment]
> Ok. Do you have a procedure to reproduce?

Unfortunatly not at the moment. I will try to reduce the setup and try to prepare a procedure.

Do you have another idea how I can figure out what goes wrong? Is there a way to enable a more verbose debug output? Or do you have an idea where I can take a look in detail?

**Comment by hthiery** [comment]
In our application we use the RTS signal to do some special "debug" control of our hardware. As you can see when we toggle this line the error occurs.

```
dataxfer.c: net_fd_write: 1229: *pos=0 buf->cursize=0       <<< all ok
dataxfer.c: net_fd_write: 1231: to_send=0
dataxfer.c: net_fd_write: 1229: *pos=0 buf->cursize=3
telnet.c: process_telnet_data: 168: len=0x1
telnet.c: process_telnet_data: 168: len=0x12
telnet.c: process_telnet_data: 168: len=0x11
telnet.c: process_telnet_data: 168: len=0x10
telnet.c: process_telnet_data: 168: len=0x9
telnet.c: process_telnet_data: 168: len=0x8
dataxfer.c: com_port_handler: 4311: *option=2c, len=3
devcfg.c: devcfg_control: 1194: val=0x0b       <<< set RTS
telnet.c: process_telnet_data: 168: len=0x6
telnet.c: process_telnet_data: 168: len=0x5
telnet.c: process_telnet_data: 168: len=0x4
telnet.c: process_telnet_data: 168: len=0x3
telnet.c: process_telnet_data: 168: len=0x2
telnet.c: process_telnet_data: 168: len=0x1
dataxfer.c: com_port_handler: 4311: *option=2c, len=3
devcfg.c: devcfg_control: 1194: val=0x0c       <<< clear RTS
dataxfer.c: net_fd_write: 1229: *pos=3 buf->cursize=0       <<< !! to send becomes negative
dataxfer.c: net_fd_write: 1231: to_send=-3
```

Any ideas?

**Comment by cminyard** [comment]
On Tue, Jan 21, 2020 at 01:58:20AM -0800, Heiko Thiery wrote:
> In our application we use the RTS signal to do some special "debug" control of our hardware. As you can see when we toggle this line the error occurs.
> 
> ```
> dataxfer.c: net_fd_write: 1229: *pos=0 buf->cursize=0       <<< all ok
> dataxfer.c: net_fd_write: 1231: to_send=0
> dataxfer.c: net_fd_write: 1229: *pos=0 buf->cursize=3
> telnet.c: process_telnet_data: 168: len=0x1
> telnet.c: process_telnet_data: 168: len=0x12
> telnet.c: process_telnet_data: 168: len=0x11
> telnet.c: process_telnet_data: 168: len=0x10
> telnet.c: process_telnet_data: 168: len=0x9
> telnet.c: process_telnet_data: 168: len=0x8
> dataxfer.c: com_port_handler: 4311: *option=2c, len=3
> devcfg.c: devcfg_control: 1194: val=0x0b       <<< set RTS
> telnet.c: process_telnet_data: 168: len=0x6
> telnet.c: process_telnet_data: 168: len=0x5
> telnet.c: process_telnet_data: 168: len=0x4
> telnet.c: process_telnet_data: 168: len=0x3
> telnet.c: process_telnet_data: 168: len=0x2
> telnet.c: process_telnet_data: 168: len=0x1
> dataxfer.c: com_port_handler: 4311: *option=2c, len=3
> devcfg.c: devcfg_control: 1194: val=0x0c       <<< clear RTS
> dataxfer.c: net_fd_write: 1229: *pos=3 buf->cursize=0       <<< !! to send becomes negative
> dataxfer.c: net_fd_write: 1231: to_send=-3
> ```
> 
> Any ideas?

Oh, this has to do with the telnet data processing being in a different
buffer, I think.  I assume you have rfc2217 turned on; I'm assuming
those 6 bytes are the telnet data with the RTS indication.

I'll try to look at this soon, but I can't just right now.

-corey

**Comment by hthiery** [comment]
> Oh, this has to do with the telnet data processing being in a different buffer, I think. I assume you have rfc2217 turned on; I'm assuming those 6 bytes are the telnet data with the RTS indication. I'll try to look at this soon, but I can't just right now.

Could that be related to the seen issue?

What do you mean with "have rfc2217 turned on"? We use the rfc2217 defined messages to control the console signals, in our case the RTS signal.

**Comment by cminyard** [comment]
On Wed, Jan 22, 2020 at 06:57:37AM -0800, Heiko Thiery wrote:
> > Oh, this has to do with the telnet data processing being in a different buffer, I think. I assume you have rfc2217 turned on; I'm assuming those 6 bytes are the telnet data with the RTS indication. I'll try to look at this soon, but I can't just right now.
> 
> Could that be related to the seen issue?

I think I know what is going on.  Are you using more than one thread?  I
think it's possible with just one thread, but a lot more likely with
multiple threads.

Anyway, can you try the attached patch?

> 
> What do you mean with "have rfc2217 turned on"? We use the rfc2217 defined messages to control the console signals, in our case the RTS signal.
> 

Yeah, I figured that out.  This wouldn't be happening if you didn't have
rfc2217 enabled in the config file.

-corey

**Comment by hthiery** [comment]
> On Wed, Jan 22, 2020 at 06:57:37AM -0800, Heiko Thiery wrote: > Oh, this has to do with the telnet data processing being in a different buffer, I think. I assume you have rfc2217 turned on; I'm assuming those 6 bytes are the telnet data with the RTS indication. I'll try to look at this soon, but I can't just right now. Could that be related to the seen issue?
> I think I know what is going on. Are you using more than one thread? I think it's possible with just one thread, but a lot more likely with multiple threads. Anyway, can you try the attached patch?

How can I see what thread config we use?

Sorry, but I can't find the patch.

> What do you mean with "have rfc2217 turned on"? We use the rfc2217 defined messages to control the console signals, in our case the RTS signal.
> Yeah, I figured that out. This wouldn't be happening if you didn't have rfc2217 enabled in the config file.

But then the control will no longer work, right?

**Comment by cminyard** [comment]
On Mon, Jan 27, 2020 at 11:06:25PM -0800, Heiko Thiery wrote:
> > On Wed, Jan 22, 2020 at 06:57:37AM -0800, Heiko Thiery wrote: > Oh, this has to do with the telnet data processing being in a different buffer, I think. I assume you have rfc2217 turned on; I'm assuming those 6 bytes are the telnet data with the RTS indication. I'll try to look at this soon, but I can't just right now. Could that be related to the seen issue?
> > I think I know what is going on. Are you using more than one thread? I think it's possible with just one thread, but a lot more likely with multiple threads. Anyway, can you try the attached patch?
> 
> How can I see what thread config we use?

That's the -t option on the command line.

> 
> Sorry, but I can't find the patch.

Grr, github stripped off the patch.  And github doesn't provide any way
to upload files; I guess they only want you to use git.

You can get it at https://sourceforge.net/projects/ser2net/files/ser2net/patches/0001-Clear-all-write_pos-when-data-is-done.patch

> 
> > What do you mean with "have rfc2217 turned on"? We use the rfc2217 defined messages to control the console signals, in our case the RTS signal.
> > Yeah, I figured that out. This wouldn't be happening if you didn't have rfc2217 enabled in the config file.
> 
> But then the control will no longer work, right?

It's remctl in the config file to turn it on.  I wasn't asking to turn
it off I was just making sure it was turned on.

-corey

**Comment by hthiery** [comment]
> That's the -t option on the command line.

I use the default setting, not explicitly add the -t option. So I think I use 1 thread.

> Grr, github stripped off the patch. And github doesn't provide any way to upload files; I guess they only want you to use git. You can get it at https://sourceforge.net/projects/ser2net/files/ser2net/patches/0001-Clear-all-write_pos-when-data-is-done.patch

I applied the patch and and looks good. No errors/hanging anymore.

I added a printf to see the value of `to_send` and see it never becomes less than 0.

```
--- a/dataxfer.c
+++ b/dataxfer.c
@@ -1236,9 +1236,11 @@ net_fd_write(port_info_t *port, net_info_t *netcon,
     }
 
     to_send = buf->cursize - *pos;
-    if (to_send <= 0)
+    if (to_send <= 0) {
+        printf("here .. %d\n", to_send);
        /* Don't send empty packets, that can confuse UDP clients. */
        return;
+    }
 
     reterr = net_write(netcon->fd, buf->buf + *pos, to_send,
                       0, netcon->udpraddr, netcon->udpraddrlen);
```


> It's remctl in the config file to turn it on. I wasn't asking to turn it off I was just making sure it was turned on.

Ok. I see.

just for completness ... here is my config file I used for testing:

`2020:telnet:0:/dev/ttyUSB-FTFB6VTU:115200 8DATABITS NONE 1STOPBIT LOCAL`
