### ISSUE TITLE
Broken pipe after "Could not turn off break..."

### ISSUE THREAD

**Issue by AKBON** [cminyard/ser2net#18]
Hi,

I have an Arduino connected to a Pi via USB. I'm using ser2net for remote control over TCP. Sometimes the connection breaks with the message:

"Could not turn off break for device /dev/ttyAMA0 port 2353: Broken pipe" 

Only resetting the Arduino helps. Is there any way to avoid this?

configuration:

2358:raw:1000:/dev/ttyACM0:9600 HANGUP_WHEN_DONE disable-chardelay

"disable-chardelay" was just an attempt.

Thanks
Andre

**Comment by cminyard** [comment]
On Mon, Jan 27, 2020 at 12:55:28AM -0800, AKBON wrote:
> Hi,
> 
> I have an Arduino connected to a Pi via USB. I'm using ser2net for remote control over TCP. Sometimes the connection breaks with the message:
> 
> "Could not turn off break for device /dev/ttyAMA0 port 2353: Broken pipe" 
> 
> Only resetting the Arduino helps. Is there any way to avoid this?

What version of ser2net are you using?

Also, the error above says /dev/ttyAMA0, and the config below says
/dev/ttyACM0.  What's the deal with that?

-corey

**Comment by AKBON** [comment]
Version is 2.10.1

And the other thing is just a c/p confusion, sorry.

**Comment by cminyard** [comment]
On Mon, Jan 27, 2020 at 02:22:53AM -0800, AKBON wrote:
> Version is 2.10.1

That's a really old version.

> 
> And the other thing is just a c/p confusion, sorry.

Ok.  You can try adding the LOCAL setting, which will disable modem
control.  Usually a hangup comes from that.

-corey

**Comment by AKBON** [comment]
Ah, OK, it's the version you get when installing via apt. I downloaded an built the current version from sourceforge now and set the LOCAL option like this...that's what you meant?

2358:raw:1000:/dev/ttyACM0:9600 HANGUP_WHEN_DONE LOCAL

I will observe the behaviour. Thanks so far!

**Comment by cminyard** [comment]
On Mon, Jan 27, 2020 at 08:21:19AM -0800, AKBON wrote:
> Ah, OK, it's the version you get when installing via apt. I downloaded an built the current version from sourceforge now and set the LOCAL option like this...that's what you meant?

I should have said to use the latest 3.5.x release; the new stuff is
still kind of bleeding edge.  Hopefuly that's what you did.  The new
stuff should work, but there are some significant changes.

> 
> 2358:raw:1000:/dev/ttyACM0:9600 HANGUP_WHEN_DONE LOCAL

Yes, that should do it.  You may have modem control lines that are
unconnected, they might change states periodically if not properly
terminated.

> 
> I will observe the behaviour. Thanks so far!

Ok, let me know.

-corey

**Comment by AKBON** [comment]
Hi,

I am not sure, if this is something new or actually has the same cause. I connected my Arduino to the Pi and sent messages over ser2net (repeating attempts), what gave this output to syslog:

> 
> Jan 30 11:46:34 raspberrypi kernel: [96338.110654] usb 1-1.2: new high-speed USB device number 13 using dwc_otg
> Jan 30 11:46:34 raspberrypi kernel: [96338.241852] usb 1-1.2: New USB device found, idVendor=2341, idProduct=003e
> Jan 30 11:46:34 raspberrypi kernel: [96338.241867] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber$
> Jan 30 11:46:34 raspberrypi kernel: [96338.241876] usb 1-1.2: Product: MIPS
> Jan 30 11:46:34 raspberrypi kernel: [96338.241884] usb 1-1.2: Manufacturer: GAA Custom Electronics, LLC
> Jan 30 11:46:34 raspberrypi kernel: [96338.244183] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
> Jan 30 11:46:34 raspberrypi mtp-probe: checking bus 1, device 13: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1$
> Jan 30 11:46:34 raspberrypi mtp-probe: bus: 1, device: 13 was not an MTP device
> Jan 30 11:48:09 raspberrypi ser2net[16949]: ser2net startup
> Jan 30 11:48:09 raspberrypi kernel: [96433.150238] No dialect specified on mount. Default has changed to a more secu$
> Jan 30 11:48:09 raspberrypi kernel: [96433.157233] CIFS VFS: ioctl error in smb2_get_dfs_refer rc=-5
> Jan 30 11:48:43 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:43 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:44 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:45 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:45 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:46 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:46 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:46 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:47 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:48 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:48 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> Jan 30 11:48:49 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory

Arduino restart did not help on this, only reboot of Pi. Is this still an Arduino/USB device issue or something else? Better use 3.5.x release as you mentioned?

**Comment by cminyard** [comment]
On Thu, Jan 30, 2020 at 03:17:38AM -0800, AKBON wrote:
> Hi,
> 
> I am not sure, if this is something new or actually has the same cause. I connected my Arduino to the Pi and sent messages over ser2net (repeating attempts), what gave this output to syslog:
> 

snip...

> > Jan 30 11:48:49 raspberrypi ser2net[919]: dev read error for device on port 2358: No such file or directory
> 
> Arduino restart did not help on this, only reboot of Pi. Is this still an Arduino/USB device issue or something else? Better use 3.5.x release as you mentioned?

That means that a read() call on the device returned ENOENT.  That is
not a "normal" return value for read, but on removable devices it can
happen.

My guess would be that there is something wrong with either the driver or
the Arduino where the Arduino device disappears from the USB bus from the
driver's point of view.  Hard to say for 100% sure, but I don't think
this is a bug in ser2net.

If you can reproduce this, you could try using screen or minicom or
something like that to open the device and see if you can talk to it.
That would narrow it down.

Sticking with ser2net 4.x is ok if it works for you.  For the latest
releases of ser2net and gensio things have stabilized (I hope).  You can
try 3.5.x, but I doubt it will make any difference for this. But, it may
be worth trying.

-corey

**Comment by AKBON** [comment]
Hi, 

OK, thanks for the description, and I think you're right. Maybe it's an EMC problem or something like that. 

I think I figured out a procedure to handle this without hard rebooting anything. I can make a soft reset of the serial port of the Arduino. After that a restart of ser2net is necessary...probably because the serial object/file or whatever changes and the message that I posted in my previous comment appears.

So the plan is: monitor syslog for the error message followed by a restart of ser2net.

If I do that in the console with the -d flag I can stop and restart ser2net with Ctrl+C, but how can I do it if the ser2net was started without the -d flag, so, when it's running in background? I couldn't find it in the process list.

**Comment by cminyard** [comment]
On Thu, Jan 30, 2020 at 06:42:54AM -0800, AKBON wrote:
> Hi, 
> 
> OK, thanks for the description, and I think you're right. Maybe it's an EMC problem or something like that. 
> 
> I think I figured out a procedure to handle this without hard rebooting anything. I can make a soft reset of the serial port of the Arduino. After that a restart of ser2net is necessary...probably because the serial object/file or whatever changes and the message that I posted in my previous comment appears.
> 
> So the plan is: monitor syslog for the error message followed by a restart of ser2net.

That is unfortunate :-(,

> 
> If I do that in the console with the -d flag I can stop and restart ser2net with Ctrl+C, but how can I do it if the ser2net was started without the -d flag, so, when it's running in background? I couldn't find it in the process list.
> 

It's running, just not under your process.  You can have ser2net save
its pid in a file using the "-P <file>" option, then you can just kill the
process specified by the pid in the file.

If you want to see it, use "ps ax".  If it's not running in that output,
it's not running.

-corey
