### ISSUE TITLE
yaml configuration for TRACEFILE?

### ISSUE THREAD

**Issue by medrapal** [cminyard/ser2net#19]
First off - thanks for such a great tool!  It meets most of what I need for a project that I'm working on.

What I think I need is an example (in the new yaml format) to specify the trace file, similar to the old TRACEFILE:name:value form.  I've tried setting up a define: and that seems to work for banners, but not for tb/tr/t2 options.  I've also tried using straight-up strings with these options with no joy.

Here is what my current configuration looks like:

%YAML 1.1
---

define: &confver 1.0
define: &banner1 This is a banner for port \N(\p)\r\n
define: &log1 "/var/log/cicada0"

connection: &con00
  accepter: telnet(rfc2217),tcp,7000
  connector: serialdev,/dev/ttyUSB0,115200n81,local
  options:
    banner: *banner1
    tb: *log1

In syslog, I continue to get an error:
/var/log/user.log:Jan 28 21:54:19 beaglebone ser2net: Tracefile /var/log/cicada0 not found, it will be ignored

I get this error both when I use the indirection (*log1) or when I put an explicit string there (with and without double quotes).

I turned on DEBUG in the yaml parsing and it looks like the define: is properly parsed (e.g. same as banner1).

Normally I wouldn't care about this but the application is for serial port data logging, and the tracefile seemed to be a perfect fit for that.

Do you have an example (in the yaml format) for specifying a tracefile?

**Comment by cminyard** [comment]
I apologize, for some reason I'm not seeing these issue when they happen.  This is a bug in the new yaml configuration, I'll get a fix out soon.

**Comment by cminyard** [comment]
Ok, fixes are pushed up to the master branch in git.  I've renamed tb, tr, tw to trace-both, trace-read, and trace-write to make it easier to read and to make backwards compatibility easier.  Since obviously no one was using it, this seems safe and prudent.
