### ISSUE TITLE
just a question: what does ser2net transmit in raw mode?

### ISSUE THREAD

**Issue by rin67630** [cminyard/ser2net#2]
Please allow me a question, since I was not successful in replacing a ser2net connection to a blackbox program by a direct TCP connection, both on localhost.

Which protocol is used for a raw ser2net connection? 
TCP - UDP?
Every byte received on the serial port will be passed 1-1 to the TCP-UDP socket, OK?
Does is use some kind of wrapping around? X-on X-off? Checksums...?

Thankyou for your enlightment.

**Comment by cminyard** [comment]
On 04/28/2018 12:37 PM, rin67630 wrote:
>
> Please allow me a question, since I was not successful in replacing a 
> ser2net connection to a blackbox program by a direct TCP connection, 
> both on localhost.
>
> Which protocol is used for a raw ser2net connection?
> TCP - UDP?
>

Both are supported.

> Every byte received on the serial port will be passed 1-1 to the 
> TCP-UDP socket, OK?
>

Yes

> Does is use some kind of wrapping around?
>

I don't know what you mean by that.

> X-on X-off? Checksums...?
>

xon/xoff happens on the serial port, not on the ser2net connection. If 
the serial
port is configured for that, it will be done on the serial port, but you 
won't see it
on the network side.

No checksums besides what's in TCP/UDP.

ser2net has a fairly complicated configuration capability.  It's simple 
if you are
doing simple things, but there's plenty of non-simple things it does.

> Thankyou for your enlightment.
>

You are welcome.

-corey
