### ISSUE TITLE
librt is required unconditionally

### ISSUE THREAD

**Issue by mistydemeo** [cminyard/ser2net#3]
In 4f36de55269a084bf8cab86158a25f150c599e67, `-lrt` was added to the `LDFLAGS` unconditionally in order to provide `clock_gettime`. Not all OSs use the librt name; for example, OS X provides `clock_gettime` in its libc, and doesn't have a library by that name. It would be great to add a check so that `-lrt` is only passed when necessary.

**Comment by cminyard** [comment]
This is fixed in the latest release.  Thanks.
