### ISSUE TITLE
Telnet issues with RFC2217 and NetSerial

### ISSUE THREAD

**Issue by nriedel** [cminyard/ser2net#30]
Hi,
I have been working to get ser2net working with the NetSerial PC client (https://pcmicro.com/NetSerial/).  I am currently using v3.5.2 of ser2net, but I have seen similar problems with v4.1.8.

When connecting from a PC using the NetSerial client, I get a runaway back and forth of telnet commands (BINARY_TRANSMISSION and SUPPRESS_GO_AHEAD).  This problem appears to be similar to the one here: https://github.com/cminyard/ser2net/issues/8.  I fixed it for the NetSerial client by modifying the initial values of telnet_cmds[] in dataxfer.c and removing WILL BINARY TRANSMISSION from telnet_init_seq[] in the same file.  I don't know if this problem is due to NetSerial's client or the ser2net server.

A second problem occurred when I connected the NetSerial client, then disconnected, then connected again.  In this case I got runaway DO/DONT WILL/WONT ECHO commands between the client and server.  

I think the second problem is due to a bug in telnet.c in the function telnet_init().  This function sets the cmds member of the telnet_data_t structure to be equal to the passed-in cmds pointer.  This means that the telnet_data_t structure has a member that points to the static telnet_cmds[] array in dataxfer.c.  The problem is that all telnet data connections will point to this same array.

The telnet_cmds[] array includes state information about the telnet connection.  So all telnet data connections share the same state, which of course is not correct since each should be independent.  In my test case, disconnecting and reconnecting caused the new connection to continue with the state of the previous connection.   

I fixed this problem by changing telnet_init() to copy the telnet_cmds array into a new array that I added to the telnet_data_t structure, and setting the cmds point in this structure to point to the new array.  In this way, each connection has its own array of cmds.

**Comment by cminyard** [comment]
On Tue, Jun 16, 2020 at 03:30:24PM -0700, nriedel wrote:
> Hi,
> I have been working to get ser2net working with the NetSerial PC client (https://pcmicro.com/NetSerial/).  I am currently using v3.5.2 of ser2net, but I have seen similar problems with v4.1.8.
> 
> When connecting from a PC using the NetSerial client, I get a runaway back and forth of telnet commands (BINARY_TRANSMISSION and SUPPRESS_GO_AHEAD).  This problem appears to be similar to the one here: https://github.com/cminyard/ser2net/issues/8.  I fixed it for the NetSerial client by modifying the initial values of telnet_cmds[] in dataxfer.c and removing WILL BINARY TRANSMISSION from telnet_init_seq[] in the same file.  I don't know if this problem is due to NetSerial's client or the ser2net server.

Sigh.  The telnet RFC is impossible to understand.  I have reworked this
ad I'm attaching a patch.  This is a problem in 3.5 and 4.x.

The bug is actually on both sides.  If either side did thing completely
correct, it wouldn't go into the loop.

> 
> A second problem occurred when I connected the NetSerial client, then disconnected, then connected again.  In this case I got runaway DO/DONT WILL/WONT ECHO commands between the client and server.  

I fixed this at least once.  This is not a problem on the 4.x but I
forgot to backport this fix to 3.5.  Another patch is attached.

If these work and fix your problems, I'll include them and do a release.

-corey

**Comment by nriedel** [comment]
Hi Corey,

Thank you for the quick response.  I was on-site integrating with our customer yesterday, and found that there were some issues with the multiplexing of telnet commands and user data that appear to have been solved by some of the commits since version 3.5.2.

I'm not seeing any attachments on your message.  Am I missing something?

Thanks,
Neal Riedel

**Comment by cminyard** [comment]
On Thu, Jun 18, 2020 at 12:30:13PM -0500, Corey Minyard wrote:
> On Thu, Jun 18, 2020 at 09:23:37AM -0700, nriedel wrote:
> > Hi Corey,
> > 
> > Thank you for the quick response.  I was on-site integrating with our customer yesterday, and found that there were some issues with the multiplexing of telnet commands and user data that appear to have been solved by some of the commits since version 3.5.2.
> 
> Yeah, I seem to remember something like that.
> 
> > 
> > I'm not seeing any attachments on your message.  Am I missing something?
> 
> I guess github stripped them.  I've pushed them into upstream git to
> make it easy for you to get.

Any news on this?  I'd like to close this out and do a release.

-corey

**Comment by nriedel** [comment]
Hi Corey,
Sorry for the delay.  I tested these updates and they seem to be working correctly.  Thank you very much for your help!
Neal

**Comment by cminyard** [comment]
Thanks for the testing.  The release was don a while ago.
