### ISSUE TITLE
every second restart attempt fails

### ISSUE THREAD

**Issue by evilgreen** [cminyard/ser2net#31]
Running ser2net 3.5.2 on Debian Buster.
Occasionally noticed that every 2nd restart attempt fails:

```
# systemctl status ser2net.service
● ser2net.service - LSB: Allows network connections to serial ports
   Loaded: loaded (/etc/init.d/ser2net; generated)
   Active: active (running) since Sat 2020-07-04 12:17:55 ; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9857 ExecStart=/etc/init.d/ser2net start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4168)
   Memory: 1.4M
   CGroup: /system.slice/ser2net.service
           └─9873 /usr/sbin/ser2net -c /etc/ser2net.conf -P /run/ser2net.pid

Jul 04 12:17:55 cubox systemd[1]: Starting LSB: Allows network connections to serial ports...
Jul 04 12:17:55 cubox ser2net[9871]: ser2net startup
Jul 04 12:17:55 cubox ser2net[9857]: Starting Serial port to network proxy: ser2net.
Jul 04 12:17:55 cubox systemd[1]: Started LSB: Allows network connections to serial ports.
root@cubox:~# 
root@cubox:~# systemctl restart ser2net.service
Job for ser2net.service failed because the control process exited with error code.
See "systemctl status ser2net.service" and "journalctl -xe" for details.
root@cubox:~# 
root@cubox:~# systemctl restart ser2net.service
root@cubox:~# 
root@cubox:~# systemctl restart ser2net.service
Job for ser2net.service failed because the control process exited with error code.
See "systemctl status ser2net.service" and "journalctl -xe" for details.
root@cubox:~# 
```

**Comment by cminyard** [comment]
On Sat, Jul 04, 2020 at 02:32:50AM -0700, AndrewZ wrote:
> Running ser2net 3.5.2 on Debian Buster.
> Occasionally noticed that every 2nd restart attempt fails:
> 
> ```
> # systemctl status ser2net.service
> ● ser2net.service - LSB: Allows network connections to serial ports
>    Loaded: loaded (/etc/init.d/ser2net; generated)
>    Active: active (running) since Sat 2020-07-04 12:17:55 MSK; 10min ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 9857 ExecStart=/etc/init.d/ser2net start (code=exited, status=0/SUCCESS)
>     Tasks: 1 (limit: 4168)
>    Memory: 1.4M
>    CGroup: /system.slice/ser2net.service
>            └─9873 /usr/sbin/ser2net -c /etc/ser2net.conf -P /run/ser2net.pid
> 
> Jul 04 12:17:55 cubox systemd[1]: Starting LSB: Allows network connections to serial ports...
> Jul 04 12:17:55 cubox ser2net[9871]: ser2net startup
> Jul 04 12:17:55 cubox ser2net[9857]: Starting Serial port to network proxy: ser2net.
> Jul 04 12:17:55 cubox systemd[1]: Started LSB: Allows network connections to serial ports.
> root@cubox:~# 
> root@cubox:~# systemctl restart ser2net.service
> Job for ser2net.service failed because the control process exited with error code.
> See "systemctl status ser2net.service" and "journalctl -xe" for details.
> root@cubox:~# 
> root@cubox:~# systemctl restart ser2net.service
> root@cubox:~# 
> root@cubox:~# systemctl restart ser2net.service
> Job for ser2net.service failed because the control process exited with error code.
> See "systemctl status ser2net.service" and "journalctl -xe" for details.
> root@cubox:~# 

I'm not sure how this could happen.  Can you do "systemctl status ser2net.service" and "journalctl -xe" like it suggests to get more details?

-corey

**Comment by evilgreen** [comment]
> Can you do "systemctl status ser2net.service" and "journalctl -xe" like it suggests to get more details?

Sure, please see below

````root@cubox:~# systemctl restart ser2net.service
Job for ser2net.service failed because the control process exited with error code.
See "systemctl status ser2net.service" and "journalctl -xe" for details.
root@cubox:~# 
root@cubox:~# systemctl status ser2net.service
● ser2net.service - LSB: Allows network connections to serial ports
   Loaded: loaded (/etc/init.d/ser2net; generated)
   Active: failed (Result: exit-code) since Sun 2020-07-05 11:45:04 ; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17046 ExecStart=/etc/init.d/ser2net start (code=exited, status=1/FAILURE)
    Tasks: 0 (limit: 4168)
   Memory: 1.5M
   CGroup: /system.slice/ser2net.service

Jul 05 11:45:03 cubox systemd[1]: Starting LSB: Allows network connections to serial ports...
Jul 05 11:45:04 cubox ser2net[17046]: Starting Serial port to network proxy: ser2netalready running! ... failed!
Jul 05 11:45:04 cubox ser2net[17046]:  failed!
Jul 05 11:45:04 cubox systemd[1]: ser2net.service: Control process exited, code=exited, status=1/FAILURE
Jul 05 11:45:04 cubox systemd[1]: ser2net.service: Failed with result 'exit-code'.
Jul 05 11:45:04 cubox systemd[1]: Failed to start LSB: Allows network connections to serial ports.
root@cubox:~# 
root@cubox:~# journalctl -xe
Jul 05 11:45:03 cubox systemd[1]: Stopped LSB: Allows network connections to serial ports.
-- Subject: A stop job for unit ser2net.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit ser2net.service has finished.
-- 
-- The job identifier is 7150 and the job result is done.
Jul 05 11:45:03 cubox systemd[1]: ser2net.service: Found left-over process 11009 (ser2net) in control group while starting unit. Ignoring.
Jul 05 11:45:03 cubox systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jul 05 11:45:03 cubox systemd[1]: Starting LSB: Allows network connections to serial ports...
-- Subject: A start job for unit ser2net.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit ser2net.service has begun execution.
-- 
-- The job identifier is 7150.
Jul 05 11:45:04 cubox ser2net[17046]: Starting Serial port to network proxy: ser2netalready running! ... failed!
Jul 05 11:45:04 cubox ser2net[17046]:  failed!
Jul 05 11:45:04 cubox systemd[1]: ser2net.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit ser2net.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Jul 05 11:45:04 cubox systemd[1]: ser2net.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit ser2net.service has entered the 'failed' state with result 'exit-code'.
Jul 05 11:45:04 cubox systemd[1]: Failed to start LSB: Allows network connections to serial ports.
-- Subject: A start job for unit ser2net.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit ser2net.service has finished with a failure.
-- 
-- The job identifier is 7150 and the job result is failed.
root@cubox:~# 
````

**Comment by cminyard** [comment]
On Sun, Jul 05, 2020 at 01:53:44AM -0700, AndrewZ wrote:
> > Can you do "systemctl status ser2net.service" and "journalctl -xe" like it suggests to get more details?
> 
> Sure, please see below

Hmm:

Jul 05 11:45:04 cubox ser2net[17046]: Starting Serial port to network proxy: ser2netalready running! ... failed!

That doesn't seem to be coming from ser2net, so something else is
printing that.  I don't know why, but it appears that ser2net didn't
stop.  Can you poke a bit to see if that's really the case?

I guess syslog is the best way to see what is going on.

-corey

**Comment by evilgreen** [comment]
> I guess syslog is the best way to see what is going on.

here is the relevant part of the log:
```
Jul  5 11:45:03 localhost systemd[1]: Stopping LSB: Allows network connections to serial ports...
Jul  5 11:45:03 localhost ser2net[17032]: Stopping Serial port to network proxy: ser2net.
Jul  5 11:45:03 localhost systemd[1]: ser2net.service: Succeeded.
Jul  5 11:45:03 localhost systemd[1]: Stopped LSB: Allows network connections to serial ports.
Jul  5 11:45:03 localhost systemd[1]: ser2net.service: Found left-over process 11009 (ser2net) in control group while starting unit. Ignoring.
Jul  5 11:45:03 localhost systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jul  5 11:45:03 localhost systemd[1]: Starting LSB: Allows network connections to serial ports...
Jul  5 11:45:04 localhost ser2net[17046]: Starting Serial port to network proxy: ser2netalready running! ... failed!
Jul  5 11:45:04 localhost ser2net[17046]:  failed!
Jul  5 11:45:04 localhost systemd[1]: ser2net.service: Control process exited, code=exited, status=1/FAILURE
Jul  5 11:45:04 localhost systemd[1]: ser2net.service: Failed with result 'exit-code'.
Jul  5 11:45:04 localhost systemd[1]: Failed to start LSB: Allows network connections to serial ports.
```

I'm also attaching automatically installed init script for ser2net:
[ser2net.txt](https://github.com/cminyard/ser2net/files/4891143/ser2net.txt)

**Comment by cminyard** [comment]
On Wed, Jul 08, 2020 at 07:16:23AM -0700, AndrewZ wrote:
> > I guess syslog is the best way to see what is going on.
> 
> here is the relevant part of the log:
> ```
> Jul  5 11:45:03 localhost systemd[1]: Stopping LSB: Allows network connections to serial ports...
> Jul  5 11:45:03 localhost ser2net[17032]: Stopping Serial port to network proxy: ser2net.
> Jul  5 11:45:03 localhost systemd[1]: ser2net.service: Succeeded.
> Jul  5 11:45:03 localhost systemd[1]: Stopped LSB: Allows network connections to serial ports.
> Jul  5 11:45:03 localhost systemd[1]: ser2net.service: Found left-over process 11009 (ser2net) in control group while starting unit. Ignoring.
> Jul  5 11:45:03 localhost systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.

Looks like it's not dying when it was sent the terminate signal.  Let me
look at it a bit.

-corey

**Comment by cminyard** [comment]
On Tue, Jul 14, 2020 at 06:36:27PM -0500, Corey Minyard wrote:
> On Wed, Jul 08, 2020 at 07:16:23AM -0700, AndrewZ wrote:
> > > I guess syslog is the best way to see what is going on.
> > 
> > here is the relevant part of the log:
> > ```
> > Jul  5 11:45:03 localhost systemd[1]: Stopping LSB: Allows network connections to serial ports...
> > Jul  5 11:45:03 localhost ser2net[17032]: Stopping Serial port to network proxy: ser2net.
> > Jul  5 11:45:03 localhost systemd[1]: ser2net.service: Succeeded.
> > Jul  5 11:45:03 localhost systemd[1]: Stopped LSB: Allows network connections to serial ports.
> > Jul  5 11:45:03 localhost systemd[1]: ser2net.service: Found left-over process 11009 (ser2net) in control group while starting unit. Ignoring.
> > Jul  5 11:45:03 localhost systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
> 
> Looks like it's not dying when it was sent the terminate signal.  Let me
> look at it a bit.

Is ser2net still running when this happens?  It takes a few seconds for
ser2net to shut down when it is sent a terminate signal.  Since it
happens ever other time, I'm wondering if it's just too slow to die.

-corey

**Comment by evilgreen** [comment]
I was able to reproduce the issue and test the fix with the following command:
`/etc/init.d/ser2net stop && sleep 0.5 && /etc/init.d/ser2net start`
Using the smaller _sleep_ values I was getting the error as before.
I've tried to add a similar pause between _stop_ and _start_ in the init.d script however that was ignored. Do I need to do something special to update init.d script?

**Comment by cminyard** [comment]
On Wed, Jul 15, 2020 at 08:53:18AM -0700, AndrewZ wrote:
> I was able to reproduce the issue and test the fix with the following command:
> `/etc/init.d/ser2net stop && sleep 0.5 && /etc/init.d/ser2net start`
> Using the smaller _sleep_ values I was getting the error as before.
> I've tried to add a similar pause between _stop_ and _start_ in the init.d script however that was ignored. Do I need to do something special to update init.d script?

I'm not really much of an expert in systemd and init scripts, but I
would expect that after sending a sigintr it would wait until the
process went away.  So I really don't know how to fix this properly.
Sometimes when interacting with serial ports it can take some time to
clean things up.  If you have a lot of entries it can take many seconds.

-corey

**Comment by cminyard** [comment]
Any progress on this?

**Comment by evilgreen** [comment]
I created a service file and not using `/etc/init.d/ser2net` anymore.
Generally speaking everything is fine, however I'm getting this message when I run `systemctl status ser2net` after the earlier `systemctl restart ser2net`:
````
Sep 08 23:57:15 cubox systemd[1]: Starting Serial port to network proxy...
Sep 08 23:57:15 cubox ser2net[26185]: ser2net startup
Sep 08 23:57:15 cubox systemd[1]: ser2net.service: Can't open PID file /run/ser2net.pid (yet?) after start: No such file or director
Sep 08 23:57:15 cubox systemd[1]: Started Serial port to network proxy.
````
Looks like another timing issue?

**Comment by cminyard** [comment]
On Tue, Sep 08, 2020 at 02:19:15PM -0700, AndrewZ wrote:
> I created a service file and not using `/etc/init.d/ser2net` anymore.
> Generally speaking everything is fine, however I'm getting this message when I run `systemctl status ser2net` after the earlier `systemctl restart ser2net`:
> ````
> Sep 08 23:57:15 cubox systemd[1]: Starting Serial port to network proxy...
> Sep 08 23:57:15 cubox ser2net[26185]: ser2net startup
> Sep 08 23:57:15 cubox systemd[1]: ser2net.service: Can't open PID file /run/ser2net.pid (yet?) after start: No such file or director
> Sep 08 23:57:15 cubox systemd[1]: Started Serial port to network proxy.
> ````
> Looks like another timing issue?

Maybe.  If ser2net is started with '-P /run/ser2net.pid', then it looks
like a timing error.

-corey

**Comment by cminyard** [comment]
I haven't heard anything on this, so I'll close for now.  If there's something I can do, please re-open.
