### ISSUE TITLE
Syntax Change 3.x -> 4.0

### ISSUE THREAD

**Issue by zombielinux** [cminyard/ser2net#35]
Many home automation projects use an older version of the ser2net syntax to forward serial ports over the network.

For example, zigbee2mqtt uses ```20108:raw:0:/dev/ttyACM0:115200 8DATABITS NONE 1STOPBIT``` for their example here: https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

With that syntax going away (or already gone, not sure based on documentation), I'm trying to find an updated syntax. 

As such, I have the following yaml:

```
%YAML 1.1
---
define: &conbee "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00"
connection: &con01
  accepter: tcp,2001
  connector: serialdev,*(conbee),115200n81,kickolduser=true,local
  enable: on
```

In my case, I get the error: "Error while opening socket" on the remote end. I suspect the issue is with the "raw" state set in the old syntax. I haven't found a matching syntax in either ser2net or ser2net.yaml's man file. 

Is there any advice from the devs/users?

**Comment by cminyard** [comment]
On Sun, Oct 25, 2020 at 12:51:57PM -0700, William Sutton wrote:
> Many home automation projects use an older version of the ser2net syntax to forward serial ports over the network.
> 
> For example, zigbee2mqtt uses ```20108:raw:0:/dev/ttyACM0:115200 8DATABITS NONE 1STOPBIT``` for their example here: https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html
> 
> With that syntax going away (or already gone, not sure based on documentation), I'm trying to find an updated syntax. 

It's still there.  I got a lot of complaints from people trying to use
names with ":" in them, and doing very complex lines with lots of
options.  Plus it wasn't in a standard form.  But it will probably go
away in 5.x, if/when that ever happens.

> 
> As such, I have the following yaml:

Try the following:

%YAML 1.1
---
define: &conbee "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00"
connection: &con01
  accepter: tcp,2001
  connector: serialdev,*(conbee),115200n81,local
  enable: on
  options:
    kickolduser: true

This worked ok for me (with a different serial port).  kickolduser is a
ser2net function, things that go onto the accepter and connector lines
are gensio functions.

-corey

**Comment by zombielinux** [comment]
Nope, no joy. 

Even tried defining conbee as `/dev/ttyACM0` which is where it actually shows up. 

Perhaps zigbee2mqtt is doing something funky?

**Comment by cminyard** [comment]
On Sun, Oct 25, 2020 at 02:41:53PM -0700, William Sutton wrote:
> Nope, no joy. 
> 
> Even tried defining conbee as `/dev/ttyACM0` which is where it actually shows up. 
> 
> Perhaps zigbee2mqtt is doing something funky?

No, I was able to start with a copy-paste of your entry and moving
kickolduser.  It won't work since I don't have that device, but it won't
see that until you try to use it.

What version of ser2net are you using?  Can you try the end of the git
tree?

-corey

**Comment by zombielinux** [comment]
I'm using ser2net 4.0 (from the arch repos)

I tried pulling from the git tree, but it fails on make.

```
  CC       controller.o
In file included from controller.c:37:
ser2net.h:31:10: fatal error: gensio/gensio_list.h: No such file or directory
   31 | #include <gensio/gensio_list.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```

I thought it might have been an issue with the gensio package, so I uninstalled it and tried to build it from source as well. It failed on make as well with: 

```
make[2]: Entering directory '/home/alarm/gensio/lib'
  CC       gensio.lo
  CC       gensio_osops.lo
  CC       gensio_net.lo
  CC       gensio_udp.lo
  CC       gensio_stdio.lo
  CC       sergensio.lo
  CC       sergensio_telnet.lo
  CC       sergensio_serialdev.lo
  CC       uucplock.lo
  CC       gensio_selector.lo
  CC       gensio_ssl.lo
  CC       gensio_base.lo
  CC       gensio_filter_ssl.lo
  CC       gensio_filter_telnet.lo
  CC       telnet.lo
  CC       buffer.lo
  CC       gensio_ll_fd.lo
  CC       gensio_ll_gensio.lo
  CC       gensio_acc.lo
  CC       gensio_acc_gensio.lo
  CC       gensio_ll_ipmisol.lo
  CC       sergensio_ipmisol.lo
  CC       utils.lo
  CC       selector.lo
  CC       gensio_sctp.lo
gensio_sctp.c:1095:1: error: conflicting types for 'sctp_gensio_alloc'
 1095 | sctp_gensio_alloc(struct gensio_addr *iai, const char * const args[],
      | ^~~~~~~~~~~~~~~~~
```

**Comment by zombielinux** [comment]
Ok, I wasn't able to build from the latest git, nor the latest RC's but I was able to build 4.2.3 and gensio 2.1.7, and the same problem persists.

**Comment by cminyard** [comment]
On Mon, Oct 26, 2020 at 10:31:15AM -0700, William Sutton wrote:
> Ok, I wasn't able to build from the latest git, nor the latest RC's but I was able to build 4.2.3 and gensio 2.1.7, and the same problem persists. 

Building it all is a bit of a pain, but I'm not sure what is going
wrong.  It sounds like some stuff got left around, like the include
files were not removed properly.

Anyway, I installed arch linux in an LXC container and I was able to get
it working without an issue.

%YAML 1.1
---
#define: &conbee "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00"
define: &conbee "/home/ttyEcho0"
connection: &con01
  accepter: tcp,2001
  connector: serialdev,*(conbee),115200n81,local
  enable: on
  options:
    kickolduser: true


[root@arch ~]# ser2net -d -c t1.yaml

And in another window:

[root@arch /]# gensiot tcp,localhost,2001

So the 4.0 version should work.

I shouldn't have anything to do with "raw", basically if you don't put
telnet in the accepter you get raw.

I'm not sure how you are connecting.  Can you try with gensiot or
telnet?

-corey

**Comment by zombielinux** [comment]
Hmmm. 

```
[alarm@deconz-host gensio]$ gensiot tcp,127.0.0.1,2001
Device open failure: Remote end closed connection
```

**Comment by cminyard** [comment]
On Mon, Oct 26, 2020 at 11:06:24AM -0700, William Sutton wrote:
> Hmmm. 
> 
> ```
> [alarm@deconz-host gensio]$ gensiot tcp,127.0.0.1,2001
> Device open failure: Remote end closed connection

Ah, more information.  ser2net was unable to open the device.  The error
is strange, though.  If I modify the config file to point to something
that doesn't exist, I get:

[root@arch /]# gensiot tcp,localhost,2001
Device open failure: Value or file not found

which is what you would expect.  I think what that is telling you is
that it can't open the device because the remote end:

/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00

closed the connection.

I don't know what that means for that device, exactly.  In *nix systems,
that generally means that a read returns "0" bytes.  But that's where
the problem appears to be.

If you have a local program that can open the device you might try that.
Even doing:

  cat </dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00

might tell you something.

-corey

**Comment by zombielinux** [comment]
``` cat </dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00```

Returns some binary data, but not immediately after connecting. Is there a timeout? Or a way to override that need for a read?

**Comment by zombielinux** [comment]
admin console shows 
```
-> showport
port: con01
  accepter: tcp,2001
  enable state: on
  timeout: 0
  device: serialdev,/dev/ttyACM0,115200n81,local
  device config: 115200N81,CLOCAL
  tcp to device state: unconnected
  device to tcp state: unconnected
  bytes read from device: 0
  bytes written to device: 0
```
So it definitely looks like ser2net is having issues connecting to the serial device.

**Comment by cminyard** [comment]
On Mon, Oct 26, 2020 at 11:32:06AM -0700, William Sutton wrote:
> ``` cat </dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00```
> 
> Returns some binary data, but not immediately after connecting. Is there a timeout?

There's no timeout by default, and you would get a different message for
that.

> Or a way to override that need for a read?

Well, ser2net wouldn't be very useful if it didn't read from the port.

gensiot uses the same base code as ser2net uses to talk to the port.
Can you try:

  gensiot 'serialdev,/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995807-if00,115200n81,local'

Maybe we can get some more information.

-corey

**Comment by zombielinux** [comment]
```Could not open serialdev,/dev/ttyACM0,115200n81,local: Remote end closed connection```

Somehow, not helpful...

The question is why it would be closing the connection.

**Comment by zombielinux** [comment]
Well, I've been diving through this, and I'm shocked I didn't find it before. 

https://github.com/Koenkk/zigbee2mqtt/issues/3862

There's apparently issues with this exact thing I'm trying to do. 

I'll close this for now and crosslink it there to show what we've troubleshot so far.

Thanks for your help!

**Comment by cminyard** [comment]
On Mon, Oct 26, 2020 at 01:01:39PM -0700, William Sutton wrote:
> Well, I've been diving through this, and I'm shocked I didn't find it before. 
> 
> https://github.com/Koenkk/zigbee2mqtt/issues/3862
> 
> There's apparently issues with this exact thing I'm trying to do. 
> 
> I'll close this for now and crosslink it there to show what we've troubleshot so far.

Ok, thanks.  I was going to suggest using trying ser2net 3.5.x, but
obviously it has a problem, too.

> 
> Thanks for your help!

Thanks for reporting issues.  That's how things get fixed: :-).

-corey
