### ISSUE TITLE
telnet-brk-on-sync man page issues

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/ser2net#38]
Hi,

in the ser2net.yaml man page, telnet-brk-on-sync is spelled telnet_brk_on_sync, and the sentence "If  a  telnet is received" is probably missing the word "sync".

Greetings
Marc

**Comment by cminyard** [comment]
On Wed, Jan 20, 2021 at 10:08:25AM -0800, Zugschlus wrote:
> Hi,
> 
> in the ser2net.yaml man page, telnet-brk-on-sync is spelled telnet_brk_on_sync, and the sentence "If  a  telnet is received" is probably missing the word "sync".
> 

Thanks, got it.
