### ISSUE TITLE
INSTALL says use ./configure, but it does not exist!

### ISSUE THREAD

**Issue by ke5stl** [cminyard/ser2net#40]
subject says it all.  this is in 4.3.2

:(

**Comment by cminyard** [comment]
On Sat, Jan 30, 2021 at 08:22:39PM -0800, ke5stl wrote:
> subject says it all.  this is in 4.3.2

From README.rst:

This is a normal autoconf system, nothing special.  Note that if you
get this directly from git, you won't have the build infrastructure
included.  There is a script named "reconf" in the main directory
that will create it for you.

**Comment by pbelbin** [comment]
Ah.  Interesting.  Yeah, I did not look at the README for info on building.  Might be nice to add a mention in the INSTALL docs too, since that's what's talking about building the code from scratch.

Thank you for the pointer!

**Comment by ke5stl** [comment]
Ah.  Thank you for the pointer.  Might be good to add a mention in the INSTALL too.

:)
