### ISSUE TITLE
warning if old format configuration file is read

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/ser2net#42]
Hi,

please consider printing a warning if an old format configuration file is encountered. This will motivate users of the program to migrate to the new yaml format and makes it also easier for distribution packages.

Greetings
Marc

**Comment by evilgreen** [comment]
The warning is already there:
````
$ sudo /usr/local/sbin/ser2net -c /etc/ser2net.conf 
Unable to start mdns: Operation not supported
ser2net:WARNING: Using old config file format, this will go away
soon.  Please switch to the yaml-based format.
````

**Comment by cminyard** [comment]
On Sat, Feb 06, 2021 at 10:13:46AM -0800, AndrewZ wrote:
> The warning is already there:
> ````
> $ sudo /usr/local/sbin/ser2net -c /etc/ser2net.conf 
> Unable to start mdns: Operation not supported
> ser2net:WARNING: Using old config file format, this will go away
> soon.  Please switch to the yaml-based format.
> ````

Well, it was just added a day ago, per Marc's request :-).

-corey
