### ISSUE TITLE
Unable to start mdns: Operation not supported

### ISSUE THREAD

**Issue by jfrogg** [cminyard/ser2net#43]
ser2net version 4.3.3

Starting the program always gives an error: `Unable to start mdns: Operation not supported`
configuration file is in the new format, tried using in the connection
```
options:
        mdns: false
```
but that does not help

**Comment by cminyard** [comment]
Are you still having this issue?  I can't see how that would happen if you have mdns disabled.

**Comment by evilgreen** [comment]
Yes, but that is obviously a cosmetic issue.

````
Mar 31 20:49:11 cubox systemd[1]: Starting Serial port to network proxy...
Mar 31 20:49:11 cubox ser2net[31531]: Unable to start mdns: Operation not supported
Mar 31 20:49:11 cubox ser2net[31531]: ser2net startup
Mar 31 20:49:11 cubox systemd[1]: ser2net.service: Can't open PID file /run/ser2net.pid (yet?) after start: No such file or director
Mar 31 20:49:11 cubox systemd[1]: Started Serial port to network proxy.
````

**Comment by konradgraefe** [comment]
I have the same issue due to gensio being compiled without `HAVE_AVAHI`.

`main()` calls `init_dataxfer()` before reading the config file. That calls `gensio_alloc_mdns()` which returns `GE_NOTSUP`.

**Comment by westfa** [comment]
> I have the same issue due to gensio being compiled without `HAVE_AVAHI`.
> 
> `main()` calls `init_dataxfer()` before reading the config file. That calls `gensio_alloc_mdns()` which returns `GE_NOTSUP`.

Hi,

I'm not very familiar with installing Linux stuff without apt-get install, but I managed to compile and install gensio 2.2.8 and ser2net 4.3.1 on a Raspberry Pi 3 b+ with raspberry pi os lite running. However, when I start ser2net, I get:
_Unable to start mdns: Operation not supported
Could not initialize defaults: 'Value or file not found'_

In the quoted post, it is mentioned that this is due to gensio being compiled without HAVE_AVAHI. Can someone instruct me on how to fix this? As for the second error message, I'll cross that bridge when I get there :), unless someone knows what that's about?

**Comment by westfa** [comment]
> > I have the same issue due to gensio being compiled without `HAVE_AVAHI`.
> > `main()` calls `init_dataxfer()` before reading the config file. That calls `gensio_alloc_mdns()` which returns `GE_NOTSUP`.
> 
> Hi,
> 
> I'm not very familiar with installing Linux stuff without apt-get install, but I managed to compile and install gensio 2.2.8 and ser2net 4.3.3 on a Raspberry Pi 3 b+ with raspberry pi os lite running. However, when I start ser2net, I get:
> **_Unable to start mdns: Operation not supported_**
> 
> In the quoted post, it is mentioned that this is due to gensio being compiled without HAVE_AVAHI. Can someone instruct me on how to fix this?

Never mind. Figured it out! I installed libavahi-client-dev and recompiled gensio.

**Comment by cminyard** [comment]
I have modified ser2net to not report mdns startup failure if gensio doesn't support it.  It will log if mdns is enabled on a port and mdns startup failed, so you'll only get the warning if you try to use it.
