### ISSUE TITLE
/etc/ser2net/ser2net.yaml not used by default

### ISSUE THREAD

**Issue by evilgreen** [cminyard/ser2net#44]
Using freshly compiled ser2net version 4.3.3

I read this as `/etc/ser2net/ser2net.yaml` is used by default:
```
/usr/local/sbin/ser2net: Valid parameters are:
  -c <config file> - use a config file besides /etc/ser2net/ser2net.yaml
```
However this is not what I see on my computer:
```
$ sudo /usr/local/sbin/ser2net 
Unable to start mdns: Operation not supported
~/src/ser2net-4.3.3$ sudo ps aux | grep ser2net
xxxxxx  13451  0.0  0.0   6720   520 pts/0    S+   20:31   0:00 grep --color=auto ser2net

$ sudo /usr/local/sbin/ser2net -c /etc/ser2net/ser2net.yaml 
Unable to start mdns: Operation not supported
~/src/ser2net-4.3.3$ sudo ps aux | grep ser2net
root     13464  0.0  0.0   4360   304 ?        S    20:33   0:00 /usr/local/sbin/ser2net -c /etc/ser2net/ser2net.yaml
xxxxxx  13466  0.0  0.0   6720   556 pts/0    S+   20:33   0:00 grep --color=auto ser2net
```

The program starts only if configuration file name provided explicitly with -c option.

**Comment by cminyard** [comment]
On Sat, Feb 06, 2021 at 09:36:17AM -0800, AndrewZ wrote:
> Using freshly compiled ser2net version 4.3.3
> 
> I read this as `/etc/ser2net/ser2net.yaml` is used by default:
> ```
> /usr/local/sbin/ser2net: Valid parameters are:
>   -c <config file> - use a config file besides /etc/ser2net/ser2net.yaml

This is a unix-ism/autoconf-ism that gets everyone.

I'm assuming you just did "./configure" without any options.

Unless you have explicitly overridden it it, it will use
/usr/local/etc/ser2net/ser2net.yaml, because the default prefix is
/usr/local.

Even if you set --prefix=/usr, it will install it in /usr/etc/...

You have to explicitly override it with

  --sysconfdir=/etc

when you run configure.  It's that way for pretty much any autoconf
build.

But if you are installing in /usr/local, it's generally best to put your
configuration in /usr/local/etc, to keep things consistent.

-corey

**Comment by evilgreen** [comment]
> But if you are installing in /usr/local, it's generally best to put your configuration in /usr/local/etc, to keep things consistent.

the binary was installed to /usr/local/sbin/ automatically, so that was unintentional from my side. I already moved configuration folder to `/usr/local/etc` and everything is OK. Thank you for the explanation.
