### ISSUE TITLE
proper translation between old and new config format

### ISSUE THREAD

**Issue by evilgreen** [cminyard/ser2net#45]
this is what I have in the old style configuration file `/etc/ser2net.conf`:
`192.168.1.6,4001:raw:600:/dev/usbcom1:115200 8DATABITS NONE 1STOPBIT NOBREAK banner1`

with this configuration I can connect from the remote host and work with a com port.

Now I'm trying to do the same with the new style configuration in `/etc/ser2net/ser2net.yaml`:
````
connection: &con1
    accepter: tcp,192.168.1.6,4001
    connector: serialdev,/dev/usbcom1,115200n81,local
````
My terminal connects as before, then nothing.

**Comment by cminyard** [comment]
On Sat, Feb 06, 2021 at 09:55:56AM -0800, AndrewZ wrote:
> this is what I have in the old style configuration file `/etc/ser2net.conf`:
> `192.168.1.6,4001:raw:600:/dev/usbcom1:115200 8DATABITS NONE 1STOPBIT NOBREAK banner1`
> 
> with this configuration I can connect from the remote host and work with a com port.
> 
> Now I'm trying to do the same with the new style configuration in `/etc/ser2net/ser2net.yaml`:
> ````
> connection: &con1
>     accepter: tcp,192.168.1.6,4001
>     connector: serialdev,/dev/usbcom1,115200n81,local
> ````
> My terminal connects as before, then nothing.

That's a little bit different.  You have local enabled, which won't use
the modem control lines.  If the thing on the other end of the serial
port requires modem control lines to work, that might be an issue.

You also don't have the banner, which would tell if if the
ser2net->client direction is working.

To be 100% the same, you can add "nobreak" to the connector, but I can't
imagine that would make a difference.

But I don't see anything wrong.  You can replace the connecter with
"echo", which will simply echo back anything that comes in, which would
tell you if the accepter part is working.

-corey

**Comment by evilgreen** [comment]
> To be 100% the same, you can add "nobreak" to the connector, but I can't imagine that would make a difference.

That is the key! Adding "nobreak" bring things back to normal. That keyword is undocumented(?) in the new config, so I didn't use it.

Strange thing discovered with TCP connection (but not with telnet). Here is how I see the banner I added. Needless to say that it was defined in the configuration file without that garbage:

`^JCCAA@@This is a banner for port con1(telnet,tcp,192.168.1.6,4001)^M`
or
`1(telnet,tcp,192.168.1.6,4001)^M^JCCAA@@This is a banner for port con`

**Comment by cminyard** [comment]
Well, socat doesn't do telnet.  If you don't use "telnet" in the accepter, it should work fine.

If you need telnet, gensiot can do it.
