### ISSUE TITLE
Unable to establish ckermit connection with ser2net 4.3

### ISSUE THREAD

**Issue by cotardp** [cminyard/ser2net#57]
Hello,

With ser2net 4.3 I cannot establish a kermit connection anymore.
According to the page https://github.com/cminyard/ser2net kermit should be working with ser2net.
However, I found no working configuration to make it work.

The following configuration is done on the server:
```
%YAML 1.1
---
define: &confver 1.0

connection: &my-board
  accepter: telnet(rfc2217),15010
  connector: serialdev,
    /dev/ttySER1-3,
    115200n81,
    local
  options:
   max-connections: 5
```

1. When using telnet, the connection is established correctly:
```
$ telnet localhost 15010
Trying ::1...
Connected to localhost.
Escape character is '^]'.
```

2. When using ckermit, the connection fails as follow:
```
$ kermit -c -j localhost:15010
 DNS Lookup...  Trying 127.0.0.1...  Reverse DNS Lookup... (OK)
 localhost connected on port 15010
 Negotiations................................
*************************
The Telnet server is not sending required responses.

?Telnet waiting for response to DO KERMIT

You can continue to wait or you can cancel with Ctrl-C.
In case the Telnet server never responds as required,
you can try connecting to this host with TELNET /NOWAIT.
Use SET HINTS OFF to suppress further hints.
*************************
..........................................................................................
?Telnet Protocol Timeout - connection closed
?Telnet waiting for response to DO KERMIT
?Telnet Option negotiation error.
can't open host connection
```

3. Note that using ckermit on the control port (15000) does work:
```
$ kermit -c -j localhost:15000
 DNS Lookup...  Trying 127.0.0.1...  Reverse DNS Lookup... (OK)
 localhost connected on port 15000
Connecting to host localhost:15000
 Escape character: Ctrl-\ (ASCII 28, FS): enabled
Type the escape character followed by C to get back,
or followed by ? to see other options.
----------------------------------------------------
->
```

I am using the following environment:
- Debian 11.1
- ser2net 4.3.3-1
- ckermit 305~alpha02-1

**Comment by cminyard** [comment]
On Thu, Oct 21, 2021 at 09:36:28AM -0700, cotardp wrote:
> Hi,
> 
> I did use:
> ***@***.***
> ***@***.***
> 
> Compiled from a Debian 11 chroot, and transfered to my system.
> 
> Using telnet:
> ```
> telnet localhost 15010
> Trying localhost...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> ```
> As you see, connection gets closed and I cannot reconnect after.

Hmm, that's really strange.  Can you change your accepter line to:

  accepter: telnet(rfc2217),trace(dir=both,file=tracefile),tcp,15010

and send me the contents of tracefile?

Also, what telnet version are you using?

> 
> Using kermit:
> ```
> kermit -c -j localhost:1510
>  DNS Lookup...  Trying 127.0.0.1...  Reverse DNS Lookup... (OK)
>  lab-test connected on port 1510
>  Negotiations...
> ?Connection closed by peer.
> ?Telnet Option negotiation error.
> Connecting to host localhost:1510
>  Escape character: Ctrl-\ (ASCII 28, FS): enabled
> Type the escape character followed by C to get back,
> or followed by ? to see other options.
> 
> ?Connection closed by peer.
> ?Carrier required but not detected.
> ***********************************
>  Hint: To CONNECT to a serial device that
>  is not presenting the Carrier Detect signal,
>  first tell C-Kermit to:
> 
>    SET CARRIER-WATCH OFF
> 
> ***********************************
> 
> C-Kermit 9.0.305 OPEN SOURCE: Alpha.02, 19 Sep 2020, for Linux+SSL+KRB5 (64-bit)
>  Copyright (C) 1985, 2020,
>   Trustees of Columbia University in the City of New York.
> Type ? or HELP for help.
> (/tmp/) C-Kermit>
> ```

If your hardware is not providing carrier, then it's not going to work
without doing the "set carrier watch off".

If it is, it appears that ser2net is doing the right thing to provide
carrier signals over rfc2217.

So I have two serial ports on my machine connected with a null modem.
I hook ser2net to one end.  If the other end is unconnected, connecting
with ser2net with kermit results in the "set carrier watch off" thing.
If I open the other end with gensiot and connect, everything works fine.

I did find a bug in kermit (C-Kermit 9.0.305), if you do:
   kermit -c -b 115200 -j localhost:15010
then it sets the speed to 115200, then it sends another message setting
the speed to 38400.  You have to do another "set speed 115200" to make
it work.

> 
> About script, I will look at gensio python interface to see if it can fit my need.

Yeah, the trouble is that you will be programming, not scripting.  But
if you are up for that, it's a lot more powerful.

There are some examples in the gensio examples directory, but the aren't
great.  All the documentation is in man pages.  More docs need to be
written, but that takes time :-(.

-corey
