### ISSUE TITLE
ser2net version 3.5.3 crashed when reconnection occured from client side.

### ISSUE THREAD

**Issue by jaechulcho** [cminyard/ser2net#58]
Hi. thank you for wonderful ser2net.

I am using ser2net 3.4.3( committed on29 Jun 2020 4f073e6)

as title, it is crashed when reconnection occurred from client side.

1st connection is ok.
but when 2nd connection, the ser2net(v3.5.3) is crashed.

I see the it is not release version but, in previous version(3.5.2), because some data are dropped, i moved 3.5.3.

when the code executed with gdb, the double free occurred in dataxfer.c at 2025 line when 2nd connection establish.

thank you.

**Comment by cminyard** [comment]
On Tue, Nov 02, 2021 at 10:45:35PM -0700, jaechulcho wrote:
> Hi. thank you for wonderful ser2net.
> 
> I am using ser2net 3.4.3( committed on29 Jun 2020 4f073e6)
> 
> as title, it is crashed when reconnection occurred from client side.
> 
> 1st connection is ok.
> but when 2nd connection, the ser2net(v3.5.3) is crashed.
> 
> I see the it is not release version but, in previous version(3.5.2), because some data are dropped, i moved 3.5.3.
> 
> when the code executed with gdb, the double free occurred in dataxfer.c at 2025 line when 2nd connection establish.
> 

Can you try the following patch?

diff --git a/dataxfer.c b/dataxfer.c
index a87a710..0b74eef 100644
--- a/dataxfer.c
+++ b/dataxfer.c
@@ -3093,8 +3093,10 @@ netcon_finish_shutdown(net_info_t *netcon)
        netcon->banner = NULL;
     }
 
-    if (netcon->working_telnet_cmds)
+    if (netcon->working_telnet_cmds) {
        free(netcon->working_telnet_cmds);
+       netcon->working_telnet_cmds = NULL;
+    }
 
     if (num_connected_net(port, true) == 0) {
        start_shutdown_port(port, "All network connections free");


Thanks,

-corey

**Comment by jaechulcho** [comment]
> On Tue, Nov 02, 2021 at 10:45:35PM -0700, jaechulcho wrote: Hi. thank you for wonderful ser2net. I am using ser2net 3.4.3( committed on29 Jun 2020 [4f073e6](https://github.com/cminyard/ser2net/commit/4f073e69297f950853404907fdcc88fac1f84124)) as title, it is crashed when reconnection occurred from client side. 1st connection is ok. but when 2nd connection, the ser2net(v3.5.3) is crashed. I see the it is not release version but, in previous version(3.5.2), because some data are dropped, i moved 3.5.3. when the code executed with gdb, the double free occurred in dataxfer.c at 2025 line when 2nd connection establish.
> Can you try the following patch? diff --git a/dataxfer.c b/dataxfer.c index a87a710..0b74eef 100644 --- a/dataxfer.c +++ b/dataxfer.c @@ -3093,8 +3093,10 @@ netcon_finish_shutdown(net_info_t *netcon) netcon->banner = NULL; } - if (netcon->working_telnet_cmds) + if (netcon->working_telnet_cmds) { free(netcon->working_telnet_cmds); + netcon->working_telnet_cmds = NULL; + } if (num_connected_net(port, true) == 0) { start_shutdown_port(port, "All network connections free"); Thanks,
> […](#)
> -corey
> thank you. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #58

Thank you.

it works.

Thnak you.
