### ISSUE TITLE
wrong configuration? or problems with sending more than 6000 characters from tcp over the serial? 

### ISSUE THREAD

**Issue by familazzo** [cminyard/ser2net#59]
Hi. thank you for wonderful ser2net.
I would like to know if the problems I'm having on ser2net are related to a wrong configuration, or to a bug:
The ser2net works (writing from tcp to usb0), under 5000 characters. If this threshold is exceeded, ser2net does not update the remaining data to be sent.
Do you help me?

**Comment by cminyard** [comment]
On Wed, Nov 03, 2021 at 05:29:21AM -0700, familazzo wrote:
> Hi. thank you for wonderful ser2net.
> I would like to know if the problems I'm having on ser2net are related to a wrong configuration, or to a bug:
> The ser2net works (writing from tcp to usb0), under 5000 characters. If this threshold is exceeded, ser2net does not update the remaining data to be sent.
> Do you help me? 

Well, I'll need some more information:

What version of ser2net?  Have you tried the most current version?

What is your ser2net configuration?  What hardware are you using?

-corey

**Comment by familazzo** [comment]
Hi Corey,

Maybe I found the point where the connection to the serial is closed.
I commented out the gensio callback which invokes the "accept_read_disabled function"(port.c - line 891), and the print is completed.
I understand that the function called by the callback(accept_read_disabled) is called before the handle_dev_write_ready function is executed.

Unfortunately now I have another problem, the serial is never closed (even if the print is completed).

Thanks in advance :-).

**Comment by cminyard** [comment]
On Wed, Nov 03, 2021 at 09:03:51AM -0700, familazzo wrote:
> 
> Hello
> I am trying to print to a raspberry USB connected printer.
> 
> | WINDOWS | -> | TCP | -> | RASPBERRY | -> | Ser2Net | -> | USB0 | -> | Printer |
> 
> .conf:
> 1041: raw: 0: / dev / ttyUSB0: 9600 8DATABITS NONE 1STOPBIT XONXOFF banner LOCAL -RTSCTS NOBREAK tw = tw1

I assume all those spaces are not in the actual config file.

You definitely don't want the banner.  That's going to send things back
to windows, which may confuse it.

Are you sure the serial parameters are correct?  Particularly XONXOFF
and -RTSCTS.  Do you really want to disable hardware flow control and
enable software flow control?  Unless the printer actually does this, it
may be sending stop characters which will, of course, stop things.  You
need to know how the printer expects to do flow control, since it will
be necessary.

If the data is only one-way to the printer, you probably want to use
rawlp, not raw, for the type.  If the data flows both directions, then
raw is correct.

-corey

**Comment by cminyard** [comment]
On Thu, Nov 04, 2021 at 10:11:12AM -0700, familazzo wrote:
> Hi Corey,
> 
> Maybe I found the point where the connection to the serial is closed.
> I commented out the gensio callback which invokes the "accept_read_disabled function"(port.c - line 891), and the print is completed.
> I understand that the function called by the callback(accept_read_disabled) is called before the handle_dev_write_ready function is executed.

No, you can't do that.  Things won't get closed properly.

The serial port shutdown happens (well, starts to happen) in
start_shutdown_port_io().  But I don't think that's the issue.

> 
> Unfortunately now I have another problem, the serial is never closed (even if the print is completed).

I'm not sure I follow.  If the TCP connection closes, it should close
the serial port.  Otherwise it stays open.  I'm not sure what you mean.

The only way that something on the serial port can know if the other end
has shut down is the modem control like (DCD, really).  I believe you
had "local" set in your config, which disabled modem control.

I'm going to need more information to debug this.  I don't know what you
mean by "the serial is never closed."

-corey

**Comment by familazzo** [comment]
Hi Corey,

> No, you can't do that.  Things won't get closed properly

Mine was just a test to understand how ser2net works.Nothing else.

I can assume that the ser2net closes all connections (TCP - USB Serial) as soon as all data has arrived from Windows (via TCP)
Unfortunately the serial is much slower, and I would have to wait for all data to be sent to the serial before it closes.

> The only way that something on the serial port can know if the other end
> has shut down is the modem control like (DCD, really).  I believe you
> had "local" set in your config, which disabled modem control.

The parameter is present in the ser2net.conf

Thanks

**Comment by cminyard** [comment]
On Sat, Nov 06, 2021 at 01:07:41AM -0700, familazzo wrote:
> Hi Corey,
> 
> > No, you can't do that.  Things won't get closed properly
> 
> Mine was just a test to understand how ser2net works.Nothing else.
> 
> I can assume that the ser2net closes all connections (TCP - USB Serial) as soon as all data has arrived from Windows (via TCP)

No, ser2net does not close any connections on it's own.  It has no way
to know that all the data has arrived.  The only way it knows is if
Windows disconnects.

> Unfortunately the serial is much slower, and I would have to wait for all data to be sent to the serial before it closes.

If Windows disconnects, ser2net will wait until all the data has cleared
out before it shuts down the connection to the serial port.

> 
> > The only way that something on the serial port can know if the other end
> > has shut down is the modem control like (DCD, really).  I believe you
> > had "local" set in your config, which disabled modem control.
> 
> The parameter is present in the ser2net.conf

Should it be?  Should you be using xonxoff?  Should you turn off rtscts?
It all depends on the hardware.  I would guess that a printer hooked up
would not use xonxoff, would use rtscts, and might need to have local
removed.

You should certainly remove banner, if you haven't already done so.

-corey

**Comment by familazzo** [comment]
Hi Corey,

The print stops due to a read error returned by gensio (26 -> GE_REMCLOSE) 
The handle_net_td_read (dataxfer.c) function reads this error and executes the shutdown of the ports
Maybe the windows data block does not arrive for a period of time, and this error occurs. 

Should I wait for the device ready event to be returned?

Fabio

**Comment by cminyard** [comment]
On Mon, Nov 08, 2021 at 06:41:42AM -0800, familazzo wrote:
> Hi Corey,
> 
> The print stops due to a read error returned by gensio (26 -> GE_REMCLOSE) 
> The handle_net_td_read (dataxfer.c) function reads this error and executes the shutdown of the ports
> Maybe the windows data block does not arrive for a period of time, and this error occurs. 

I don't know.  It means that Windows is closing the connection.  The
question is where the data is lost.  Some ideas:

* Between Windows and ser2net
* Inside ser2net (it drops the data on close)
* Inside the operating system
* Between ser2net and the printer

There are counters in ser2net that counts how much data ser2net receives
and sends.  You can use those to narrow down where the data is lost.

The gensios involved do have a timer on shutdown for serialdev that
gives up after a certain time if all the data has not been sent.
Perhaps that timer is too short?

> 
> Should I wait for the device ready event to be returned?

Shouldn't be necessary, I don't think.

-corey

**Comment by familazzo** [comment]
Hi Corey,

As I mentioned, the error that is generated by the GENSIO library (GE_REMCLOSE), forces the shutdown of the ports (method handle_net_fd_read, line 549 from dataxfer.c)
I am trying to handle the error, by first writing to the buffer (function gbuf_write line 588),
inserting a sleep before closing the print, everything works.

In your opinion, how can I know when the serial finishes printing?

Thanks

**Comment by cminyard** [comment]
On Nov 10, 2021 3:39 AM, familazzo ***@***.***> wrote:
Hi Corey,
As I mentioned, the error that is generated by the GENSIO library (GE_REMCLOSE), forces the shutdown of the ports (method handle_net_fd_read, line 549 from dataxfer.c)
I am trying to handle the error, by first writing to the buffer (function gbuf_write line 588),
inserting a sleep before closing the print, everything works.
In your opinion, how can I know when the serial finishes printing?Hmm, that's interesting.  The way it's supposed to work is that when it gets data from the network, it writes to the device.  If not all the data was written, it turns off the read handling and sets the state to PORT_WAITING_OUTPUT_CLEAR.  In that state, it ignores any read callbacks.  Once some data is written, it changes the state back to normal and re-enables the read handle.So you shouldn't get a read callback if there is data in the net_to_dev buffer to send to the device.How long is the sleep?  If you just add a sleep and nothing else and it works, that means the data is in the OS buffers.  The gensio library is not supposed to finish the close of the device until all the data is written, but there are timers and if it takes too long, it will close the connection.In the gensio library, in lib/sergensio_serialdev.c, in the function sterm_wait_close_drain(), this timing is done.  There is a fixed value there, if it doesn't write any bytes in .5 seconds it will shut down the connection.  You can increase that value and see what happens.-corey
Thanks

**Comment by familazzo** [comment]
Hi Corey,

The sleep is parameterized with the amount of data received and to be written. I do a calculation similar to the one done in the recalc_port_chardelay function.
As soon as possible I will try to change the gensio times and maybe manage the PORT_WAITING_OUTPUT_CLEAR state.

Thanks
Fabio

**Comment by cminyard** [comment]
On Sat, Nov 13, 2021 at 01:04:38PM -0800, familazzo wrote:
> Hi Corey,
> 
> The sleep is parameterized with the amount of data received and to be written. I do a calculation similar to the one done in the recalc_port_chardelay function.
> As soon as possible I will try to change the gensio times and maybe manage the PORT_WAITING_OUTPUT_CLEAR state.

In the version of gensio I just released you can set the close times
(total and inter-character).  If that's the issue, that should really be
all you need.  Look in the gensio.5 man page under serialdev for info.

-corey
