### ISSUE TITLE
failed at first start but succesful restart

### ISSUE THREAD

**Issue by elschman** [cminyard/ser2net#60]
Hi I run this onb raspberryPi with newest raspbian.
the first start (after reboot) always failed with

Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 24 column 0
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 24 column 0
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 33 column 0
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 33 column 0

a restart runs successful

root@raspberrypi:/home/sff00009# service ser2net status
● ser2net.service - Serial port to network proxy
     Loaded: loaded (/lib/systemd/system/ser2net.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-12-07 18:23:39 CET; 6min ago
       Docs: man:ser2net(8)
   Main PID: 460 (ser2net)
      Tasks: 1 (limit: 1597)
        CPU: 88ms
     CGroup: /system.slice/ser2net.service
             └─460 /usr/sbin/ser2net -n -c /etc/ser2net.yaml -P /run/ser2net.pid

Dec 07 18:23:39 raspberrypi systemd[1]: Starting Serial port to network proxy...
Dec 07 18:23:39 raspberrypi systemd[1]: Started Serial port to network proxy.
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 24 column 0
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 24 column 0
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 33 column 0
Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 33 column 0
root@raspberrypi:/home/sff00009# service ser2net restart
root@raspberrypi:/home/sff00009# service ser2net status
● ser2net.service - Serial port to network proxy
     Loaded: loaded (/lib/systemd/system/ser2net.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-12-07 18:30:27 CET; 1s ago
       Docs: man:ser2net(8)
   Main PID: 1370 (ser2net)
      Tasks: 1 (limit: 1597)
        CPU: 26ms
     CGroup: /system.slice/ser2net.service
             └─1370 /usr/sbin/ser2net -n -c /etc/ser2net.yaml -P /run/ser2net.pid

root@raspberrypi:/home/sff00009# ser2net -v
ser2net version 4.3.3
root@raspberrypi:/home/sff00009# cat /etc/ser2net.yaml
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &tb001
  accepter: telnet(rfc2217),tcp,2001
  enable: on
  options:
    banner: *banner
    kickolduser: false
    telnet-brk-on-sync: true
    max-connections: 4
  connector: serialdev,/dev/portserver/tb001,115200n81,local

connection: &tb002
  accepter: telnet(rfc2217),tcp,2002
  enable: on
  options:
    banner: *banner
    kickolduser: false
    telnet-brk-on-sync: true
    max-connections: 4
  connector: serialdev,/dev/portserver/tb002,115200n81,local
root@raspberrypi:/home/sff00009# lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
root@raspberrypi:/home/sff00009# uname -a
Linux raspberrypi 5.10.82-v7+ #1497 SMP Fri Dec 3 16:26:57 GMT 2021 armv7l GNU/Linux
root@raspberrypi:/home/sff00009# apt info ser2net
Package: ser2net
Version: 4.3.3-1
Priority: optional
Section: utils
Maintainer: Marc Haber <ser2net@packages.debian.org>
Installed-Size: 197 kB
Pre-Depends: init-system-helpers (>= 1.58)
Depends: lsb-base (>= 3.0-6), libc6 (>= 2.4), libgensio0 (>= 2.2.4), libyaml-0-2
Suggests: telnet
Homepage: https://github.com/cminyard/ser2net
Download-Size: 78.9 kB
APT-Manual-Installed: yes
APT-Sources: http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
Description: Serial port to network proxy
 This daemon allows telnet and tcp sessions to be established with a
 host's serial ports. Combined with a terminal emulator, this can be a
 very simple means to configure network devices or other equipment with
 a serial port. This is remarkably similar to the reverse telnet
 feature of some Cisco routers.

root@raspberrypi:/home/sff00009#

**Comment by cminyard** [comment]
On Tue, Dec 07, 2021 at 09:39:13AM -0800, elschman wrote:
> Hi I run this onb raspberryPi with newest raspbian.
> the first start (after reboot) always failed with
> 
> Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 24 column 0
> Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 24 column 0
> Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 33 column 0
> Dec 07 18:23:40 raspberrypi ser2net[460]: Invalid port name/number: Invalid data to parameter on line 33 column 0

Yeah, this is a known issue.  ser2net starts before networking, and
calls to getaddrinfo (to convert the port names to IP addresses) fail.

So it's not really a ser2net issue, it's an OS issue.  See
https://github.com/cminyard/ser2net/issues/52 

-corey

**Comment by SjonHortensius** [comment]
@cminyard can you explain why ser2net doesn't quit with a sensible exit code when it is unable to parse the configuration? If it would quit after printing the error, this issue likely wouldn't exist

**Comment by cminyard** [comment]
On Mon, Jan 10, 2022 at 12:16:40PM -0800, SjonHortensius wrote:
> @cminyard can you explain why ser2net doesn't quit with a sensible exit code when it is unable to parse the configuration? If it would quit after printing the error, this issue likely wouldn't exist

It is able to parse the configuration file.  That's not where the error
lies.  The error lies in the conversion of "tcp,2001" to a binary
address.  When the network is down, that fails.

I agree that the error code isn't very helpful.  That error has been
changed in a more recent version to say something like:

  Invalid port name/number 'telnet(rfc2217),tcp,2001': Invalid data
+to parameter on line 33 column 0

That's a little more helpful, but not much in this case.  I don't
currently map the getaddrinfo() error return (where this error is
occuring) to gensio errors.  That's probably a good idea.  But even if I
did, the error would be: "The specified network host does not have any
network addresses in the requested address family."  If you think really
hard you might figure it out from that, but it's still not great.

I'm open to suggestions.

-corey

**Comment by SjonHortensius** [comment]
thanks for your extensive and quick reply. Without looking at your code; I see two possible improvements:

* when the reported error occurs, ser2net should quit. This would allow the o/s (or the admin) to retry after all conditions have been met
* can't you bind on `0.0.0.0` instead of lookup up the actual available addresses? That should allow you to start regardless of the state of any network

thanks!

**Comment by cminyard** [comment]
On Tue, Jan 11, 2022 at 02:28:40AM -0800, SjonHortensius wrote:
> thanks for your extensive and quick reply. Without looking at your code; I see two possible improvements:
> 
> * when the reported error occurs, ser2net should quit. This would allow the o/s (or the admin) to retry after all conditions have been met

I'll have to think about that.  It does shut down on a parsing error,
perhaps it should on this, too.

> * can't you bind on `0.0.0.0` instead of lookup up the actual available addresses? That should allow you to start regardless of the state of any network

That's what happens.  However, if no network devices are up, no IP
addresses are available, and getaddrinfo will fail.

-corey

**Comment by SjonHortensius** [comment]
FYI that this behavior can be worked around with this terrible hack:

```
ExecStartPost=-/bin/sh -c 'systemctl status ser2net|grep -E ^[A-Z]|grep -q "Invalid port name/number" || exit 0; sleep 9; systemctl restart ser2net'
```

it makes sure that ser2net hasn't failed by checking the current status - and restarting it if needed

**Comment by jerrens** [comment]
I had this same problem when creating a systemd unit file for ser2net.  Adding the `After=network-online.target` and equivalent `Wants` lines in the Unit section fixed that problem for me:

```
[Unit]
Description=Allows network connections to serial ports
Documentation=man:ser2net(5)
After=syslog.target network.target
After=network-online.target
Wants=network-online.target

[Service]
EnvironmentFile=-/etc/default/ser2net
Type=forking
ExecStart=/usr/sbin/ser2net -n -c /etc/ser2net/ser2net.yaml -P /run/ser2net.pid $OPTIONS

Restart=always

[Install]
WantedBy=multi-user.target
Alias=ser2net.service
```

**Comment by MichaDit** [comment]
> I had this same problem (in Ubuntu 20.04) when creating a systemd unit file for ser2net. Adding the `After=network-online.target` and equivalent `Wants` lines in the Unit section fixed that problem for me:
> 
> ```
> [Unit]
> Description=Allows network connections to serial ports
> Documentation=man:ser2net(5)
> After=syslog.target network.target
> After=network-online.target
> Wants=network-online.target
> 
> [Service]
> EnvironmentFile=-/etc/default/ser2net
> Type=forking
> ExecStart=/usr/sbin/ser2net -n -c /etc/ser2net/ser2net.yaml -P /run/ser2net.pid $OPTIONS
> Restart=always
> 
> [Install]
> WantedBy=multi-user.target
> Alias=ser2net.service
> ```

Thanks @jerrens, adding the two lines worked for me:
```
After=network-online.target
Wants=network-online.target
```

Note: The `syslog.target` is deprecated since [systemd v198 - 7 Mar 2013](https://github.com/systemd/systemd/blob/6aa8d43ade72e24c9426e604f7fc4b7582b9db7c/NEWS)

**Comment by jerrens** [comment]
Thanks @MichaDit for the note about `syslog.target`.  I've updated my response for those who may stumble across it and miss your note.

**Comment by cminyard** [comment]
I think this can be closed now.  Thanks to those that helped with this, since I"m not much use on these things :).
