### ISSUE TITLE
[Q] How to specify XON/XOFF flow control in ser2net.yaml?

### ISSUE THREAD

**Issue by curlyel** [cminyard/ser2net#62]
I've been using ser2net with a bunch of serial devices before. So I had for example a Ember Zigbee adaptor connected via:

_/etc/ser2net.conf:_
```
#Ember, BitronVideo BV10/2010
10003:raw:0:/dev/zigbee:57600 8DATABITS NONE 1STOPBIT XONXOFF

```

From the man pages, I'm not able to figure out, how to specify XON/XOFF flow control in the ser2net.yaml.
I simply guessed:

```
connection: &Zigbee
  accepter: telnet(rfc2217),tcp,2222
  connector: serialdev,
    /dev/zigbee,
    57600n81 local xonxoff
  options:
    mdns: true
    mdns-sysattrs: true

```

Ser2net seems to accept the xonxoff parameter as in older versions and the tcp connection got established. But I'm still not able to open the remote serial port.

May I ask, if the above is the correct setting in ser2net.yaml equivalent to ser2net.conf above?

**Comment by cminyard** [comment]
On Wed, Dec 15, 2021 at 05:47:11AM -0800, curlyel wrote:
> I've been using ser2net with a bunch of serial devices before. So I had for example a Ember Zigbee adaptor connected via:
> 
> _/etc/ser2net.conf:_
> ```
> #Ember, BitronVideo BV10/2010
> 10003:raw:0:/dev/zigbee:57600 8DATABITS NONE 1STOPBIT XONXOFF
> 
> ```
> 
> From the man pages, I'm not able to figure out, how to specify XON/XOFF flow control in the ser2net.yaml.
> I simply guessed:
> 
> ```
> connection: &Zigbee
>   accepter: telnet(rfc2217),tcp,2222
>   connector: serialdev,
>     /dev/zigbee,
>     57600n81 local xonxoff

Sorry, I missed this earlier.

You need commas between the items above, which is probably the issue.
The docs for this are no in "man 5 gensio" under serialdev.

-corey

**Comment by curlyel** [comment]
Thanks for clarifying 👍
