### ISSUE TITLE
conf not working with new version yaml

### ISSUE THREAD

**Issue by marcuzz0** [cminyard/ser2net#64]
Hi,

with the old version the ser2net.conf file worked with:

3331:raw:0:/dev/ttyACM0:115200 8DATABITS NONE 1STOPBIT banner

if I try to configure the ser2et.yaml file with the new version that I am attaching
[ser2net.txt](https://github.com/cminyard/ser2net/files/7899376/ser2net.txt)

it doesn't work ... Can you help me out?

**Comment by cminyard** [comment]
On Wed, Jan 19, 2022 at 09:48:38AM -0800, marcuzz0 wrote:
> Hi,
> 
> with the old version the ser2net.conf file worked with:
> 
> 3331:raw:0:/dev/ttyACM0:115200 8DATABITS NONE 1STOPBIT banner
> 
> if I try to configure the ser2et.yaml file with the new version like this:

What's the issue?  I'm not sure what "not working" means.

-corey

**Comment by marcuzz0** [comment]
Once started with the command: sudo systemctl start ser2net
check if the tcp stream comes out with the command:
socat tcp: 127.0.0.1: 3331 -
with the old version I saw the tcp flow, now it gives me this:
Device open failure: Remote end closed connection

**Comment by cminyard** [comment]
On Wed, Jan 19, 2022 at 01:11:20PM -0800, marcuzz0 wrote:
> Once started with the command: sudo systemctl start ser2net
> check if the tcp stream comes out with the command:
> socat tcp: 127.0.0.1: 3331 -
> with the old version I saw the tcp flow, now it gives me this:
> Device open failure: Remote end closed connection

Are you sure /dev/ttyACM0 still exists and is accessible?

-corey

**Comment by marcuzz0** [comment]
yes i tried with minicom

**Comment by cminyard** [comment]
On Wed, Jan 19, 2022 at 02:11:39PM -0800, marcuzz0 wrote:
> yes i tried with minicom

I have no idea, then.  I took your file and changed ttyACM to ttyUSB, and
it worked fine.  Though I did have to edit your file, it had a bunch of
extra spaces in it that got added somewhere.

If you could send a file that didn't have all the extra spaces, that
would be great.  Maye try attaching it.  Also, what's the exact output
of the banner?

-corey

**Comment by marcuzz0** [comment]
extra spaces and where?  could you post the file that you corrected so in the morning I'll try it?

**Comment by cminyard** [comment]
On Wed, Jan 19, 2022 at 02:46:33PM -0800, marcuzz0 wrote:
> extra spaces and where?  could you post the file that you corrected so in the morning I'll try it?

Ok, here's the file I tried:

%YAML 1.1
---

define: &banner \r\nser2net port\p device\d [\B] (Debian GNU / Linux)\r\n\r\n

connection: &conms1
     accepter: tcp, 3331
     enable: on
     options:
       banner: *banner
       kickolduser: true
       telnet-brk-on-sync: true
     connector: serialdev,
               /dev/ttyUSB1,
               115200n81, local

I did 'gensiot tcp,localhost,3331' and it worked fine.

Here's the file you sent, as it came to me (mangled by some mailer, I
assume):

% YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml (5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: & banner \ r \ nser2net port \ p device \ d [\ B] (Debian GNU / Linux) \
+r \ n \ r \ n

connection: & conms1
     accepter: tcp, 3331
     enable: on
     options:
       banner: * banner
       kickolduser: true
       telnet-brk-on-sync: true
     connector: serialdev,
               /dev/ttyACM0,
               115200n81, local

-corey

**Comment by marcuzz0** [comment]
Ok Corey, tomorrow I'll try and update you, thanks for your help

**Comment by marcuzz0** [comment]
Hi Corey,

I copied your file to /etc/ser2net.yaml as you posted it. Then I gave the command:

sudo systemctl restart ser2net

but unfortunately same problem...

**Comment by cminyard** [comment]
On Thu, Jan 20, 2022 at 03:56:01AM -0800, marcuzz0 wrote:
> Hi Corey,
> 
> I copied your file to /etc/ser2net.yaml as you posted it. Then I gave the command:

That should be /etc/ser2net/ser2net.yaml.

Sigh, I and others are paying for making that change, but I needed a
directory to put other stuff in. :(.

-corey

**Comment by marcuzz0** [comment]
hi Corey, I finally understood ... the file is correct but there is incompatibility between the device I connect and the latest version of ser2net unfortunately, I use debian on a computer with version 11 but if I use a raspberry with 10 for example everything works because from the repo it downloads the previous one (3.5.2).  Anyway I solved it by installing an older version in a docker on debian 11. Actually the problem is only on the tttyACM0 if the data flow I pass through the ttyUSB… then everything works.  With the docker it goes with all ports
