### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by abergdesign** [cminyard/ser2net#65]
Hi,
I am really looking forward to trying out the ser2net cli on an XU4 Odroid arm v7 ubuntu 18.04. I downloaded the ser2net-4.3.5 and gensio-2.4.0-rc1 tar.gz from sourceforge and got it all compiled without errors. (I didn't install libssl-dev since it had unmet dependencies on the hardkernel/odroid version of ubuntu 18.04, but it compiled OK anyway and my use cases do not need ssl.)

On first run of ser2net -v, I get:
`ser2net: error while loading shared libraries: libgensio.so.0: cannot open shared object file: No such file or directory`

`cat /usr/local/lib/libgensio.so.0` returns a big binary file, and `cat /etc/ld.so.conf.d/libc.conf` returns:
`# libc default configuration`
`/usr/local/lib`

Any ideas how to troubleshoot further?

Many thanks, Ulf

**Comment by cminyard** [comment]
On Wed, Feb 16, 2022 at 09:26:25AM -0800, abergdesign wrote:
> Hi,
> I am really looking forward to trying out the ser2net cli on an XU4 Odroid arm v7 ubuntu 18.04. I downloaded the ser2net-4.3.5 and gensio-2.4.0-rc1 tar.gz from sourceforge and got it all compiled without errors. (I didn't install libssl-dev since it had unmet dependencies on the hardkernel/odroid version of ubuntu 18.04, but it compiled OK anyway and my use cases do not need ssl.)
> 
> On first run of ser2net -v, I get:
> `ser2net: error while loading shared libraries: libgensio.so.0: cannot open shared object file: No such file or directory`
> 
> `cat /usr/local/lib/libgensio.so.0` returns a big binary file, and `cat /etc/ld.so.conf.d/libc.conf` returns:
> `# libc default configuration`
> `/usr/local/lib`
> 
> Any ideas how to troubleshoot further?

You need to run "ldconfig", I believe.

-corey

**Comment by abergdesign** [comment]
That solved it, thank you Corey! I should have known. 
Thank you for the quick reply!
Ulf
