### ISSUE TITLE
typos in manual pages

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/ser2net#73]
Here is what lintian found:

> I: ser2net: spelling-error-in-binary defalt default [usr/sbin/ser2net]

this is in ser2net.c, in the -Y usage string.

> I: ser2net: typo-in-manual-page recevied received [usr/share/man/man5/ser2net.yaml.5.gz:424]
> I: ser2net: typo-in-manual-page recevied received [usr/share/man/man5/ser2net.yaml.5.gz:428]
> I: ser2net: typo-in-manual-page recieve receive [usr/share/man/man5/ser2net.yaml.5.gz:367]
> I: ser2net: typo-in-manual-page recieve receive [usr/share/man/man5/ser2net.yaml.5.gz:640]
> I: ser2net: typo-in-manual-page subtitution substitution [usr/share/man/man5/ser2net.yaml.5.gz:18]
> I: ser2net: typo-in-manual-page reponse response [usr/share/man/man8/ser2net.8.gz:237]

These are all triviall found in the man page.

Greetings
Marc

**Comment by cminyard** [comment]
All these were just fixed with a merge request #70.
