### ISSUE TITLE
ser2net service deactivations and core dumps

### ISSUE THREAD

**Issue by istorrs** [cminyard/ser2net#77]
Hello Corey,

First of all, thanks for creating and maintaining this very useful utility!

I am using ser2net 3.6 as part of a test harness with currently 7 serial port devices being used concurrently. I've noticed that during longer duration connections, the telnet connection is being closed. This seems to correspond with the ser2net service either being deactivated (not by me!) or crashed. It often seems to take multiple attempts for the service to restart.  See logs below. 

Can you provide any suggestions on how to increase the logging to try to figure out what is causing this?

Regards,
Ian

Sep 14 13:17:59 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully. <<<What could be deactivating the service?
Sep 14 13:17:59 rack8-termserv-b systemd[1]: ser2net.service: Consumed 35.240s CPU time.
Sep 14 13:18:00 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 11.
Sep 14 13:18:00 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 13:18:00 rack8-termserv-b systemd[1]: ser2net.service: Consumed 35.240s CPU time.
Sep 14 13:18:00 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 13:18:00 rack8-termserv-b ser2net[5858]: ser2net startup
Sep 14 13:18:00 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.

Sep 14 15:09:01 rack8-termserv-b systemd[1]: ser2net.service: Main process exited, code=dumped, status=11/SEGV <<<<< How to debug this crash?
Sep 14 15:09:01 rack8-termserv-b systemd[1]: ser2net.service: Failed with result 'core-dump'.
Sep 14 15:09:01 rack8-termserv-b systemd[1]: ser2net.service: Consumed 34.719s CPU time.
Sep 14 15:09:02 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 12.
Sep 14 15:09:02 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 15:09:02 rack8-termserv-b systemd[1]: ser2net.service: Consumed 34.719s CPU time.
Sep 14 15:09:02 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 15:09:02 rack8-termserv-b ser2net[6107]: ser2net startup
Sep 14 15:09:02 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 14 15:09:02 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 14 15:09:04 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 13.
Sep 14 15:09:04 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 15:09:04 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 15:09:04 rack8-termserv-b ser2net[6111]: ser2net startup
Sep 14 15:09:04 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 14 15:09:04 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 14 15:09:05 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 14.
Sep 14 15:09:05 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 15:09:05 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 15:09:05 rack8-termserv-b ser2net[6114]: ser2net startup
Sep 14 15:09:05 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 14 15:09:05 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 14 15:09:06 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 15.
Sep 14 15:09:06 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 15:09:06 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 15:09:06 rack8-termserv-b ser2net[6117]: ser2net startup
Sep 14 15:09:06 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 14 15:09:06 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 14 15:09:07 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 16.
Sep 14 15:09:07 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 15:09:07 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 15:09:07 rack8-termserv-b ser2net[6121]: ser2net startup
Sep 14 15:09:07 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 14 15:09:07 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 14 15:09:09 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 17.
Sep 14 15:09:09 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 14 15:09:09 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 14 15:09:09 rack8-termserv-b ser2net[6124]: ser2net startup
Sep 14 15:09:09 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.

Sep 15 00:58:39 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully. <<<< What caused this?
Sep 15 00:58:39 rack8-termserv-b systemd[1]: ser2net.service: Consumed 3min 14.189s CPU time.
Sep 15 00:58:41 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 18.
Sep 15 00:58:41 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 15 00:58:41 rack8-termserv-b systemd[1]: ser2net.service: Consumed 3min 14.189s CPU time.
Sep 15 00:58:41 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 15 00:58:41 rack8-termserv-b ser2net[9770]: ser2net startup
Sep 15 00:58:41 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 15 00:58:41 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 15 00:58:42 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 19.
Sep 15 00:58:42 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 15 00:58:42 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 15 00:58:42 rack8-termserv-b ser2net[9773]: ser2net startup
Sep 15 00:58:42 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 15 00:58:42 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 15 00:58:43 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 20.
Sep 15 00:58:43 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 15 00:58:43 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 15 00:58:43 rack8-termserv-b ser2net[9776]: ser2net startup
Sep 15 00:58:43 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 15 00:58:43 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 15 00:58:44 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 21.
Sep 15 00:58:44 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 15 00:58:44 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 15 00:58:44 rack8-termserv-b ser2net[9779]: ser2net startup
Sep 15 00:58:44 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.
Sep 15 00:58:44 rack8-termserv-b systemd[1]: ser2net.service: Deactivated successfully.
Sep 15 00:58:46 rack8-termserv-b systemd[1]: ser2net.service: Scheduled restart job, restart counter is at 22.
Sep 15 00:58:46 rack8-termserv-b systemd[1]: Stopped Allows network connections to serial ports.
Sep 15 00:58:46 rack8-termserv-b systemd[1]: Starting Allows network connections to serial ports...
Sep 15 00:58:46 rack8-termserv-b ser2net[9782]: ser2net startup
Sep 15 00:58:46 rack8-termserv-b systemd[1]: Started Allows network connections to serial ports.

**Comment by cminyard** [comment]
On Thu, Sep 15, 2022 at 07:04:27AM -0700, istorrs wrote:
> Hello Corey,
> 
> First of all, thanks for creating and maintaining this very useful utility!
> 
> I am using ser2net 3.6 as part of a test harness with currently 7 serial port devices being used concurrently. I've noticed that during longer duration connections, the telnet connection is being closed. This seems to correspond with the ser2net service either being deactivated (not by me!) or crashed. It often seems to take multiple attempts for the service to restart.  See logs below. 
> 
> Can you provide any suggestions on how to increase the logging to try to figure out what is causing this?

If you aren't using version 3.5.4, can you try that?  There's a telnet
crash fix that went in that release.

Also, the 4.x version of ser2net is a lot better.

If that doesn't help, you can get a coredump from ser2net and and if I
can get the binaries and the coredump I can look at it.  That's a bit of
a job, you have to change several things.  You have to set the "ulimit
-c" for the program, and you have to change /proc/sys/kernel/core_pattern.
Most distros change that to send coredumps to them.

BTW, there is no ser2net 3.6.  I assume you mean 3.5.

-corey

**Comment by istorrs** [comment]
Hi Corey,

Sorry, that was a typo, I meant to say version v4.3.6 is the version I am running.

Ian

**Comment by cminyard** [comment]
On Thu, Sep 15, 2022 at 09:57:20AM -0700, istorrs wrote:
> Hi Corey,
> 
> Sorry, that was a typo, I meant to say version v4.3.6 is the version I am running.

Ok, is it possible to get a coredump and binaries?

-corey

**Comment by istorrs** [comment]
I'll try to configure the system to collect core dumps, but I'm not familiar with all the steps. This is how it is set right now:

rtp-lab@rack8-termserv-b:~$ cat /proc/sys/kernel/core_pattern
|/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h
rtp-lab@rack8-termserv-b:~$ ulimit -c
0


Also,  so far the logs show only a few cores happening compared to the number of times ser2net is restarted. Can it also exit silently for some errors?

**Comment by cminyard** [comment]
On Thu, Sep 15, 2022 at 10:14:20AM -0700, istorrs wrote:
> I'll try to configure the system to collect core dumps, but I'm not familiar with all the steps. This is how it is set right now:
> 
> ***@***.***:~$ cat /proc/sys/kernel/core_pattern
> |/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h

This is set to send it to the OS vendor.  You should change it to
core.%p to have it save a core in the current directory.  Or you can
specify a path, like /tmp/core.%p.

> ***@***.***:~$ ulimit -c
> 0

ulimit is per process, so you will need to set that for ser2net itself,
and it should be set to "unlimited".  I'm not sure how to set that for
how you start ser2net.  If you can set it in the shell you start ser2net
from, that should work.

You can test this by doing "kill -segv <pid>" and it should dump the
core.

> 
> 
> Also,  so far the logs show only a few cores happening compared to the number of times ser2net is restarted. Can it also exit silently for some errors?

Not that I know of.  It's probably a crash.  But, there are always
bugs...

-corey

**Comment by istorrs** [comment]
rtp-lab@rack8-termserv-b:~$ coredumpctl list
TIME                          PID UID GID SIG     COREFILE EXE                     SIZE
Fri 2022-09-16 00:58:39 EDT 12309   0   0 SIGSEGV journal  /usr/local/sbin/ser2net  n/a
rtp-lab@rack8-termserv-b:~$ coredumpctl list ser2net
TIME                          PID UID GID SIG     COREFILE EXE                     SIZE
Fri 2022-09-16 00:58:39 EDT 12309   0   0 SIGSEGV journal  /usr/local/sbin/ser2net  n/a
rtp-lab@rack8-termserv-b:~$ coredumpctl -o ser2net.coredump dump /usr/local/sbin/ser2net
           PID: 12309 (ser2net)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Fri 2022-09-16 00:58:38 EDT (6h ago)
  Command Line: /usr/local/sbin/ser2net -c /usr/local/etc/ser2net/ser2net.yaml -P /run/ser2net.pid
    Executable: /usr/local/sbin/ser2net
 Control Group: /system.slice/ser2net.service
          Unit: ser2net.service
         Slice: system.slice
       Boot ID: aa39c32a5293468bb2085e06253f5bd0
    Machine ID: ccfeda5081e64c73b4da0a092d2fc68f
      Hostname: rack8-termserv-b
       Storage: journal
       Message: Process 12309 (ser2net) of user 0 dumped core.
                
                Found module linux-vdso.so.1 with build-id: f96ac4b22054f648d18266b14f6927b7eb2d238e
                Found module libgpg-error.so.0 with build-id: d917fad1653d0a2e8017898789cb825fb426f6bf
                Found module libgcrypt.so.20 with build-id: 320798c13872bbda5dbf71816357de1eeee021d5
                Found module libcap.so.2 with build-id: d0b607063a2b3697c25e6bcec0394270058a80a8
                Found module liblz4.so.1 with build-id: 9af9610366f698b77d4b4d9ddc52c93d924ee6ba
                Found module libzstd.so.1 with build-id: e0f73540861c62f788f8079ddecfff784543ca5e
                Found module liblzma.so.5 with build-id: 9f6c317bddd36dd22b21a56242e46a25ee89d1c3
                Found module libsystemd.so.0 with build-id: a0983aca31a3cdfa3bcf81b4e668a164c397e441
                Found module libdbus-1.so.3 with build-id: bc33c0c7280784360c22ace8d93a724e8e808174
                Found module libcap-ng.so.0 with build-id: f35a0f28923dbf26393ff8fe16833b770015acd0
                Found module libsctp.so.1 with build-id: 910e7a1b00a13edc1b753eea62e655f86bf6bc48
                Found module libavahi-common.so.3 with build-id: 4979c0a8c214b91c134850e8700a697317bad8cd
                Found module libavahi-client.so.3 with build-id: 9939cbc383461cc72f4b8479f1d2a4bc315d1e53
                Found module libcrypto.so.3 with build-id: 688b45405ff00a425f6af81b70edd61aeb9832cd
                Found module libssl.so.3 with build-id: 1e672dc6007b06c3162070d8a10ce2e4f319657e
                Found module libaudit.so.1 with build-id: ced0cdc6928e0ecd7f7a79d5d136a91b7aa92b94
                Found module libc.so.6 with build-id: f37f3aa07c797e333fd106472898d361f71798f5
                Found module libgensio.so.0 with build-id: 0c2de3b7b827aec0db2c7e3f070dffaf1d6e85ab
                Found module libpam.so.0 with build-id: d3fe59313e16c0aa6c0f17028cdd9f7c90ceecf7
                Found module libyaml-0.so.2 with build-id: 521f93a22fe421e67b768fb23ae0eab9074d76d1
                Found module ser2net with build-id: d841cdf48a1b2e2cc5fc8c14e8ff8a0bd8374bff
                Stack trace of thread 12309:
                #0  0x0000ffffb75c90d4 gensio_unix_setup_termios (libgensio.so.0 + 0x190d4)
                #1  0x0000ffffb75c9338 gensio_unix_termios_control (libgensio.so.0 + 0x19338)
                #2  0x0000ffffb75f3770 sterm_control_raddr (libgensio.so.0 + 0x43770)
                #3  0x0000ffffb75cc988 gensio_ll_control (libgensio.so.0 + 0x1c988)
                #4  0x0000ffffb75ccb5c gensio_base_func (libgensio.so.0 + 0x1cb5c)
                #5  0x0000ffffb75c30b4 gensio_control (libgensio.so.0 + 0x130b4)
                #6  0x0000aaaada4d65b4 net_raddr_str (ser2net + 0x165b4)
                #7  0x0000aaaada4d7130 showshortport (ser2net + 0x17130)
                #8  0x0000aaaada4d75ac showshortports (ser2net + 0x175ac)
                #9  0x0000aaaada4c705c process_command (ser2net + 0x705c)
                #10 0x0000aaaada4c75d8 process_input_line (ser2net + 0x75d8)
                #11 0x0000ffffb75c5610 gensio_cb (libgensio.so.0 + 0x15610)
                #12 0x0000ffffb75ca718 basen_read_data_handler (libgensio.so.0 + 0x1a718)
                #13 0x0000ffffb75ddb0c telnet_ll_write (libgensio.so.0 + 0x2db0c)
                #14 0x0000ffffb75caae0 gensio_filter_ll_write (libgensio.so.0 + 0x1aae0)
                #15 0x0000ffffb75cc7c0 filter_ll_write (libgensio.so.0 + 0x1c7c0)
                #16 0x0000ffffb75d1654 child_event (libgensio.so.0 + 0x21654)
                #17 0x0000ffffb75c5610 gensio_cb (libgensio.so.0 + 0x15610)
                #18 0x0000ffffb75ca718 basen_read_data_handler (libgensio.so.0 + 0x1a718)
                #19 0x0000ffffb75cc6a4 filter_ll_write (libgensio.so.0 + 0x1c6a4)
                #20 0x0000ffffb75d0c7c fd_deliver_read_data (libgensio.so.0 + 0x20c7c)
                #21 0x0000ffffb75d0d7c fd_deliver_read_data (libgensio.so.0 + 0x20d7c)
                #22 0x0000ffffb760e354 handle_selector_call (libgensio.so.0 + 0x5e354)
                #23 0x0000ffffb76102e4 process_fds_epoll (libgensio.so.0 + 0x602e4)
                #24 0x0000ffffb76103a4 sel_select (libgensio.so.0 + 0x603a4)
                #25 0x0000aaaada4ce330 op_loop (ser2net + 0xe330)
                #26 0x0000aaaada4c5aa8 main (ser2net + 0x5aa8)
                #27 0x0000ffffb74273fc __libc_start_call_main (libc.so.6 + 0x273fc)
                #28 0x0000ffffb74274cc __libc_start_main_impl (libc.so.6 + 0x274cc)
                #29 0x0000aaaada4c6030 _start (ser2net + 0x6030)
[ser2net_core_2.zip](https://github.com/cminyard/ser2net/files/9583573/ser2net_core_2.zip)

**Comment by istorrs** [comment]
This is running in a raspberry pi.

**Comment by cminyard** [comment]
I forgot to ask, what version of gensio are you using?

-corey

**Comment by istorrs** [comment]
Based on the stack trace, I think the crash is happening when a python script is connecting to the control port of ser2net. A jenkins server is running tests on the 7 serial devices connected via ser2net. Sometimes we found that a port was left busy, so we added a step to connect to the control port and dump the state of the ports with showshortports and also to disconnect a port that may have been left connected. The sequence when this works is:

1 Telnet to ser2net control port
2 showshortports to get a list of all ports, then map the telnet port to the serial port
3 showshortport on the serial port which is still active
4 disconnect the serial port
5 showshortport again to confirm it is released

It looks like the first 3 steps may have been in progress?

**Comment by cminyard** [comment]
Ok.  Are you using the stock ser2net and gensio?  What distribution are you running on the Pi?  Can you get the exact bulid version using "dpkg -l | grep -e ser2net -e gensio" (debian-based) or "rpm -qa | grep -e ser2net -e gensio" (redhat-based)?

With the information you give above, I may be able to figure it out, but being able to load it into the debugger might be helpful.

**Comment by istorrs** [comment]
Linux rack8-termserv-b 5.15.0-1014-raspi #16-Ubuntu SMP PREEMPT Thu Aug 25 09:50:55 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

v4.3.6 of ser2net  and the gensio library v2.4.2. We had to build the source ourselves because the ones available with Ubuntu on aarch64le are older, but we do not modify the source code, just download and build it.

We plan to upgrade to ser2net 4.3.8 and gensio 2.6-rc2 early next week.

**Comment by cminyard** [comment]
If that's the case, can you upload the libgensio so file?  I'll be able to debug it with that.

**Comment by cminyard** [comment]
I think the following patch will fix the problem:

diff --git a/lib/sergensio_serialdev.c b/lib/sergensio_serialdev.c
index 87df0760..c1e51cb9 100644
--- a/lib/sergensio_serialdev.c
+++ b/lib/sergensio_serialdev.c
@@ -807,6 +807,9 @@ sterm_check_close_drain(void *handler_data, struct gensio_iod *iod,
            uucp_rm_lock(sdata->devname);
        gensio_fd_ll_close_now(sdata->ll);
     }
+    if (err != GE_INPROGRESS)
+       /* We are really closing, the iod will be destroyed now. */
+       sdata->iod = NULL;
  out_unlock:
     sterm_unlock(sdata);
     return err;

The close code is not clearing the io descriptor, but until the close completes it's still available to do control operations, like querying the serial port parameters.

The rest of the code should probably handle a NULL iod, at least by inspection and it passes all my tests.  Other similar gensios (pty) do this, it was missed here.  But if you want to try out the patch, feel free.  It's not in the most current release, either.

**Comment by istorrs** [comment]
Thanks again, Corie. I will try this fix tomorrow. It may have to soak a few days in our environment before I can confirm it has resolved the issue.

**Comment by istorrs** [comment]
The patch has soaked for several days now and the core dumps and disconnections are no longer happening.

**Comment by cminyard** [comment]
On Sat, Sep 24, 2022 at 05:30:08AM -0700, istorrs wrote:
> The patch has soaked for several days now and the core dumps and disconnections are no longer happening.

Thanks for testing this.  I've got one other outstanding issue, and I'll
release a 2.5 and a new 2.6-rc.  If you could close the issue, it would
be great.

-corey
