### ISSUE TITLE
Problem with windows telnet client

### ISSUE THREAD

**Issue by gobarksoo** [cminyard/ser2net#8]
I observed an abnormal behavior of ser2net while connecting from Windows telnet client. Telnet command options are exchanged forever between ser2net server and Windows telnet client. 

![image](https://user-images.githubusercontent.com/33204427/49445904-5131fe80-f816-11e8-914d-16782f5eb9de.png)

The figure above is a snapshot of packet capture.
x.x.x.100: ser2net server
x.x.x.49: Windows telnet client

In the figure, ser2net sends "fffb03:fffb01:fffe01:fffd00" command to the client.

According to my analysis, the following commands are exchanged and last four sequences are repeated forever. (I omitted leading 0xff pattern)

![image](https://user-images.githubusercontent.com/33204427/49446235-082e7a00-f817-11e8-90d5-083dec310a6b.png)

Is there any reasons for this behavior ?

Anyway, console connection is still valid and I didn't observe any other problem.

**Comment by gobarksoo** [comment]
Thanks.
Could you please share the commit link for this specific issue ?

**Comment by cminyard** [comment]
On 12/4/18 1:02 PM, gobarksoo wrote:
>
> Thanks.
> Could you please share the commit link for this specific issue ?
>

There were two commits,

https://github.com/cminyard/ser2net/commit/f1e348a09dfae5cc6d354fefec8bdbaf3c702494

https://github.com/cminyard/ser2net/commit/e521637854f5c95c9b2a948f376138e865ff9b1f

But you are really better off with the full 3.5.1 release.

-corey

**Comment by cminyard** [comment]
On 12/4/18 1:02 PM, gobarksoo wrote:
>
> Thanks.
> Could you please share the commit link for this specific issue ?
>
Also, you didn't answer the question.  What version are you using?

-corey

**Comment by gobarksoo** [comment]
We are using version 2.8.

**Comment by cminyard** [comment]
On 12/4/18 4:57 PM, gobarksoo wrote:
>
> We are using version 2.8.
>
> —
>

You really need to upgrade.  I have no idea what patches are in there 
that might cause this issue.

-corey

**Comment by meldh76** [comment]
I am unable to withdraw to my wallet
