### ISSUE TITLE
Can you add supported baudrates?

### ISSUE THREAD

**Issue by saramlove** [cminyard/ser2net#81]
Hello,
I use USB to Serial to control devices with a non-standard baudrate (3840).

If I control it via USB to Serial with a laptop program, it works fine.

Is it possible to add a non-standard baudrate in ser2net?

![2022-09-22 18 35 09](https://user-images.githubusercontent.com/84359554/191716584-fb57cba9-1ae8-4c19-aa0d-31ecf2d55424.png)

Thank you very much.

**Comment by cminyard** [comment]
On Thu, Sep 22, 2022 at 02:52:33AM -0700, saramlove wrote:
> Hello,
> I use USB to Serial to control devices with a non-standard baudrate (3840).
> 
> If I control it via USB to Serial with a laptop program, it works fine.
> 
> Is it possible to add a non-standard baudrate in ser2net?

You don't mention the version of ser2net or the gensio library.

Older versions required you to add a custspeed option, like:

  serialdev(custspeed),/dev/ttyUSB0,3840n81

It just works on newer version and it ignores custspeed.  I just tested
it.  The hardware also has to support it, but you've already tested
that.

**Comment by saramlove** [comment]
> On Thu, Sep 22, 2022 at 02:52:33AM -0700, saramlove wrote: Hello, I use USB to Serial to control devices with a non-standard baudrate (3840). If I control it via USB to Serial with a laptop program, it works fine. Is it possible to add a non-standard baudrate in ser2net?
> You don't mention the version of ser2net or the gensio library. Older versions required you to add a custspeed option, like: serialdev(custspeed),/dev/ttyUSB0,3840n81 It just works on newer version and it ignores custspeed. I just tested it. The hardware also has to support it, but you've already tested that.

**Comment by saramlove** [comment]
This is perfect.
Thank you so much. :)
