### ISSUE TITLE
man ser2net default config location is wrong

### ISSUE THREAD

**Issue by timdonovanuk** [cminyard/ser2net#82]
man ser2net says `Set the configuration file to one other than the default of /etc/ser2net/ser2net.yaml.`
default install `creates /etc/default/ser2net `with `CONFFILE="/etc/ser2net.yaml"`

Not sure if the man is wrong, or the default install is wrong, but they should be the same.

**Comment by cminyard** [comment]
/etc/default/ser2net is something added by whatever distro you use, it is not part of ser2net.  You will have to bring this up with your distro.

**Comment by timdonovanuk** [comment]
I'm using a very obscure distro called Debian, and ser2net was installed using an even more obscure installation method (apt) so probably not worth ensuring the manual is correct for such an unusual combination that no other users are sure to use 😆

**Comment by cminyard** [comment]
On Sat, Oct 01, 2022 at 05:26:03AM -0700, timdonovanuk wrote:
> I'm using a very obscure distro called Debian, and ser2net was installed using an even more obscure installation method (apt) so probably not worth ensuring the manual is correct for such an unusual combination that no other users are sure to use 😆 

Well, it's not a matter of the commonness of the distro.  It's a matter
of the distro getting it wrong and needing to fix it.  You need to
report it to them.

-corey
