### ISSUE TITLE
Unknown name server lookup failure

### ISSUE THREAD

**Issue by Zugschlus** [cminyard/ser2net#88]
Hi,

has the configuration file format changed between ser2net 4.3.7 and 4.3.11?

Trying to update the ser2net package in Debian to 4.3.11, I found that the new ser2net won't start on my test system: "device configuration serialdev, /dev/ttyS0, 9600n81,local invalid: Unknown name server lookup failure". The configuration stanza in question is:

```
connection: &con0096
    accepter: tcp,localhost,2000
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyS0,
              9600n81,local
```

And it used to work in the older versions. What is ser2net trying to look up on startup here?

Greetings
Marc

**Comment by cminyard** [comment]
This is a common issue people have had, but it's not really a problem with ser2net.  The problem is that ser2net is started before networking.  The code calls getaddrinfo() to look up "localhost" (or whatever you put there, even nothing) and it can't get to the nameserver.

4.3.11 should have a fix in to retry periodically if this fails.  It will issue the error, but should retry every few seconds.  Is that not happening?

**Comment by Zugschlus** [comment]
That didnt happen on my system, and also, it happened on package installation. The machine was up and running when I started ser2net. I was even logged in via ssh!

**Comment by Zugschlus** [comment]
Okay, this is a local packaging issue regarding gensio. ser2net looks for /usr/libexec/gensio-2.6.1/libgensio_serialdev.so which is not part of the gensio package. I am not sure whether this is supposed to happen and if the .so is supposed to be at this path, especially with the gensio version number in the pathname. Closing this issue for the time being.

**Comment by cminyard** [comment]
On Mon, Jan 09, 2023 at 11:06:34PM -0800, Zugschlus wrote:
> Okay, this is a local packaging issue regarding gensio. ser2net looks for /usr/libexec/gensio-2.6.1/libgensio_serialdev.so which is not part of the gensio package. I am not sure whether this is supposed to happen and if the .so is supposed to be at this path, especially with the gensio version number in the pathname. Closing this issue for the time being.

Oh, that's a new one, yes.  Sorry for the misleading post.

Yes, the new gensio library has split out all the gensios into separate
loadable modules, and that's the right path.  The number of dependencies
was getting out of control for one big library, plus this makes it easy
to add or remove gensios.

You can change this and go back to the old way via configure parameters
to gensio.

**Comment by 0xStuart** [comment]
I have just run into this issue.  Trying to start ser2net from the command line. I checked for the library, and found this
/libexec/gensio/2.7.7/libgensio_serialdev.so

**Comment by cminyard** [comment]
On Tue, Jan 02, 2024 at 09:22:06AM -0800, Stuart wrote:
> I have just run into this issue.  Trying to start ser2net from the command line. I checked for the library, and found this
> /libexec/gensio/2.7.7/libgensio_serialdev.so
> 

Can you post your ser2net config file?  It's likely that you have
something misnamed.

This is really something I have to fix.  To make it compatible with a
really old version of ser2net, if you didn't put anything, it would
attempt to guess what type of gensio you were using, and it would
default to "serialdev" if it started with /dev/ and default to tcp
elsewise.

So if you put a gensio name it doesn't recognise, it will attempt use
that as a TCP host name and try to connect to it.  Thus the nameserver
failure.  I'm going to remove that right now, as nobody should be using
it at this point.

-corey

**Comment by 0xStuart** [comment]
```
connection: &myconn
 accepter: telnet(rfc2217),tcp,3000
 connector: serialdev,/dev/ttyS1,38400n81
```

**Comment by cminyard** [comment]
On Tue, Jan 02, 2024 at 10:00:55AM -0800, Stuart wrote:
> ```
> connection: &myconn
>  accepter: telnet(rfc2217),tcp,3000
>  connector: serialdev,/dev/ttyS1,38400n81
> ```

That works fine for me.  Is that the whole file?  Maybe there some
international character in there?

**Comment by 0xStuart** [comment]
Yes that's the whole file, and I tried different example configs.  Works ok on my Raspberry Pi.

This device is running busybox if that makes any difference.  The error seemed specific, so was hoping it easy to trace.

**Comment by cminyard** [comment]
On Tue, Jan 02, 2024 at 10:56:32AM -0800, Stuart wrote:
> Yes that's the whole file, and I tried different example configs.  Works ok on my Raspberry Pi.
> 
> This device is running busybox if that makes any difference.  The error seemed specific, so was hoping it easy to trace.

What version of ser2net and gensio is this?

**Comment by 0xStuart** [comment]
```
[root@milkv-duo]~# ser2net -v
ser2net version 4.5.1

[root@milkv-duo]~# gensiot --version
Version 2.7.7
```

**Comment by cminyard** [comment]
On Tue, Jan 02, 2024 at 10:56:32AM -0800, Stuart wrote:
> Yes that's the whole file, and I tried different example configs.  Works ok on my Raspberry Pi.
> 
> This device is running busybox if that makes any difference.  The error seemed specific, so was hoping it easy to trace.

Actually, can you run strace on it?

strace -i my.trace ser2net ...

Then send me my.trace.  Or you might be able to figure it out just
looking at it.

-corey
