### ISSUE TITLE
Double prompt at end of command response

### ISSUE THREAD

**Issue by istorrs** [cminyard/ser2net#89]
Hi Cory,

I'm using the latest versions, downloaded, built and installed on my UBuntu 22.04 x86-64 system:
gensio 2.6.2
ser2net 4.3.11

I'm connecting from UBuntu 22.04 to a QNX target via ser2net. The issue I see is that is a command/response/prompt sequence sent using ser2net (telnet), the prompt after the command is duplicated. I see this when manually connected with telnet to the device from a UBuntu shell, or when using 7 year old legacy automation that had run fine on UBuntu 20.04 with the version of ser2net that came with 20.04. This seems to have stopped working after I upgraded to 22.04 and got a newer version of ser2net with that,

That same legacy automation suite works fine if I configure it to telnet to target via a network interface rather than telnet to ser2net. 

**Output when using ser2net:**

``
telnet 10.182.19.157 2000
Trying 10.182.19.157...
Connected to 10.182.19.157.
Escape character is '^]'.

ser2net port tcp,2000 device serialdev, /dev/ttyUSB0, 115200n81,local [,115200N81,CLOCAL] (Debian GNU/Linux)
\# 
\# uname -a
uname -a
QNX localhost 6.6.0 2014/02/22-19:07:53EST i.MX6Q_Sabre-Smart_Board armle
\# 
\# uname -a 
QNX localhost 6.6.0 2014/02/22-19:07:53EST i.MX6Q_Sabre-Smart_Board armle
\# 
\#  <<<<<<<<<<<<<<< second of 2 \#
``
Notice the # prompt is received twice every time CRLF is sent to the device.

If I open the serial port directly with GTKTerm:

\# uname -a
QNX localhost 6.6.0 2014/02/22-19:07:53EST i.MX6Q_Sabre-Smart_Board armle
\# uname -a 
QNX localhost 6.6.0 2014/02/22-19:07:53EST i.MX6Q_Sabre-Smart_Board armle
\#
Only a single prompt is received.

I also suspect that there are spurious # characters being sent by ser2net. I tried to compensate for this by adding a loop in the automation to eat the extra # and sometimes it takes up to 6 to consume them all. And I also see sequences like this
\# uname -a 
\# 
QNX localhost 6.6.0 2014/02/22-19:07:53EST i.MX6Q_Sabre-Smart_Board armle
\# 
where a spurious # prompt character comes between the command echo and the command response, which really messes up the expect automation.

Hoping this is enough to help you discover the root cause. As always, thanks for ser2net.

Regards,
Ian

**Comment by cminyard** [comment]
On Mon, Jan 23, 2023 at 09:13:53AM -0800, istorrs wrote:
> Hi Cory,
> 
> I'm using the latest versions, downloaded, built and installed on my UBuntu 22.04 x86-64 system:
> gensio 2.6.2
> ser2net 4.3.11

Can you send your ser2net configuration file?

-corey

**Comment by istorrs** [comment]
I am just using the default simple config file.
$ cat /etc/ser2net.yaml
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
# 
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &con0096
    accepter: tcp,2000
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB0,
              115200n81,local

connection: &con1096
    accepter: tcp,2001
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB1,
              115200n81,local

connection: &con0192
    accepter: tcp,2002
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
              /dev/ttyUSB2,
              115200n81,local

connection: &con1192
    accepter: tcp,2003
    enable: on
    options:
      banner: *banner
      kickolduser: true
      telnet-brk-on-sync: true
    connector: serialdev,
`

**Comment by istorrs** [comment]
That was the issue. Maybe you should change the default to be telnet?

**Comment by cminyard** [comment]
On Tue, Jan 24, 2023 at 06:14:12AM -0800, istorrs wrote:
> A coworker just noticed that the default simple config file has tcp accepter rather than telnet accepter. Could that be the issue?

Yes, that is a common problem.  It needs to be:
   connector: telnet,tcp,....

**Comment by cminyard** [comment]
On Tue, Jan 24, 2023 at 06:17:56AM -0800, istorrs wrote:
> That was the issue. Maybe you should change the default to be telnet?

Probably not.  It's really too late to change it, anyway.

There are plenty of people who don't want the telnet protocol there.
Unless you need to control the serial port (baud rate, etc.) it doesn't
really do anything for you except let you use the telnet program, and if
you are using a program to talk to the serial port, it gets in the way.

I understand what you are saying, but it's really not feasible now.

-corey

**Comment by istorrs** [comment]
Thanks again for your support.
