### ISSUE TITLE
how to config to support many tcp clients

### ISSUE THREAD

**Issue by hisstone** [cminyard/ser2net#90]
hello, cminyard

is the ser2net have the ability to support many clients? how to config it? 

below is my yaml config content:
`
connection: &con01
  accepter: tcp,20109
  connector: serialdev,/dev/ttyUSB0,115200n81,nobreak,local
  options:
    kickolduser: true
`
then I open two tcp clients, when one is connecting with port 20109, this client can receiving and send data from/to serial device.
but when I try open another tcp client try connecting with port 20109, the first one will closed!

So how to config to support many tcp clients that all could receiving the serial device data ?

thanks a lot!

**Comment by cminyard** [comment]
On Thu, Feb 02, 2023 at 07:44:29PM -0800, hisstone wrote:
> hello, cminyard
> 
> is the ser2net have the ability to support many clients? how to config it? 

Yes, there is.

> 
> below is my yaml config content:
> `connection: &con01
>   accepter: tcp,20109
>   connector: serialdev,/dev/ttyUSB0,115200n81,nobreak,local
>   options:
>     kickolduser: true
> `
> then I open two tcp clients, when one is connecting with port 20109, this client can receiving and send data from/to serial device.
> but when I try open another tcp client try connecting with port 20109, the first one will closed!

That's what kickolduser does.  So no surprise.

> 
> So how to config to support many tcp clients that all could receiving the serial device data ?

Add "max-connections: <n>" where <n> is the maximum number of
connections you want to allow.

If you pull up the manual page "man 5 ser2net.yaml" it will describe all
this under "MULITPLE CONNECTIONS".  There are some "interesting"
interactions, especially with flow control.  It's a lot harder to do
this than you might imagine.

Also, the kickolduser interaction is wrong, it only kicks off a single
user, not every one.  I just fixed that.

> 
> thanks a lot!

You are welcome.

-corey

**Comment by cminyard** [comment]
I assume this is working for you.
