### ISSUE TITLE
telnet-brk-on-sync is non functional since genio framework

### ISSUE THREAD

**Issue by russdill** [cminyard/ser2net#93]
When telnet handling was moved over to the genio framework (commit 6bdaabecae11ca6aaa61ef3c8c07e11a50f020ee), the ability to send a serial break on telnet sync was lost. Being able to send a serial break is very useful when debugging linux kernel problems as it enables the use of the magic sysrq functionality.

**Comment by russdill** [comment]
Ah, thanks. Sending a break is much easier. Can you remove the telnet-brk-on-sync config option or document it as "does nothing" as to not break previous configurations that contain it?

**Comment by cminyard** [comment]
On Thu, Mar 23, 2023 at 04:33:08PM -0700, Russ Dill wrote:
> Ah, thanks. Sending a break is much easier. Can you remove the telnet-brk-on-sync config option or document it as "does nothing" as to not break previous configurations that contain it?

Actually, I've fixed it to do what it was supposed to do.  It should now
do something :).

-corey
