### ISSUE TITLE
Can only write, but not read from lp device.

### ISSUE THREAD

**Issue by zcattacz** [cminyard/ser2net#98]
Hi, thank you for building such a handy tool. 
I have label printers connected to Openwrt router, with ser2net (`ser2net 3.5.1-5`) forwarding the `/dev/usb/lp0` device to port 9900. I can script to write to port 9900 to get labels printed, but writing status command and reading from that port won't return anything, the read call either timeout or blocked forever. I wonder if ser2net support `O_RDRW` mode for lp device, is there any way to enable that. 
I can confirm the USB printer works when connected to my computer and status can be read when opening the lp device in `os.O_RDRW` mode in python, after os.write() a get_status command.

```
# /tmp/ser2net.conf
9108:rawlp:5:/dev/usb/lp0:9600 8DATABITS NONE 1STOPBIT -XONXOFF

```

**Comment by morganchristiansson** [comment]
Hello. I can't help much but I just happen to be searching for rawlp on github:

rawlp is read only / one -way per code:
https://github.com/cminyard/ser2net/blob/3a00a838d65c76ed3da973fa596f5ac5d095a883/portconfig.c#L969-L972

maybe try port raw for two-way? https://github.com/cminyard/ser2net/issues/59#issuecomment-961303341

**Comment by cminyard** [comment]
On Tue, Jun 20, 2023 at 04:04:42AM -0700, Morgan Christiansson wrote:
> Hello. I can't help much but I just happen to be searching for rawlp on github:
> 
> rawlp is read only / one -way per code:
> https://github.com/cminyard/ser2net/blob/3a00a838d65c76ed3da973fa596f5ac5d095a883/portconfig.c#L969-L972

Yes, that is correct, it is only designed for /dev/lpX devices, which
are write-only.

> 
> maybe try port raw for two-way? https://github.com/cminyard/ser2net/issues/59#issuecomment-961303341

Maybe that will work.  If you don't specify any port configuration I
think it will skip serial port initialization, but I'm not 100% sure.

-corey

**Comment by zcattacz** [comment]
I tried all modes before, raw give the following setup error
```
root@OpenWrt:~# nc 127.0.0.1 9108
Device open failure: OS error, see logs
root@OpenWrt:~# logread|tail
Sat Jun  3 22:48:26 2023 daemon.err uhttpd[1569]: [info] luci: accepted login on /admin/services/ser2net/proxies for root from 127.0.0.1
Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 76 for databits: Interrupted system call
Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 77 for stopbits: Interrupted system call
Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 78 for parity: Interrupted system call
Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 80 for remctl: Interrupted system call
```
Either `raw` or `rawlp` working is fine. I hope ser2net could provide a way that works. It's not uncommon for label printers to have status command sets that will return printer state, mileage etc.
In my early testing I just use socat to forward, but It's console only, `luci-app-ser2net` is much friendlier for other non terminal users to config and maintain.

**Comment by cminyard** [comment]
On Tue, Jun 20, 2023 at 08:35:06AM -0700, zcattacz wrote:
> I tried all modes before, raw give the following setup error
> ```
> ***@***.***:~# nc 127.0.0.1 9108
> Device open failure: OS error, see logs
> ***@***.***:~# logread|tail
> Sat Jun  3 22:48:26 2023 daemon.err uhttpd[1569]: [info] luci: accepted login on /admin/services/ser2net/proxies for root from 127.0.0.1
> Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 76 for databits: Interrupted system call
> Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 77 for stopbits: Interrupted system call
> Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 78 for parity: Interrupted system call
> Sat Jun  3 22:49:07 2023 user.err : error setting default value on line 80 for remctl: Interrupted system call
> ```

Yeah, I was afraid of this.  It's trying to do serial setup on the
device.  What's the ser2net.conf file?  Did you enter anything after the
device?  The line should be something like:

5001:raw:0:/dev/usb/lp0

I think that will work, but again, I'm not 100% sure.  This version is
really old.

> Either `raw` or `rawlp` working is fine. I hope ser2net could provide a way that works. It's not uncommon for label printers to have status command sets that will return printer state, mileage etc.

"raw" is working fine?  I thought it was failing.

> In my early testing I just use socat to forward, but It's console only, `luci-app-ser2net` is much friendlier for other non terminal users to config and maintain.

If you could get OpenWRT to upgrade to a modern version of ser2net, that
would be a huge help.  Version 3.5.1 is 5 years old.

-corey

**Comment by cminyard** [comment]
On Tue, Jun 20, 2023 at 12:28:30PM -0700, Morgan Christiansson wrote:
> Openwrt  23.05.0-rc1 has ser2net  4.3.5. Still uses the same, now deprecated, ser2net.conf tho

Ah, good, except for the conf file.  I guess zcattacz is using an old
version of OpenWRT.

I'm not sure this will work in either the old or new version of ser2net.
It's at least not clear.  So I have added a "dev" gensio to the new
version to allow for this sort of thing.  But you will need to use the
yaml config file to use it.

**Comment by morganchristiansson** [comment]
Notice the -rc1. Upgraded ser2net is in OpenWRT 23.05.0 _release candidate_. It may not help but nice upgrade nonetheless.

I need to switch to yaml config to set `dtr=off,rts=off` for my Slaesh zigbee usb stick which was previously fixed in #46.
So I've started a PR to switch to ser2net.yaml config: https://github.com/openwrt/packages/pull/21409

I came across this issue trying to figure out how to set  `rawlp`  in the new yaml config - which seems to be `serialdev(wronly=true)`. OpenWRT init scripts auto generates /tmp/ser2net.conf from [OpenWRT uci config](https://openwrt.org/docs/guide-user/base-system/uci). It was probably wise to upgrade without changing the config as it's a bit of work to update while keeping backwards compatibility. If you have any comments or would like to follow progress it would be appreciated.

Not sure if you use OpenWRT - here's screenshots from OpenWRT admin UI luci to give an idea of how we configure it.

![luci ser2net settings](https://github.com/cminyard/ser2net/assets/66844/9e2b4249-096a-492d-b1c9-3c3831069fa3)
![lluci ser2net proxies](https://github.com/cminyard/ser2net/assets/66844/83a9238e-0254-4643-bb04-25d7eb0f1c6a)

Anyhow sorry for sidetracking this issue. Thanks for the good work and it's a pleasure to help out in a small way.

**Comment by cminyard** [comment]
On Tue, Jun 20, 2023 at 03:13:10PM -0700, Morgan Christiansson wrote:
> Notice the -rc1. Upgraded ser2net is in OpenWRT 23.05.0 _release candidate_. It may not help but nice upgrade nonetheless.
> 
> I need to switch to yaml config to set `dtr=off,rts=off` for my Slaesh zigbee usb stick which was previously fixed in #46.
> So I've started a PR to switch to ser2net.yaml config: https://github.com/openwrt/packages/pull/21409
> 
> I came across this issue trying to figure out how to set  `rawlp`  in the new yaml config - which seems to be `serialdev(wronly=true)`.

It's `serialdev,/dev/lp0,wronly`

With the new changes I just added, it would be `dev(wronly),/dev/lp0`
which makes a little more sense, but won't be available yet.

> OpenWRT init scripts auto generates /tmp/ser2net.conf from [OpenWRT uci config](https://openwrt.org/docs/guide-user/base-system/uci). It was probably wise to upgrade without changing the config as it's a bit of work to update while keeping backwards compatibility. If you have any comments or would like to follow progress it would be appreciated.
> 
> Not sure if you use OpenWRT - here's screenshots from OpenWRT admin UI luci to give an idea of how we configure it.

I run OpenWRT on all my routers, but I don't use them for ser2net.

The new version of ser2net is a lot more capable, you can do encryption,
authentication, and a host of other things.  I'm not sure how you would
represent all that in luci, and maybe it's not necessary, I don't know.

> 
> ![luci ser2net settings](https://github.com/cminyard/ser2net/assets/66844/9e2b4249-096a-492d-b1c9-3c3831069fa3)
> ![lluci ser2net proxies](https://github.com/cminyard/ser2net/assets/66844/83a9238e-0254-4643-bb04-25d7eb0f1c6a)
> 
> Anyhow sorry for sidetracking this issue. Thanks for the good work and it's a pleasure to help out in a small way.

Not a problem.  Thank you.

-corey

**Comment by morganchristiansson** [comment]
> It's `serialdev,/dev/lp0,wronly`

Oh. `serialdev[(<options>)],<device>[,<serialoption>[,<serialoption>]]` from man 5 gensio led me to believe it's specified as \<options>. Thanks!

> you can do encryption

Yes I had same thought. There's a lot of options in the yaml. Hopefully be easy to add in a follow up PR.

**Comment by morganchristiansson** [comment]
Ah my bad - I missed this line from man 5 gensio when I was scanning:
> There are a plethora of **serialoptions**, available as defaults:

maybe it should be a heading to help poor users who scan without reading :man_facepalming:

**Comment by cminyard** [comment]
On Tue, Jun 20, 2023 at 05:03:49PM -0700, Morgan Christiansson wrote:
> Ah my bad - I missed this line from man 5 gensio when I was scanning:
> > There are a plethora of **serialoptions**, available as defaults:
> 
> maybe it should be a heading to help poor users who scan without reading :man_facepalming: 

Point taken, it should have been.

**Comment by zcattacz** [comment]
> Yeah, I was afraid of this. It's trying to do serial setup on the device. What's the ser2net.conf file? Did you enter anything after the device? The line should be something like: 5001:raw:0:/dev/usb/lp0 I think that will work, but again, I'm not 100% sure. This version is really old.
```
cat /tmp/ser2net.conf
9108:raw:5:/dev/usb/lp0:9600 8DATABITS NONE 1STOPBIT -XONXOFF

uname -a
Linux OpenWrt 5.15.114 #0 Sat Jun 3 09:42:00 2023 mips GNU/Linux
```
Openwrt is on the latest firmware I can find.

> Either `raw` or `rawlp` working is fine. I hope ser2net could provide a way that works. It's not uncommon for label printers to have status command sets that will return printer state, mileage etc.
> "raw" is working fine? I thought it was failing.
Sorry, I mean, it would be really nice, if it works, whether it is `raw` or `rawlp` mode really doesn't matter.

> If you could get OpenWRT to upgrade to a modern version of ser2net, that
> would be a huge help.  Version 3.5.1 is 5 years old.
Could you let me know what is the latest ser2net that would work with `libgensio0 - 2.4.2-1` ?
If the dependency is simple, maybe the bin can be build with the downloadable `openwrt-toolchain`,

**Comment by cminyard** [comment]
On Tue, Jun 20, 2023 at 07:15:55PM -0700, zcattacz wrote:
> > Yeah, I was afraid of this. It's trying to do serial setup on the device. What's the ser2net.conf file? Did you enter anything after the device? The line should be something like: 5001:raw:0:/dev/usb/lp0 I think that will work, but again, I'm not 100% sure. This version is really old.
> ```
> cat /tmp/ser2net.conf
> 9108:raw:5:/dev/usb/lp0:9600 8DATABITS NONE 1STOPBIT -XONXOFF

Looking at the code a little more, I don't think it's going to work.
You could try removing the ":9600 8DATABITS NONE 1STOPBIT -XONXOFF" part
and see, but I don't think it's going to matter.

> 
> uname -a
> Linux OpenWrt 5.15.114 #0 Sat Jun 3 09:42:00 2023 mips GNU/Linux
> ```
> Openwrt is on the latest firmware I can find.
> 
> > Either `raw` or `rawlp` working is fine. I hope ser2net could provide a way that works. It's not uncommon for label printers to have status command sets that will return printer state, mileage etc.
> > "raw" is working fine? I thought it was failing.
> Sorry, I mean, it would be really nice, if it works, whether it is `raw` or `rawlp` mode really doesn't matter.
> 
> > If you could get OpenWRT to upgrade to a modern version of ser2net, that
> > would be a huge help.  Version 3.5.1 is 5 years old.
> Could you let me know what is the latest ser2net that would work with `libgensio0 - 2.4.2-1` ?
> If the dependency is simple, maybe the bin can be build with the downloadable `openwrt-toolchain`, 

Unfortunately, I don't think there is a released version that will do
what you want.  A lack of foresight on my part, but I guess you can't
see everything.  I have just added the code to do this to the gensio git
repository, and it should work, and I can do a release for you if you
like.  But you would have to compile the gensio library and compile
ser2net against it and install it on OpenWRT.  I don't know how to do
those things on OpenWRT.

**Comment by cminyard** [comment]
Can you build the versions of gensio and ser2net that are latest in git?  They should solve your problem.  You can specify the device as:

  dev,/dev/usb/lp0

in the connector and it should work like what you want.

**Comment by cminyard** [comment]
Oops, didn't mean to close this.

**Comment by cminyard** [comment]
Not hearing anything, I assume this is fixed.
