### ISSUE TITLE
configure.ac: autoconf: obsolete $as_echo, STDC_HEADERS

### ISSUE THREAD

**Issue by pvn44** [cminyard/ser2net#99]
Ubuntu 22.04 under VMware on Mac w/ M1 processor.

Building gensio-2.6.6 works fine.
Building ser2net-4.3.12 fails on the autoconf step:

$ libtoolize
$ aclocal
$ autoconf
configure.ac:20: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/ax_pthread.m4:89: AX_PTHREAD is expanded from...
configure.ac:20: the top level
configure.ac:76: warning: The preprocessor macro `STDC_HEADERS' is obsolete.
configure.ac:76:   Except in unusual embedded environments, you can safely include all
configure.ac:76:   ISO C90 headers unconditionally.

$ automake -a
tests/Makefile.am:4: warning: shell readlink -f $(top_builddir: non-POSIX variable name
tests/Makefile.am:4: (probably a GNU make extension)
tests/Makefile.am:5: warning: shell readlink -f $(top_srcdir: non-POSIX variable name
tests/Makefile.am:5: (probably a GNU make extension)

$ ./configure
....
./configure: line 13795: syntax error near unexpected token `GENSIO,'

./configure: line 13795: `PKG_CHECK_MODULES(GENSIO, libgensio, LIBS="$LIBS $GENSIO_LIBS",'

Again, gensio was built successfully from source.

Now I'm not an expert on this configure stuff, so probably it's my fault.
What did I do wrong? How can I fix this?

**Comment by cminyard** [comment]
On Thu, Jun 22, 2023 at 05:34:23AM -0700, pvn44 wrote:
> Ubuntu 22.04 under VMware on Mac w/ M1 processor.
> 
> Building gensio-2.6.6 works fine.
> Building ser2net-4.3.12 fails on the autoconf step:
> 
> $ libtoolize
> $ aclocal
> $ autoconf
> configure.ac:20: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
> lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
> lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
> ./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
> ./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
> m4/ax_pthread.m4:89: AX_PTHREAD is expanded from...
> configure.ac:20: the top level
> configure.ac:76: warning: The preprocessor macro `STDC_HEADERS' is obsolete.
> configure.ac:76:   Except in unusual embedded environments, you can safely include all
> configure.ac:76:   ISO C90 headers unconditionally.

Yeah, I just need to clean those up.  I've done it.

> 
> $ automake -a
> tests/Makefile.am:4: warning: shell readlink -f $(top_builddir: non-POSIX variable name
> tests/Makefile.am:4: (probably a GNU make extension)
> tests/Makefile.am:5: warning: shell readlink -f $(top_srcdir: non-POSIX variable name
> tests/Makefile.am:5: (probably a GNU make extension)

This is normal, the test scripts do something a little strange.  I
should probably figure out a way around this some day...

> 
> $ ./configure
> ....
> ./configure: line 13795: syntax error near unexpected token `GENSIO,'
> ./configure: line 13795: `PKG_CHECK_MODULES(GENSIO, libgensio, LIBS="$LIBS $GENSIO_LIBS",'
> 

Is pkg-config installed?  I think that's what you would get if it
wasn't.  That's an m4 macro that should come from there.

> 
> Again, gensio was built successfully from source.
> 
> Now I'm not an expert on this configure stuff, so probably it's my fault.
> What did I do wrong? How can I fix this?

Yeah, it's fairly messy.  I've tried to make it as easy as possible from
the READMEs, but there's always something that causes issues.

-corey

**Comment by pvn44** [comment]
> Is pkg-config installed?  I think that's what you would get if it
> wasn't.  That's an m4 macro that should come from there.

That was it! It builds now. Thanks!
